### ISSUE TITLE
Replace the tinymce editor with another one

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1046]

**Comment by rrenkert** [comment]
With newer Office versions there are problems with copy/paste in our currently used tinymce version.
We need an investigation of other editors or what is necessary to use tinymce with newer Office.

Most important:
* compatible FS License
* copy/paste
* text format

**Comment by Elblinator** [comment]
TinyMCE 5.10.6 has issues if text from office 365 (with certain formatting) is copy and pasted into it. Words vanish.

The following are possible other Editors which could be a replacment

| Editor/Demo  | Stable? | Implement Effort |  Angular | Last commit (today 13.Jul.23) | Licence | Format | 
|-------------------|------------|------------------------|------------|-----------------------------------------|------------|-----------|
| [CKEditor](https://ckeditor.com/ckeditor-5/demo/)       |  Y      |   |   Y | 12.Jul.23      | GNU General Public License Version 2 or later |   |
| [Quill](https://quilljs.com/playground/)  |  Y           |  medium(?)           |  Y         |  6.Jul.23                                   | BSD-3-Clause license | bullet point issues |
| [ProseMirror](https://prosemirror.net/examples/) |  Y |  high                     | Y          |  11.Jul.23                                 | MIT licence  |    bullet point issues  |
| [TipTap](https://tiptap.dev/editor) |  Y         | medium/high        |  Y         |   11.Jul.23                                | MIT licence | bullet point issues |
| [ReMirror](https://remirror.io/) |  Y      |  low                      |  ?         |  6.Jul.23                                  |MIT licence |bullet point issues  | 
| [DesktopEditor OnlyOffice](https://www.onlyoffice.com/see-it-in-action.aspx) | Y   |  ? |  Y   |   16.Jun.23   | MIT licence | |

**Comment by bastianjoel** [comment]
ProseMirror does not have a production ready menu bar. Therefore I would say that the implementation effort would be way too high. 
ReMirror is react only. 

As discussed with @rrenkert I will implement a version with TipTap.
