### ISSUE TITLE
Check if a user can create multiple amendments at once

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1055]
1. Create paragraphbased amendments
2. Try to create one (choose a motion, choose some paragraphs and change something)
3. Try to click multiple times on the "Create" button (this must happen quickly, before the router navigates to another page)

**Comment by emanuelschuetze** [comment]
works for me in current main branch

**Comment by luisa-beerboom** [comment]
> works for me in current main branch

If I try, what I stated above it in the current main branch, my stated result still happens. Maybe the "back"-button should be disabled as soon as the create-button has been clicked.

**Comment by MSoeb** [comment]
> > works for me in current main branch
> 
> If I try, what I stated above it in the current main branch, my stated result still happens. Maybe the "back"-button should be disabled as soon as the create-button has been clicked.

Thanks for the advise. Please implament the disabled back button, while the spinner is active. 

Additonally: The original problem doesn't exist anymore. It seems to be fixed by another update.

**Comment by emanuelschuetze** [comment]
good enough for 4.0. closed.
