### ISSUE TITLE
Error while creating a permission

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1059]
**Describe the bug**

`…/motions/workflow/…`

Adding a new column or permission within a workflow results in the following error message: 
`data must not contain {'collection'} properties` 
→ No new permission is created and it is not possible to continue working.

**OpenSlides-Version**
4.0.0-beta-20220429-b1f2574

**Comment by jsangmeister** [comment]
sounds similar to https://github.com/OpenSlides/openslides-client/issues/1019
