### ISSUE TITLE
Parent agenda item is ignored

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1060]
**Describe the bug**

`…topics/new…`

If you select a parent agenda item when creating an agenda item, the selection made will be ignored. The agenda item appears then at the bottom of the list and not below the selected parent item. The agenda item must then be sorted manually using: `⁝ › Sort`

**Expected behavior**
The selected parent agenda item should be correctly inherited and the agenda item should be sorted under the selected parent.

**OpenSlides-Version**
4.0.0-beta-20220429-b1f2574

**Comment by jsangmeister** [comment]
Cannot reproduce:
1. Goto https://demo.os4.openslides.com/11/agenda
2. Click the "plus" button
3. Enter title and select e.g. "Motion 02 - Entlastung des Vorstandes" as parent
4. Click "Save" -> the newly created agenda item has the correct parent and is correctly displayed.

Maybe there are some more factors to this? If so, please provide a detailled description of these.

**Comment by GabrielInTheWorld** [comment]
Please re-test on version: 4.0.0-beta-20220502-464a0e5

**Comment by alveolus** [comment]
**The bug is fixed.** The selected parent agenda item will now be saved correctly again and the agenda item will be sorted under the selected parent item. Closing the issue now.

Tested on: 4.0.0-beta-20220502-464a0e5
