### ISSUE TITLE
Not possible to add tags to agenda items

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1061]
`…/agenda`

**Describe the bug**
It is currently not possible to add tags to agenda items. The selected tag is not inserted. Nothing happens.

**OpenSlides-Version**
4.0.0-beta-20220429-b1f2574

**Comment by GabrielInTheWorld** [comment]
Please test this on version 4.0.0-beta-20220510-c5b9559

**Comment by alveolus** [comment]
Successfully tested.

**Comment by jsangmeister** [comment]
`Successfully` meaning the error does not appear anymore or you recreated the error successfully? In the former case, you can close this issue.

**Comment by alveolus** [comment]
I mean: The bug is fixed. :) I can tag agenda items successfully. Closing the issue now.
