### ISSUE TITLE
CSV import of participants: Automatic generation of the user name

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1103]
`…/users/import`

**Problem:**
When importing the CSV file for the import of participants, the column "Username" must currently contain text and must not be empty. Otherwise, no import will take place. If the column does not contain any text, then no preview is displayed. 

Also no error message will be displayed indicating that the column "Username" has not been filled in. The fact that no error message is displayed is probably related to: https://github.com/OpenSlides/openslides-client/issues/1081

**Expected behaviour:**
If the column "Username" is left empty in the CSV file for the import of participants, then a username should be generated automatically according to the currently valid rules as is the case when a user is created manually. 

This means (as far as I know): First name and surname are put together, no spaces in the string, if _MaxMustermann_ already exists and the e-mail addresses do not match, then the username _MaxMustermann1_ is generated. Basically, this is exactly how the current rules dictate when you create a person manually.

**Why?**
The admins of an event should not be expected to compose the user name "correctly". Especially since they cannot know whether there is a MaxMustermann in the system or not.

**Comment by emanuelschuetze** [comment]
works in current 4.0-rc version
