### ISSUE TITLE
Email subject is sent in English, although another language is selected for the interface

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1104]
`.../settings/participants`
Affects the interface in non-English language.

### Description
The email **subject** of the invitation email under _Settings_ › _Participants_ is correctly displayed in German language: "OpenSlides-Zugangsdaten". 

If the email **body** is now adjusted by someone as usual to German and an invitation email is sent, the email **subject** is still in English: "OpenSlides access data". Only after customizing the email subject (e.g. "Zugangsdaten für OpenSlides") the custom email subject will be used for the emails as shown.

### Expected behavior
The email subject should be sent as it is displayed in the interface, e.g. in German: "OpenSlides-Zugangsdaten". Preferably in the language that the user - who has the permission to send the invitation email - has selected for the OpenSlides interface.

**Comment by jsangmeister** [comment]
This is due to the fact that we do not have the possibility to translate strings in the backend yet. See https://github.com/OpenSlides/openslides-backend/issues/994 for progress.
