### ISSUE TITLE
Check in which component the `translate.instant` function can be replaced by the marker (also seen as `_`)

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1112]
I think the function `translate.instant` (provided by the `TranslateService`) is only in services and pipes required. In components, the marker function should be used and sufficient.

**Comment by jsangmeister** [comment]
Looked through the components using `translate.instant` and it seems the only uses are for titles, dialog titles and content, snackbars, errors, dynamically created strings and other places where an instant translation is necessary, so I'm closing this.
