### ISSUE TITLE
Read/Write permissions for comment fields do not get saved

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1118]
`…/motions/comment-sections`

The selected "Groups with read permissions" and "Groups with write permissions" for comment fields do not get saved.

**Expected behavior:**
Selection is saved correctly.

Version: 4.0.0-beta-20220513-73ddad1

**Comment by GabrielInTheWorld** [comment]
Please re-test with the latest version. I cannot reproduce it.

**Comment by alveolus** [comment]
The bug is no longer there in version 4.0.0-beta-20220517-110f4d7. The read/write permissions are saved correctly. I am closing the issue.
