### ISSUE TITLE
Offer sample file for importing participants additionally as Excel file

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1154]
**Problem**
Employees in the administration are usually overwhelmed with the CSV file because various versions of Excel do not seem to be able to open the CSV file correctly. It does not seem to matter which separator is used for all CSV exports and examples.

**Suggestion**
The example file for importing participants is also offered as an Excel file.

**Comment by jsangmeister** [comment]
Not sure how practical that is, because we do not offer excel imports (and I don't think we want to change that). If we offer an excel example file, people will be confused because they cannot import it, which kind of defeats the whole purpose of an example file.

**Comment by emanuelschuetze** [comment]
we don't want any excel examples in client code for download. see faq for more help.
