### ISSUE TITLE
Ignore spelling (upper/lower case) of e-mail addresses

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1157]
`…/participants/new`

**Problem**
When adding participants manually, the system checks whether there is already an account for the specified e-mail address. If the e-mail address is entered differently than it is stored in the existing account, no match is made. The e-mail address must be written exactly the same (upper/lower case).

**Suggestion**
When checking, it should not matter how exactly the e-mail address is written. Upper/lower case should be ignored.

**Example**
Maxi.Muster@OpenSlides.com
maxi.muster@openslides.com
→ It's a Match! Despite different spellings.

**Comment by GabrielInTheWorld** [comment]
Relates to OpenSlides/openslides-backend#1334

**Comment by jsangmeister** [comment]
Done in the backend, so I think this can be closed
