### ISSUE TITLE
List of committees do not get loaded/displayed

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1159]
`…/committees`
Version: 4.0.0-beta-20220517-110f4d7

### Problem
The list of committees do not get loaded/displayed. Search is not possible. There should be 7031 committees to see. Exactly 0 are displayed. The reason for this is not obvious.

The following (handle stream) error is displayed in the console:

<img width="625" alt="Bildschirmfoto 2022-05-19 um 14 38 00" src="https://user-images.githubusercontent.com/23032204/169294968-9cc2c58c-023a-4d8c-a639-9f795e794c1a.png">

**Comment by GabrielInTheWorld** [comment]
Since your marked version is two versions behind the latest, we need an info here, if this behavior is still existing.

@alveolus: Please check with the latest version and give us steps to reproduce, if the behavior is still existing.

**Comment by alveolus** [comment]
The bug occurs in a production environment, so I can't test locally with a current (dev) version.

@emanuelschuetze Can you please provide an update for the production and training environment?

**Comment by alveolus** [comment]
@emanuelschuetze has analysed the problem with @ostcar. A timely bug fix would be great.

**Comment by ostcar** [comment]
This should be fixed with https://github.com/OpenSlides/openslides-autoupdate-service/pull/479

**Comment by alveolus** [comment]
The error no longer occurs in version 4.0.0-beta-20220520-b5ddb57. The list is fully loaded after 2-3 seconds and shows all 7031 committees as well as the tags correctly.
