### ISSUE TITLE
The requests for list-of-speaker creating/removing speakers for the user need a user_id in payload

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-client#116]
The payload description for the corresponding actions on backend side requires a user_id, identical to the user of the request, to work properly

**Comment by FinnStutzenstein** [comment]
Yes, the `user_id` is always required: https://github.com/OpenSlides/openslides-backend-coordination/issues/84

**Comment by GabrielInTheWorld** [comment]
Adding/removing a speaker works properly. Only adding/removing a "point of order" does not work properly until now. This will be fixed with #127.
