### ISSUE TITLE
Support for DIN SPEC 91379 in PDF prints

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1172]
Some letters and characters are not printed in PDF files. These are characters that should be processed according to DIN SPEC 91379 ("Characters in Unicode for the electronic processing of names and data exchange in Europe"). These letters and characters are used especially in names whose spellings are variations of basic Latin. Like the letter `Ş` in my surname. ;-)

[DIN SPEC 91379.pdf](https://github.com/OpenSlides/openslides-client/files/8745787/DIN.SPEC.91379.pdf)

I have attached a PDF showing which letters and characters are printed and which are not. The printed text is this example file from DIN 91379: https://github.com/String-Latin/DIN-91379-Characters-and-Sequences/blob/main/latin_list_all_en.txt

For more information see: https://github.com/String-Latin/DIN-91379-Characters-and-Sequences

**Comment by jsangmeister** [comment]
I think this is a bug rather than a feature - maybe @m-schieder an take a look at this?

**Comment by m-schieder** [comment]
I think this is because the fonts we use for PDF export do not contain these characters. I'll take a closer look.

**Comment by m-schieder** [comment]
The problem also exists with other fonts that contain these characters. These characters are also transferred correctly to pdfmake.  In [pdfmake playground](http://pdfmake.org/playground.html) such characters can be displayed. Either pdfmake cannot interpret the font I am using correctly or there is something wrong with our implementation of pdfmake.

**Comment by emanuelschuetze** [comment]
@alveolus can you create a pull request - or send me the new woff files

**Comment by alveolus** [comment]
@emanuelschuetze Use [this file](https://github.com/String-Latin/DIN-91379-Characters-and-Sequences/blob/de3e846e674111c5f6d6ca40a145f24c52f818cf/latin_letters_1.3.txt) for comparison: If you see more characters with the new fonts than before (or than in [this file](https://github.com/OpenSlides/openslides-client/files/10014640/DIN-91379-Characters-and-Sequences_latin_letters_1.3.txt.pdf), created with the font files without Latin extended), then everything works fine.

In the user interface you can see the change best in the account list: Create an account that contains the letter `Ş` in its name. If the letter is displayed in the same font and size as the rest of the name/text, then everything works here too.
