### ISSUE TITLE
Cannot deselect custom font

### ISSUE THREAD

**Issue by m-schieder** [OpenSlides/openslides-client#1190]
When a custom font is selected, it cannot be deselected.

**Comment by jsangmeister** [comment]
Can you provide more detailed steps to reproduce? Only thing I found is a missing autoupdate:
1. upload a font
2. select it for two places
3. try to deselect the first place -> request succeeds, but the checkbox stays marked -> reload needed

**Comment by m-schieder** [comment]
Yes, this is exactly the behavior I mean. However, from autoupdate comes the correct list of selected options. Only the client does not display this information correctly once two options have been selected. 

Also the display if the font is used is broken. This function does not seem to be implemented in os4 yet.

**Comment by m-schieder** [comment]
In os3 there is an indicator if an image or a font is in use. The icon for this is to the left of the three dots menu. In os4 this icon is always displayed.

**Comment by rrenkert** [comment]
Additionally:
The indicator icon in the list of fonts and images should only appear if the item is used.

**Comment by jsangmeister** [comment]
I think https://github.com/OpenSlides/openslides-client/pull/1570 reintroduced this error: 
1. Upload logo to https://demo.os4.openslides.com/
2. Select as e.g. web header
3. Deselect again -> request is send correctly, but the changes are not displayed
