### ISSUE TITLE
Y, N, A, votesvalid, votesinvalid, votescast are numbers not strings

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#120]
I tried to create a new poll with the following data:
```
[{'action': 'poll.create', 'data': [{'meeting_id': 1, 'title': 'Abstimmung', 'pollmethod': 'YNA', 'publish_immediately': True, 'type': 'analog', 'options': [{'content_object_id': 'motion/4', 'Y': 2, 'A': 4, 'N': 20}], 'votescast': 80, 'votesinvalid': 4, 'votesvalid': 22, 'content_object_id': 'motion/4'}]}]
```

The backend sends me the following error:
`Fehler: data.votesvalid must be string or null`

But, votesvalid, votesinvalid and votescast has to be numbers as it is defined the [openslides-backend-coordination](https://github.com/OpenSlides/openslides-backend-coordination/issues/117). Am I right?

EDIT:
If I try to send those values as numbers, the backend sends me the following answer:
`Fehler: data.votesvalid must match pattern ^-?(\d|[1-9]\d+)\.\d{6}$`

**Comment by GabrielInTheWorld** [comment]
> As discussed: The client should send decimal numbers.

Is this the same as the value `vote_weight` for users?

**Comment by FinnStutzenstein** [comment]
> Is this the same as the value `vote_weight` for users?

I think so.
