### ISSUE TITLE
Investigate if MeetingControllerService providing templates is causing problems somewhere

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1237]
`MeetingControllerService`'s `getViewModelListObservable()` provides not only the relevant meetings that the operator should be able to see, but also all template meetings (for the sake of being able to duplicate from them even if the operator technically doesn't have access).

This previously caused a problem in the dashboard/calendar, where meetings were shown, that shouldn't be there ( see #1201 fixed with #1226).

At some point we should probably take a look at whether there are any further instances where calls to this viewModelList may be causing similar problems

**Comment by GabrielInTheWorld** [comment]
Maybe, we should then implement a function to get only template meetings as an observable and the `getViewModelList (Observable)` should only propagate meetings, which are available for the operator.
