### ISSUE TITLE
Generic copy-code for repositories

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#124]
We need a solution to reduce the amount of explicit copying in the repos. This is too explicit and repetitive.

**Comment by GabrielInTheWorld** [comment]
There are already decorators under `app/infrastructure/annotations`, which are functionaning. Feel free to use and enhance them.

**Comment by rrenkert** [comment]
Based on the last comment, ithink we can close here.
If we need futher enhancements we can open a new issue.
