### ISSUE TITLE
The projector detail view won't be updated even if autoupdates are received

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1244]
Go to the detail view of a projector and try to start a countdown -> the countdown does not start.

**Comment by luisa-beerboom** [comment]
Cannot be replicated on current main branch, might instead be a problem with the current (more complicated) production setup (and its AU service). Should probably put this one aside, until that is cleared up

**Comment by GabrielInTheWorld** [comment]
I cannot reproduce this on the public [demo](https://demo.openslides.os4.com), too (version: 4.0.0-beta-20220608-4cc5c55).

**Comment by GabrielInTheWorld** [comment]
I will close this. @emanuelschuetze or @alveolus feel free to re-open this issue, if this behavior still occurs.
