### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1257]
- [x] motion list: "by xy ·sequential_number" → a space should be after the middot
- [x] #1325
- [x] motion detail view: The tooltip "Mark as favorite" should only be visible if a user hovers over the icon
- [ ] motion detail view: The box for the summary of every changes (amendment, change recommendation) should be outlined
- [x] #1326
- [x] #1327
- [x] #1329
- [x] #1328

**Comment by luisa-beerboom** [comment]
@emanuelschuetze I couldn't identify three of them, so I split off the rest into their own issues and solved them all in pull #1330 .

Please check if the other problems are still present, if they are solved this issue may be closed.
