### ISSUE TITLE
Topic poll projection not functioning

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1275]
Topic poll was implemented in OpenSlides/openslides-client#1010, however the projection-feature is still not implemented/broken and shows an empty slide while throwing an error "slide error:  calculating key [...]" on the slide-container.component.ts

Might not be a pure frontend problem.

**Comment by ostcar** [comment]
You are correct. It should be fixed with this PR: https://github.com/OpenSlides/openslides-autoupdate-service/pull/502

 Please tell me if I should merge this or if there is something else I should fix.

**Comment by jsangmeister** [comment]
At the moment I am not aware of any other changes, but I suggest to just leave it open until the client work is done in case something else comes up.

**Comment by GabrielInTheWorld** [comment]
@luisa-beerboom Please tell, which things have to be done in the client to deal with topic polls.
