### ISSUE TITLE
Sidebar-arrow gets stuck to wrong position on apple-devices

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1281]
Open Safari
-> open sidebar (by using the arrow (>))
-> close sidebar (same button)
=> the (>)-Button gets stuck to the position it would have, if the sidebar was open, instead of moving back to the left side of the page.
Navigating to other pages does not return the button to the correct position.

Some views (for example the projector view) do work as intended, however most other pages seem to have this error.

**Comment by tsiegleauq** [comment]
I used to observe similar behavior in the past. I think it's a bug in (native) web kit. You might be able to reproduce this behavior on gnome empathy (or any other plain WebKit browser, gnome empathy is just the only one that is simply installable)
