### ISSUE TITLE
Do not automatically mark meetings as templates (when duplicating or creating based on a template).

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1305]
<img width="851" alt="Bildschirmfoto 2022-06-22 um 17 56 42" src="https://user-images.githubusercontent.com/23032204/175077341-dab3008d-601c-4068-ab9a-266ccd97eb62.png">

`.../committees/...`

**Problem**
When you duplicate an meeting or create it based on an meeting template (manually as well as via CSV import), the duplicated meeting gets also marked as a meeting template (star icon is active).

**This is how it should be**
Meetings that are duplicated or created based on a template will not automatically be marked as a template.

**Comment by luisa-beerboom** [comment]
Re-opening since we will likely have to change the payloads in the client to actually get the correct object.

**Comment by jsangmeister** [comment]
The default will be `false` to set as template, so, since we do not plan to make this configurable in the client according to @emanuelschuetze, nothing has to be changed in the client.
