### ISSUE TITLE
Missing translation: New category

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1308]
`…/motions/categories`

**Problem**
The name of the text field is only available in English and not in German.

**Solution**
German → Name des neuen Sachgebietes

<img width="418" alt="Bildschirmfoto 2022-06-22 um 19 02 52" src="https://user-images.githubusercontent.com/23032204/175095938-2cd0f327-ab32-4762-98b8-09b4fa57351c.png">

**Comment by jsangmeister** [comment]
I updated the translations file on transifex, there are currently 30 untranslated strings. @emanuelschuetze can you take care of/delegate this? @alveolus with the next translations update, this will be fixed then. I will therefore close this issue

**Comment by jsangmeister** [comment]
see https://github.com/OpenSlides/openslides-client/pull/1351 for updates
