### ISSUE TITLE
In the call list: Put a motion as a child of another motion leads to incorrectly sorted motion list

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1312]

**Comment by luisa-beerboom** [comment]
If the correct result is to keep the sorting in the motionlist the same as before, I cannot replicate this.

**Comment by jsangmeister** [comment]
me neither

**Comment by luisa-beerboom** [comment]
If anyone can replicate this, please fix it, or at least write a description of how to do it
