### ISSUE TITLE
'Error: Anonymous user can not vote' after logging out

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-client#1321]
When logging out while a poll is running an error pop up shows up displaying:
'Error: Anonymous user can not vote'

@luisa-beerboom and i talked a bit about this but were not sure where this arises or were it should be fixed.
@ostcar Do you maybe have some insight on the intended working of this.
My theory is, that the client repeatedly asks the vote service for votes and continues to do so after the logout.
The vote service then sees no session for the user in the auth-service and returns the error message.
If my understanding of the situation is correct it should probably get fixed in the client.

Steps to reproduce (e.g. on nightly.demo.os4.openslides.com):
- create a
  1. committee
  2. meeting
  3. poll
- start the poll
- log out

**Comment by ostcar** [comment]
@peb-adr I als othink, that you understanding is correct.

**Comment by bastianjoel** [comment]
This got fixed by #1662
