### ISSUE TITLE
Participant list in meeting is broken

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#1322]
```
ERROR TypeError: Cannot read property 'source' of undefined
    at n.get totalVoteWeight [as totalVoteWeight] (1947.a1ef17afb6fee0a2.js:1)
```
Probably a missing `?` behind `this.listComponent` in this line: https://github.com/OpenSlides/openslides-client/blob/783ffc09830d5481fe73c24b1c967b343aad8fc3/client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts#L73

**Comment by luisa-beerboom** [comment]
Can't reproduce in current client anymore
