### ISSUE TITLE
Agenda: Tags are not loaded

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1333]
`…/agenda`
`…/motions/tags`

**Problem**
Initially, no tags are displayed in the agenda, although the agenda items are tagged. You first have to go to "Tags" in the three-dots-menu and then back to the agenda so that the tags are displayed next to the agenda items.

**Comment by jsangmeister** [comment]
sounds like a missing autoupdate subscription

**Comment by luisa-beerboom** [comment]
@alveolus How does this look in the current main? Maybe I'm doing something wrong, but I can't get any tags to load at all.
