### ISSUE TITLE
New update strategy for the client

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1339]
Currently, the client requests updates for collections by making several TCP-connections to the AU-service per tab per browser.
There could be up to 20 connections per tab. This is inefficient, if a user uses OpenSlides in multiple tabs.

There are the following options to improve the user experience:
- Combine different connections to one (this will end up in ~4 connections per tab)
- Use the local storage of a browser

The last option is the preferred one. Implement it as described:
- Every time a connection should be established, it will be checked, if there is already made a connection for the same name in another tab
- If a connection was established, append an established connection to a list and write the list in the local storage of a browser
- Write incoming data as a map into the local storage, as well, in the following form:
```ts
interface Map {
  [collection: string]: {
    [id: number]: BaseModel;
  }
}
```
- Listen in the repositories to the data in the local storage instead of their in-memory storage

This should be equivalent to the autoupdate format receiving from the AU-service.

**Comment by jsangmeister** [comment]
We will need some kind of cleanup or check if the connection and information is still up-to-date, since the local storage persists until it is deleted.

**Comment by peb-adr** [comment]
If i read this correctly, this would mean we're introducing yet another layer of caching that needs to be kept valid (I guess @jsangmeister meant pretty much the same)
I'm not sure if this would be a robust long-term solution.

The other proposal we had sounded better to me.
Where every tab opens a single AU connection and every newly requested subscription will add the data flow to the existing connection.
This may have drawbacks compared to the - here preferred - proposal. e.g.
 - Probably needs more adjustment, specifically in the AU
 - Would probably result in much data being transmitted multiple times redundantly
Still I'm worried, that the local storage cache solution would introduce us to more lost updates and inconsistent UI.

**Comment by jsangmeister** [comment]
I agree with @peb-adr, this sounds better. Maybe @ostcar wants to chime in?

**Comment by ostcar** [comment]
I also think that the single AU connection is a good idea.

But I also think, that we should find a solution, that different tabs share the connections. Is a cache in the local storage really necessary for this? I thing it should also be possible to use a service worker for that. When a tab wants to open a connection, it asks the service-worker to do it. The steps in the service worker are the same, as @GabrielInTheWorld descried above. The only difference is, that the data is not written to the local storage, but in memory in the service worker.

**Comment by emanuelschuetze** [comment]
works good enough in current 4.0-rc
