### ISSUE TITLE
Relics in account/user list after deletion of a user

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#1344]
After you delete a user in the account list, the user is removed, but an empty row is appended at the end of the list with only the text "Inactive" on the right side.

**Comment by luisa-beerboom** [comment]
There is now a problem where the client doesn't receive updates from the autoupdate at all, making it impossible for him to know if the user has been deleted.
This may still be a client issue though.

**Comment by jsangmeister** [comment]
@luisa-beerboom do you subscribe to updates to the field `meta_deleted` of all models? This should carry the required information.

**Comment by luisa-beerboom** [comment]
@jsangmeister I tried that, but it didn't work, I think the autoupdate service didn't like it

**Comment by jsangmeister** [comment]
@ostcar just tested it, and it seems like `meta_deleted` is not implemented in the restricter... I'm not sure what the intended way was to subscribe the field (if the client should do it manually or if it should be done autmatically, since it is the same for every models and always needed), but it does not seem to work at the moment. I'm assuming this did work in the past? Or did we just never try to delete models?

**Comment by ostcar** [comment]
The field meta_deletet is not for the client. The datastore needs this field, since there are deleted models. But the autoupdate service returns id:null for deleted models.

If you want to change this, you have to add the field meta_deletet to the models.yml. But this should not be necessary.

**Comment by jsangmeister** [comment]
Ah, thanks for clearing that up. I was sure that I tried it and the id field wasn't `null`, but turns out it is the client who inserts it back in:
![image](https://user-images.githubusercontent.com/33004050/180939929-f7ba883d-2c48-4b49-8c2e-bec093cfd45d.png)
@luisa-beerboom as you can see, the raw data is correct (`id` is `null`), but the processed data used by the client contains it again. Seems like somewhere in the autoupdate adapter, an automatic insertion of the id is taking place, when it should in reality remove the model.
