### ISSUE TITLE
Save language changes

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#1345]
When one changes the language, it is reset on the next reload. We should save this e.g. in the local storage to improve user experience.

**Comment by luisa-beerboom** [comment]
Good idea, however wouldn't it be more prudent to save it in the backend then?
After all, just as it is annoying to have the language change back to default every time you reload, having to change it back every time you log in would be no less annoying.

Could be another field in the user model

**Comment by tsiegleauq** [comment]
As long as you keep using the same device, indexedDB can restore it, even though you close your browser, as long as you don't flush the db (OS might do so when you manually call the logout routine).

**Comment by jsangmeister** [comment]
What sean says - we do not have to couple it to the login, but can store it independently. I don't think this should be a backend feature/field.

**Comment by luisa-beerboom** [comment]
Alright, I guess that works then
