### ISSUE TITLE
media-files: sometimes the files of another meeting are shown. 

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-client#1354]
Test:
0. Navigate into meeting/1.
1. Look at the mediafiles of meeting/1.
2. Create meeting/2
3. Switch into the meeting/2 and look at the mediafiles.
Except: no mediafile
See: the mediafiles from meeting/1

**Comment by jsangmeister** [comment]
probably related to https://github.com/OpenSlides/openslides-client/issues/1192
