### ISSUE TITLE
Participants cannot join a Jitsi conference

### ISSUE THREAD

**Issue by m-schieder** [OpenSlides/openslides-client#1362]
Settings:
* In the Superadmin settings the jitsi domain and room name is specified.
* In the Livestream settings a URl is specified and 'Show live conference window' is checked.
* Also 'Enable virtual help desk room' is checked. 

The current behavior:
* The UI does not display the phone handset.
* When clicking on 'help desk' the message 'JitsiMeetExternalAPI is not defined' appears.
* The style of the buttons is broken

**Comment by tsiegleauq** [comment]
> JitsiMeetExternalAPI is not defined

Sounds like angular bundles cannot find the jitsi JS blob. Perhaps something got moved around in the global jitsi setup(s)
