### ISSUE TITLE
validate meeting date

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-client#1368]
When creating a meeting the start_date and stop_date are not validated.
Specifically end_date can be lower than start_date which shouldn't be the case.

This should be possible relatively easy using angulars validators I think.

**Comment by jsangmeister** [comment]
Same thing for the backend, if we do this. The backend currently does no validation at all.

**Comment by peb-adr** [comment]
> Same thing for the backend, if we do this. The backend currently does no validation at all.

Yeah had the same thought later too.
Should the validation happen in two places tho?

Or should maybe just the backend do the validation and the client will just display the error message? 🤔
That would have have a worse UX though as the problem wouldn't be immediately visible to the user and also wouldn't have translation...

**Comment by jsangmeister** [comment]
That's the age-old validation problem: You always have to validate in both client and server and make sure that the validation stays consistent... So to answer, yes, it should happen in both places for the UX, as you said.

We have to agree on a date format for this to work, though. And the client needs to be able to display it in the user's language and send it to the backend always in the agreed upon format. There is a reason we did not validate this in OS3 when it wasn't needed :D

**Comment by peb-adr** [comment]
Huh, how do we have to "agree on a date format" now? Didn't that already happen?
I was under the impression the backend accepts dates/timestamps in unix format (secs after 1970) and the client would already be converting the entered date to that before sending the request to the backend.
For displaying it in the correct locale-format to the user angular should have us covered, no?

**Comment by jsangmeister** [comment]
You're right, my bad... This should not be much work then.
