### ISSUE TITLE
function "Allow access for anonymous guest users" didn't work

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1381]
Activating the check box has no effect. Guest mode didn't work. No obvious error appears.

Reproduction:
1. Open a meeting. 
2. Go to Settings -> General -> activate check box "Allow access for anonymous guest users" -> save
3. Log out and open the meeting URL again. Normally (like in OS3) the instance should open now in guest view. This didn't happen.

What should happen: Clicking the check box activates the guest mode. After activation, opening the web page again will trigger the guest mode to open. See comparison OS3

![Screenshot_20220718_115856](https://user-images.githubusercontent.com/105491030/179488503-cb9e662b-0fe0-4b8b-9d91-6a450b5485b4.png)

**Comment by luisa-beerboom** [comment]
Probably has something to do with the openslides.service and its bootup function

**Comment by luisa-beerboom** [comment]
In my attempts to solve this I have found multiple places, where the anonymous feature is potentially not implemented:

1. openslides.service bootup(): If there is no access token it navigates to login (I don't think anonymous users have access tokens) => if the operator isn't logged in, he will be rerouted to the login mask
2. Neither the active meeting, nor any meetings at all are loaded when the auth and permission guards are first called, as a result the enabled value can't be checked and will be interpreted as false => the meeting will be treated as if it didn't have guest mode enabled
3. I think the operator service is not correctly handling anonymous users (they should be treated like a normal user who is part of the meetings standard group)

**Comment by rrenkert** [comment]
Talked to @emanuelschuetze and @MSoeb:
Decided to remove the UI for this Option to avoid confusion and to much load.
This is only the first step. This feature should be removed completely in the future.

**Comment by peb-adr** [comment]
We discussed that for the anonymous login we would probably want an implicit group defining access permissions.

It should be ensured at some point that no writing permissions can be granted.\
One proposal was to have checkboxes below the 'activate guest users' one to grant these.\
Whether the implicit group should be shown in the permission matrix is perhaps debatable.

**Comment by MSoeb** [comment]
#3965 <- further implementation and details could be found there.
