### ISSUE TITLE
PDF Export,Texts can have only one decoration

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1385]
If an amendment contains a link, the link will not be shown crossed out in the pdf export of the motion.

Repro:
1. Create motion
2. create an amendment with a link inside the text, NOT at the line start.
3. switch back to the motion.
4. open the 3-dot-menu. choose pdf. 
5. open pdf file. -> link is not crossed out. 

What should happen: The link should be crossed out even in the pdf export file. 

Example image: OS <--> pdf file
![Screenshot_20220705_160316](https://user-images.githubusercontent.com/105491030/179501700-8a5de264-5108-4f12-afe0-eafc59f044e9.png)

**Comment by jsangmeister** [comment]
@m-schieder can you as our pdf expert take a look at this? :D

**Comment by m-schieder** [comment]
@jsangmeister yes, of course. :D

**Comment by m-schieder** [comment]
This affects not only the links described above, but also normal texts with the decoration underline and lineThrough without amendment.
