### ISSUE TITLE
Changes to single votes table

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#139]
(depends on https://github.com/OpenSlides/openslides-backend/issues/628 and https://github.com/OpenSlides/openslides-backend/issues/629)

The single votes table has to be adjusted so it works with the `user_tokens` instead of ids. It has to be also displayed for pseudoanonymous polls. See https://github.com/OpenSlides/OpenSlides/pull/5978 for the changes done to the OS3 client.

**Comment by GabrielInTheWorld** [comment]
@tsiegleauq will this be fixed with #217?

**Comment by tsiegleauq** [comment]
yes
