### ISSUE TITLE
login.spec.ts cypress test failing

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1390]
...due to timeout.
This may not be the only issue though.

**Comment by luisa-beerboom** [comment]
Couldn't replicate that, but this error message seems to originate in the client's `webpack-dev-server` library.
I googled it a bit and it seems that it is the result of a safety feature in that very library, wherein there are a limited number of allowed hosts that can access the server. There are some suggested fixes, some of them apparently dangerous, I tried a few (although I'm not quite sure I did it correctly), none solved the problem.

**Comment by bastianjoel** [comment]
It seems like that reducing the autoupdate requests has an impact on this issue. With #1454 the test isn't failing so far.

**Comment by jsangmeister** [comment]
The error does not happen on every PR, but only on some, as far as I observed it, so I'm not sure if this is really caused by your changes or rather just per chance. But the former would be nicer, of course :D

**Comment by bastianjoel** [comment]
This doesn't seem to be related to specific PRs. I think the test is just randomly failing per action run.
With #1454 the test hasn't failed on any action run as you can see here: https://github.com/OpenSlides/openslides-client/actions?query=branch%3A1339-improve-autoupdate-request-strategy

I also ran the test locally a couple times with the current main and with #1454. On main the test failed every time whereas with #1454 the test succeeded every time.

**Comment by jsangmeister** [comment]
Ok, then let's wait and hope the AU PR already solves the problem.

**Comment by bastianjoel** [comment]
The current AU PR unfortunatly does not solve the problem. 

We could try to allow retries of tests as documented here:
https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries

**Comment by bastianjoel** [comment]
There is an issue #1609 about first login taking long. I think this is related to this issue.
