### ISSUE TITLE
Firefox: Endless loading icon

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#14]
The icon in the firefox-tab do not stop due to the streaming responses. Can we do something against it?

**Comment by ostcar** [comment]
Could you try to add a timeout before connecting to the streaming services?

https://stackoverflow.com/questions/9932462/how-to-remove-safaris-loading-wheel-when-using-server-sent-events

Our should were use websockets? 😀

**Comment by FinnStutzenstein** [comment]
Maybe some browser lifecycle thing. I can imagine, that we should wait for DomContentLoaded or so, before issuing new requests. Maybe browsers think that those early requests are still page loading request. I'll du some experiments tomorrow.

**Comment by FinnStutzenstein** [comment]
OK: We need to start communication (->bootup) in the root-component's `ngOnInit`, which is fired after DomContentLoaded with an async dispatch (-> timeout of 0 seconds). Firefox is ok, but I did not check Edge and Safari.

@jsangmeister I wanted to fiddle around with the communication, so I can include this into  the changes I have in mind.
