### ISSUE TITLE
Add entitled users table

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#140]
(depends on https://github.com/OpenSlides/openslides-backend/issues/630)

The new field `entitled_users_at_stop` contains an array of objects representing all entitlted users at the point of stopping the poll. See https://github.com/OpenSlides/OpenSlides/wiki/poll.stop for the syntax. A new table should display these users inside tabs side-by-side with the single votes table. It should support filtering for the voted state (by typing either `voted:true` or `voted:false`, which can easily be archieved with an additional field containing exactly one of these strings only used for filtering.

The table entries should only be visible to users with `users.can_see_names`, otherwise a warning is displayed.

See https://github.com/OpenSlides/OpenSlides/pull/5978 for the changes done to the OS3 client.

**Comment by GabrielInTheWorld** [comment]
@tsiegleauq will this be fixed with #217?

**Comment by tsiegleauq** [comment]
yes
