### ISSUE TITLE
Motion workflow: can't change the first state

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#1403]
The first state of a workflow cannot be changed.

**Comment by luisa-beerboom** [comment]
What does "change" mean?
I have tried all sorts of things in the workflow settings, but haven't noticed anything weird.
I am also able to change states within the motion detail view without any issues.

**Comment by jsangmeister** [comment]
A workflow has a defined first state in which all motions are put when the workflow is first selected for them. It is saved in `motion_workflow/first_state_id`. This cannot be changed in the client at the moment, while the functionality is present in the backend: https://github.com/OpenSlides/OpenSlides/wiki/motion_workflow.update
