### ISSUE TITLE
Add new 100%-base `entitled`

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#141]
(depends on https://github.com/OpenSlides/openslides-backend/issues/628 since the models changes will be merged there)

The `entitled` base takes the length of the `entitled_users_at_stop` array as the 100%-base.

See OS3 changes: https://github.com/OpenSlides/OpenSlides/pull/5978

**Comment by GabrielInTheWorld** [comment]
@tsiegleauq will this be fixed with #217?

**Comment by tsiegleauq** [comment]
This is was not covered in #217 
apparently it also slipped my migrate-from-os3 list. Perhaps the PR was too old or was skipped during rebase?

**Comment by GabrielInTheWorld** [comment]
This would be possible.
Okay, then we have to implement this feature separately.

**Comment by tsiegleauq** [comment]
if required, I can prolly also include it in #217. Apparently, there still is some more to do in this PR anw

**Comment by tsiegleauq** [comment]
apparently the "entitled" base was covered in #217 already
