### ISSUE TITLE
creating a new motion results in error message in console (impact is unclear)

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1413]
If a user creates a new motion, the console shows an error message. It's unclear, what impact this error could have. The motion creation is not disturbed by it and has no obvious problems. 

Reproduction:
1. open meeting
2. open motions
3. open console in browser
4. create a new motion with plus symbol

What should happen: Clean console log without error.

Error:
![Screenshot_20220720_115545](https://user-images.githubusercontent.com/105491030/179954250-b27487d8-7270-4028-8b62-9dcccd77cea0.png)

**Comment by jsangmeister** [comment]
This is the same cause as #913 and occurs because we warn other users that this motion is currently being edited by another user via ICC. However, I don't know if this feature is implemented in OS4 yet, this should be checked and done.
