### ISSUE TITLE
OS3 meeting upload menu has several bugs

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1415]
The OS3 meeting upload menu has some bugs: 

- [x] the name of the selected file is not displayed.
- [ ] the KnightRider bar has no animation.  
(If a meeting is imported twice, there is no check if users already exist. Users are created again with a number after the name.) -> delegated to backend

Reproduction:
1. download an OS3 meeting file in https://testintern.openslides.com/62/mediafiles 
2. open now on dashboard level committees and open a desired committee
3. click on the three-dot-menu and choose import meeting
4. use the OS3 meeting file and select it for upload
5. try to upload it

For third bug:
6. upload the meeting again and observe/compare duped names.   
 
What should happen:
- File name appears in the upload menu. 
- Addtionally the KnightRider bar works or some other visual feedback appears, which indicates, that the system is still working. Currently, without visual feedback, it is not possible to determine if the system is doing something or if the upload is interrupted.
- The import should check if an account still exists, add it to the meeting and don't create additional duped users with numbers in the name.   

![Screenshot_20220720_124326](https://user-images.githubusercontent.com/105491030/179963437-9df23fe8-f6ec-40e4-931e-0a8dee66bd35.png)

**Comment by luisa-beerboom** [comment]
I do believe the this specific import is handeled in the backend. 
The problems with the display and animation is clearly client-side, however as for the faulty result (of newly created users), that would be a backend problem.

I'm opening an issue in the backend for this.

**Comment by luisa-beerboom** [comment]
Issue created: OpenSlides/openslides-backend#1429

@MSoeb could you check if you have anything to add to that issue?

**Comment by MSoeb** [comment]
@luisa-beerboom Yes, the Issues describes the problem well.

**Comment by MSoeb** [comment]
Except of the the linked backend issue, the first two checkboxes should be fixed.
