### ISSUE TITLE
csv user import: typo bug in gray hint text

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1418]
The gray hint text, which is active by hovering over the reference arrow symbol, has a typo error. A space is missing. 

Reproduction:

1. open meeting
2. open participants menu
3. open three-dot-menu and choose import
4. download the example file
5. edit the file and add an user from the account list. save file.
6. upload this file and hover over the icon. 

![Screenshot_20220720_143839](https://user-images.githubusercontent.com/105491030/179983870-dfc0c066-2184-4e77-8b16-ade47711b6ac.png)

**Comment by emanuelschuetze** [comment]
typo in translation already fixed in current 4.0-rc version.
