### ISSUE TITLE
file upload menu freezes ( CPU load rises)

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1427]
If you open the file upload menu and leave the tab open without doing anything, the CPU load increases rapidly in a short time. This causes the tab or, in the worst case, the browser to slow down or freeze.

In meetings with a lower amount of uploaded files it tooks a bit longer to trigger the problem. In https://testintern.openslides.com/2/mediafiles it could be triggered quite fast.

Reproduction:
1. open meeting
2. open in navigation bar FILES
3. click on the plus icon to upload a file
4. stay on the page until it freezes.

**Comment by emanuelschuetze** [comment]
Done with #1430
