### ISSUE TITLE
User creation menu in meeting freezes (CPU load rises)

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1428]
When creating a new user in a meeting, the CPU load in step 3 increases rapidly after a short time and the CPU fan spins up. This causes the tab to hang or freeze. As a result, the input mask can no longer be used.

Reproduction:
1. open meeting
2. open participants in navigation menu
3. click on the plus symbol and create a new participant
4. step 1: create new user (fill in name, first name and mail) and click on continue
5. jump to step 3: stay in this input mask for a short time and check CPU load. 

Waht should happen: CPU stays at normal level and tab didn't freeze.

**Comment by emanuelschuetze** [comment]
Done with #1430
