### ISSUE TITLE
Permission revocation of navigation menu items requires forced reload or opening of another menu point to be active for users on their device

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1439]
If a user's permission to see a menu item is revoked, but the user has opened the menu, the content of the menu will still be displayed in the user's browser. Only the menu item disappears from the navigation bar. Only when the user changes the menu or reloads the page he has no further access.

Reproduction: 
1. Two Accounts are needed; Superadmin und normal user account. Normal should be group staff. 
1. open meeting with both accounts in different browsers
2. navigate with the normal user account to the participant menu
3. open as superadmin the participant menu. open the three-dot-menu and choose groups. revoke permission for group staff to see other participants
4. check the normal user view. menu is gone, but the user still sees the content.

What should happen: When the permission to see a menu item is revoked, there should be an automatic redirection to the first available menu item. Example: If available, then redirect to home page, otherwise redirect to next available menu item.

**Comment by jsangmeister** [comment]
Goes in the same direction as #1421: I don't think this is important, since it's just visual and for a short moment. I don't think this situation happens often (if ever) in reality, since the permissions are not changed on the fly, and the amount of work required for this exceeds the benefit.

**Comment by luisa-beerboom** [comment]
> Goes in the same direction as #1421: I don't think this is important, since it's just visual and for a short moment. I don't think this situation happens often (if ever) in reality, since the permissions are not changed on the fly, and the amount of work required for this exceeds the benefit.

I agree that this would be a bit of work, but I don't actually think it would be so much that it would exceed the benefits.
This would likely require a new service that watches the current permissions and checks if the user is still allowed on his current page whenever there is an update. Some of the checking and re-navigating logic could then be handeled by the auth-check.service and the reroute.service (I believe that these two do, in fact already contain large parts of the required logic, so the new service wouldn't have to be that big (we may also just skip the creation of a new service and just handle it all in the auth-check now that I think about it)).

**Comment by luisa-beerboom** [comment]
#1553 adds a permissionObservable that always delivers the current permissions. This could be used to implement this functionality. 

It would also be a good idea to take a look at the various permission directives, I don't know if they currently update automatically

**Comment by jsangmeister** [comment]
If it's not much work, we could move this into the 4.0 milestone and tackle this soon.
