### ISSUE TITLE
Different problems with projector

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1446]
- [ ] editing chyron colors should be possible
- [ ] changing colors in Standardprojektor should not affect other projectors
- [ ] color reset button didn't work (could be ignored. isn't a problem)
- [ ] by clicking on apply and then save, the change menu did't close

**Details to color editing problem:**
Currently it is not possible to adjust the color values of Chyron font color and Chyron background color in the projector settings of a new created projector. The color selection menu works, but pressing the buttons Save and Apply has no effect. 
Apply button: Color change is saved by pressing the button in the menu, but not applied to the projector. 
Save button: Color change is neither saved in the menu nor applied to the projector.
When pressing the buttons an error message appears with the content: Uncaught (in promise): TypeError: e.includes is not a function

** Details Standardprojektor issue:**
Changes made in Standardprojektor affect other new created projectors. The color changes apllied to chyron in the Standardprojektor are copied to a new projector. If the user does changes in the Standardprojektor, the changes get activ in new generated projectors. Hint: The mentioned error appears also in the Standardprojektor, but the colors can be changed in it.

**Details: Color reset**
Changes to colors values couldn't be undone. The reset button does nothing. (Edit 28.7.: Isn't an issue. It has the same functionality like in OS3)

**What should happen:** 
- The colors of the chyron could be edited and saved. 
- Changes to this colors in Standardprojektor should not affect other projects. 
- color reset should be possible
- clicking save button should close menu

**Reproduction first problem:** 
1. open a meeting
2. go to projectors
3. create via plus icon a new projector
4. open this projector, the console and the chyron bar with an actice speaker
5. edit Chyron font color and try to save or a apply it. (repeat with chyron background color)

**Second problem:**
1. open a meeting
2. go to projectors
3. create via plus icon a new projector
4. project in standardprojektor and new projector the chyron bar with an actice speaker
5. edit the bar in the standardprojektor and see what happens in other projector.

third issue
1. open a meeting
2. go to projectors
3. open standardprojektor
4. open edit menu
5. change the colors of several values. apply it. try the reset button

fourth issue
1. open a meeting
2. go to projectors
3. open standardprojektor
4. open edit menu
5. change a value
6. clock on apply and than save.

**Comment by bastianjoel** [comment]
I am not able to reproduce the third issue. Works for me in Firefox and Chromium with the latest version from main.

**Comment by MSoeb** [comment]
Thx for notice. Third issue could be ignored. It works the same way like in OS3. I thought the undo button should switch the color back to default value.
