### ISSUE TITLE
chronicle mode exit button don't work

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1470]
Problem description:
When in chronicle mode, the "Exit" button does not work. To exit the mode, the web page must be reloaded.  

Reproduction:
1. log in a meeting as admin/superadmin.
2. Open the Chronicle menu.
3. Select a motion from the drop-down menu in the upper left corner and activate the chronicle mode by clicking on one of the lines that appear. A yellow-black warning appears at the top of the screen that you are in Chronicle mode.
4. Click on the "Exit" button.

What should happen:
Pressing the "Exit" button should end the Chronicle mode. 

Note: Found the error only on testintern.openslides.com.

**Comment by luisa-beerboom** [comment]
Do you mean the "Exit" button on the chronicle mode banner? Because it works for me...

**Comment by MSoeb** [comment]
issue will be closed, because error could not be found on other instances. could be reopened, if it is reported again.
