### ISSUE TITLE
Delegation of voting rights cannot be undone

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1481]
If the voting right has been transferred from one user to another, this cannot be reversed. An error message appears when deleting the voting right transfer. 

Error message: _Error: data.vote_delegated_$_to_id.5 must be greater than or equal to 1_

Reproduction: 
1. open meeting
2. open participants menu
3. create two users (A / B)
4. open detail view of user A and click pen for editing.
5. click on _Voting right delegated to (proxy) input mask_, select user B and click on _Save_.
6. open participant menu
7. open detailed view of user B and click pen for editing
8. Click on _Voting right received from (principals)_ and click on _-_ to deselect, click on _Save_. 
9. Error message appears.

Note: The problem also occurs when the voting right delegation is changed in the Participants menu in the column with the user's metadata (groups, participant number, etc.).

**Comment by luisa-beerboom** [comment]
Is this an older Version of the client? You seem to be selecting a noneItem, that - to my knowledge - shouldn't even be in that selector...

**Comment by luisa-beerboom** [comment]
> Is this an older Version of the client? You seem to be selecting a noneItem, that - to my knowledge - shouldn't even be in that selector...

I correct myself: This isn't a problem with an older Version, the replication description is wrong.

It should be:
...
7. open detailed view of user A and click pen for editing
8. Click on _Voting right delegated to (proxy)_ and click on _-_ to deselect, click on _Save_. 
9. Error message appears.

**Comment by luisa-beerboom** [comment]
Also this is probably a client-side problem
