### ISSUE TITLE
Create delegation of vote setting and rework vote delegation handling accordingly

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1512]
From #848 

-------------------------------------------------------------------------------------------------------------------------------------------------
 **Add new setting** "Activate Delegation of vote" under "Participants", below "Activate vote weight"

 If active, then under Participants .../users/...

 - [x] Filter "Delegation of vote" is visible
 - [x] In the **big edit view** of a user the dropdown menu
     - [x] "Voting right received from (principals)" is visible
     - [x] "Voting right delegated to (proxy)" is visible
 - [x] in the **quick edit dialog** of a user the dropdown menu
     - [x] "Voting right received from (principals)" is visible
     - [x] "Voting right delegated to (proxy)" is visible

 If disabled, then the previously mentioned items are not visible.

-------------------------------------------------------------------------------------------------------------------------------------------------

This is going to require not only a new settings field in the backend, it is also going to require that we find all the places where we calculate vote delegations (in the client and probably also the backend) and ensure that existing delegations will be completely ignored if this setting field is set to true.

i.e. what should work: 
1. User A delegates to user B.
2. 3 polls are opened (poll 1 and poll 2 and poll 3)
3. User B votes for user A in poll 1
4. Admin sets vote delegations to disabled
5. Now A can vote for himself in poll 2 and 3, while poll 1 shows that he has already voted, B cannot vote for A anymore
6. A votes for himself in poll 2 => He **doesn't** get a backend error that he isn't allowed to vote, because it has been delegated (!) and the vote is counted
7. Admin sets vote delegations back to true
8. B can vote for A again, but only for vote 3 because the others are already sent. A can't vote anymore

Implementing it in the client is one thing, I don't know how hard it's going to be in the backend. What do you think @jsangmeister ?

**Comment by jsangmeister** [comment]
Backend should be not much work, most of it will have to be done in the vote service by @ostcar. But I don't think simply ignoring the relation will be all too much work.

**Comment by ostcar** [comment]
This should be easy for the vote service.

This is the code that checks, if a user is allowed to vote for someone else:

https://github.com/OpenSlides/openslides-vote-service/blob/0aa7deae96812b7f21911dde116d4e4ead1a9d73/internal/vote/vote.go#L217-L232

If I understand you correctly, I just have to add another condition, that if the setting is set to false, then no one is allowed to vote for someone else.

When a poll is started, this function loads all required data from the datastore into the local cache, so the votes are faster (at least for a single instance): https://github.com/OpenSlides/openslides-vote-service/blob/0aa7deae96812b7f21911dde116d4e4ead1a9d73/internal/vote/vote.go#L448

If vote delegation is deactivated, then it is not necessary (but also not a problem) to preload the delegation data.

**Comment by luisa-beerboom** [comment]
Alright, I'll create the corresponding issues for the backend and the vote-service then

**Comment by luisa-beerboom** [comment]
OpenSlides/openslides-backend#1483

**Comment by ostcar** [comment]
Done in the vote service: https://github.com/OpenSlides/openslides-vote-service/pull/149
