### ISSUE TITLE
Function "Invite to conference room" didn't work

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1525]
Problem description:
When a user who is on the list of speakers is invited to the conference room by using the "Invite to conference room" function, nothing happens. Neither the admin nor the user sees anything in the browser. Only the console gives an error message to the admin when the button is clicked. 

Reproduction:
1. Setup Jitsi for a meeting:
1.1 Open committees on organisation-level and choose a committee
1.2 choose a meeting, click on the three-dot-menu, select edit
1.3. go to superadmin setting and fill out the lines jitsi domain and jitsi room name (if you need data, please ask @m-schieder ). save everything.
2. now open the meeting
3. open settings: check if "Show live conference window" is activated. If not, do so.
4. open participants: create a new user, add it to a group staff.
5. go to motions: create a motion
6. open the motion menu. click on the camera in front of the created motion and select project. Now the motion with a list of speakers appears in the autopilot.
7. open the Autopilot and add the user to the list of speakers.
8. open an incognito tab, open the instance page and log in as the created user. open console there.
9. head back to the admin instance page: open console. 
10. open the autopilot. click on the three-dot-menu in the user line and choose "Invite the conference room". Nothing happens.
11. Error message appears in console. 400 error
12. check the icognito tab double check if an action happens

Error message: 
![Screenshot_20220824_160143](https://user-images.githubusercontent.com/105491030/186438565-e0f65f1f-d636-424b-814f-36707e3f8768.png)

What should happen:
From my point of view, it is not clear, what should happen. I can assume three options:
1. User gets forced to join the room and it opens automatically in the client browser. May be, this is to harsh.
2. A request box appears which ask the user to join the room. So the user could decide what to do. I would prefer this option. 
3. The function is obsolte can be deleted. 

@emanuelschuetze What should be from your point of view the correct way to handle this?

**Comment by luisa-beerboom** [comment]
Can you show the exact error message, or add a picture?

**Comment by MSoeb** [comment]
> Can you show the exact error message, or add a picture?

Ah yes, forgot it. Added it to post.

**Comment by MSoeb** [comment]
some more infomation about the error:

![Screenshot_20220825_090853](https://user-images.githubusercontent.com/105491030/186598597-732e4c94-0e77-4cd4-805f-1f978b9ece47.png)

![Screenshot_20220825_090622](https://user-images.githubusercontent.com/105491030/186598355-b112340b-646e-4ebb-ae81-759439f9d28a.png)

![Screenshot_20220825_090633](https://user-images.githubusercontent.com/105491030/186598387-a906e763-9627-4541-a277-36e2019c492b.png)

**Comment by luisa-beerboom** [comment]
I tried doing exactly what you described in my instance and it worked perfectly, are you doing something else as well?
It's quite clear that your client is sending an empty channel id to the ICC service when inviting the other guy, but it just works if I do it.

After taking a look at the code, I can only assume that maybe your ICC-service didn't send you a channel-id-response after the connection was built.
Please check if you got a message along the lines of 
`onMessage > Object { channel_id: "<seemingly random assortment of letters>" }`
in your console, if you want to be sure about that.

**Comment by m-schieder** [comment]
I can reproduce the error on various productive instances. In my dev environment it also works without problems.

**Comment by emanuelschuetze** [comment]
Reproduced on current main brain
* if admin click "invite to conference room" the user gets correct icc message "invitationToCall" with channelID
* user gets dialog "Please join the conference room now!" -> click "Ok" button
=>  2 type errors: 
``` 
TypeError: Cannot read properties of undefined (reading 'type')
    at broadcast.service.ts:41:62
[...]
TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at RtcService.setOptions (rtc.service.ts:384:40)
```

**Comment by jsangmeister** [comment]
I don't get these errors, instead I get the following:
```
[features/base/jitsi-local-storage] Can't parse localStorageContent. TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at setup.web.js:80:24
[...]
[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Cannot read properties of undefined (reading '_navigate') Script: null Line: null Column: null StackTrace:  TypeError: Cannot read properties of undefined (reading '_navigate')
    at https://webconf.openslides.com/libs/app.bundle.min.js?v=5818:138:737693
[...]
TypeError: Cannot read properties of undefined (reading '_navigate')
    at middleware.js:154:48
[...]
[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Cannot destructure property 'id' of '$p(...)' as it is undefined. Script: null Line: null Column: null StackTrace:  TypeError: Cannot destructure property 'id' of '$p(...)' as it is undefined.
    at Object.changeLocalDisplayName (https://webconf.openslides.com/libs/app.bundle.min.js?v=5818:138:558897)
[...]
TypeError: Cannot destructure property 'id' of '$p(...)' as it is undefined.
    at Object.changeLocalDisplayName (conference.js:3086:17)
```
The jitsi URL is `webconf.openslides.com`, the room name is `test` and the password is empty, I'm not sure if this has anything to do with it. But connecting normally via the phone button works without problems.

I'm stumped as all these errors stem from inside the jitsi code. @m-schieder maybe you can take a look at this? Also, @peb-adr, didn't this just work in our test together?

**Comment by jsangmeister** [comment]
@m-schieder This looks similar to the error I am getting: https://github.com/OpenSlides/OpenSlides/issues/6402. Maybe this helps?

**Comment by peb-adr** [comment]
> I'm stumped as all these errors stem from inside the jitsi code. @m-schieder maybe you can take a look at this? Also, @peb-adr, didn't this just work in our test together?

Yes indeed we did test the invite-function successfully (also on production images).
However with the applause-errors too - that we couldn't observe during that test - I'm starting to worry, that somehow the browser session wasn't clean enough again or something along those lines ..

**Comment by m-schieder** [comment]
There is still a bug to fix:

- use a private tab and log in as delegate user
- add delgate user to current list of speakers
- as admin: invite user to jitsi
- delgate user gets dialog -> user has to click 2(!) time on OK button

Looks like two dialogs are created to enter the conference.
The first dialog is broken. When the first dialog is closed, the second one appears. This one works.
I can't recreate the error sometimes and I will investigate the behavior later.

(This error description comes from [PR1573](https://github.com/OpenSlides/openslides-client/pull/1573)
