### ISSUE TITLE
The Remove function, in the speech list, does not kick the user out of Jitsi

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1534]
Problem: A user that has joined the conference room, can't be kicked out by using the REMOVE function. The function worked only partially correct and removes the user from the list of speaker. 

Reproduction:
0. Setup Jitsi for a meeting:
0.1 Open committees on organisation-level and choose a committee
0.2 create/choose a meeting, click on the three-dot-menu, select edit
0.3. go to superadmin setting and fill out the lines jitsi domain and jitsi room name (if you need data, please ask @m-schieder ). save everything. 
0.4. open the meeting
0.5 open settings: check if "Show live conference window" is activated. If not, do so.
1. open the meeting in another browser and log in as a delegate. (If needed, create a new user in meeting as a delegate.)
2. as Admin:
2.1 go to agenda.
2.2 create an agenda point via plus-icon. fill out form. click save. 
2.3 click on camera icon in the new created agenda line
2.4 click on Project.
2.5 open autopilot
2.6 join conference via conference button
3. as delegate
3.1 go to autopilot
3.2 add yourself to list of speakers
3.3 join the conference room via conference button
4. as Admin: After the user has joined the conference, try to kick him by clicking on the thee-dot-menu in the user row and choose remove. 

 What should happen:
By clicking the REMOVE button, the user should be kicked out of the conference room and the list of speakers, like in OS3.

**Comment by jsangmeister** [comment]
Probably related to https://github.com/OpenSlides/openslides-client/issues/1525 with the case that the ICC service does not seem to work in the productive setup.
