### ISSUE TITLE
Account list sorting and filtering changes

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1558]
Add the following filters:

- [x] Natural person
- [x] E-mail
- [x] Gender
- [x] Committee management
- [x] OML-Permissions

Add the following sorting options:

- [x] Sequential number
- [x] Number of Meetings
- [x] Date of last sent email

**Comment by emanuelschuetze** [comment]
new filter successfully tested. Not tested: new sort options -> wait for #1559
