### ISSUE TITLE
Mediafiles: Files are notdisplayed

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#1568]
`…/…/mediafiles`

### Problem:
If you click on a file (under `Files` or on the link of an attachment under `Agenda` `Motions` or `Assignments`) the file/URL to the file is opened in a new tab. So far, so good.

But the file is not displayed. The URL `…/system/media/get/…` is not followed, but there is a redirect to the organization level ("Calendar").

### Desired behavior:
When the link of a file is clicked, then the file is opened/displayed properly (as it was until a few days ago) in a new tab.

**Comment by emanuelschuetze** [comment]
can reproduced in production mode only! (in dev mode it works as expected)

**Comment by emanuelschuetze** [comment]
@jsangmeister maybe this is a ngsw problem? please have a look.
