### ISSUE TITLE
Motion poll: Chart is black in autopilot

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1615]
* Open autopilot in a second window
* project the motion
* start/vote/stop and publish a motion poll (yes/no/abstain)

In some cases the piechartin the autopilot is completly black instead of the colors of yes/no/abstain. A reload is necessary to get the correct colors.
This one is hard to reproduce since the (pre-)conditions are not completely clear. Maybe a look in the code can help.

**Comment by rrenkert** [comment]
Update chart.js and take a look at the changelog.

**Comment by bastianjoel** [comment]
I think this got fixed now by the change to https://github.com/bastianjoel/openslides-client/blob/a3f6180352d81cd5123a3fcbdddc5d43ee0e450d/client/src/app/site/pages/meetings/modules/poll/components/chart/chart.component.ts#L160 in #1710 which fixes a bug where colors added to a chart after the chart was already initialized were not added to the chart. This resulted in repeated use of colors or a black chart if no colors were added.
