### ISSUE TITLE
Motion forwarding: UI improvements

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1624]
- [x] The button "forward" for motions should be availbale in the menu
- [x] The existing forward button should be hidden if the the motion is (already) forwarded
- [x] Move forwarding infos below motion state

**Comment by jsangmeister** [comment]
> The existing forward button should be hidden if the the motion is (already) forwarded

Is the intention that motions can only be forwarded once? If so (and assuming that is a general rule), we should also implement such a check in the backend and forbid forwarded motions from being forwarded again.
