### ISSUE TITLE
Show associated committees, meeting and groups for accounts

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1625]
Extend the account details by a table showing the committee, meetings and groups of the user for admins.

**Comment by luisa-beerboom** [comment]
@rrenkert among the orga admin roles, the group names won't be visible to account managers, everyone else should be able to see everything else.

It may be possible to just leave out the group column for account managers.
It would also be possible to show the number of groups a user is part of within that meeting.
