### ISSUE TITLE
autoupdate worker improve duplicate detection

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#1663]
The check if a autoupdate subscription can be fulfilled by another autoupdate subscription is currently just checking if the url and request body are the exact same:
https://github.com/OpenSlides/openslides-client/blob/5a4a4dbff2499aa57fc5c6db4a6167a87395ac53/client/src/app/worker/autoupdate-subscription.ts#L147-L155

It might be possible to improve this.

**Comment by jsangmeister** [comment]
@bastianjoel is this done?

**Comment by bastianjoel** [comment]
Yes
