### ISSUE TITLE
Line numbers are not correctly displayed if a chart is used in a motion

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1711]
**Description:** If a motion text contains a table, the line numbering is displayed incorrectly. 

![Screenshot_20221019_114858](https://user-images.githubusercontent.com/105491030/196658142-68965c88-4ac4-473a-9d68-94ea2e40a706.png)

**Reproduction:**
1. open meeting
2. open motions menu
3. create new motion with plus icon
4. click on source text icon in text input mask
5. insert table in source code (see sample table code below for transfer). Click on Save.
6. Fill in other necessary fields for motion creation and click on Save.

**Expected behavior:**
Line numbering will be correctly displayed when using a table, as far as it is technically possible. I'm not sure if there is a technical solution for the problem, but I wanted to include it as a bug for completeness.

**Table code:** 
Example code on website https://wiki.selfhtml.org/wiki/HTML/Tabellen/Aufbau_einer_Tabelle

**Comment by bastianjoel** [comment]
Tables are currently not considered by the motion diff and line numbering services and therefore not supported.

**Comment by emanuelschuetze** [comment]
won't fix - no table support for motion line numbering in OS4!
