### ISSUE TITLE
Extend motion workflow to allow motion submitter to set the status "withdrawn"

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#1734]
Add new attribute per state in motion workflow: "Motion submitter may set state to..."
This attribute can take exactly one state. This should be the state "withdrawn".
This allows the submitter to revoke its own amendments/motions.

To save this state additional work in the backend is needed.

**Comment by luisa-beerboom** [comment]
There are now new fields in the backend `submitter_withdraw_state_id` and `submitter_withdraw_back_ids`

**Comment by emanuelschuetze** [comment]
needs https://github.com/OpenSlides/openslides-autoupdate-service/pull/573
