### ISSUE TITLE
Error history mode: exit not possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1738]
**Description:** The history could currently not be stopped. Clicking the "Beenden"-button has no impact. Also several error appear in the console. 

![Screenshot_20221025_095822](https://user-images.githubusercontent.com/105491030/197717077-8bac1937-85b1-4d7d-953b-b2bbd4072b9b.png)

![Screenshot_20221025_095851](https://user-images.githubusercontent.com/105491030/197717092-0e96ada2-480d-4f92-a459-1c470710982d.png)

**Reproduction:**
1. open a meeting with motions as admin (if no motions available, create at least one)
2. open the console
3. open history and choose a motion. open history mode for one of the timestamps. after this a yellow/black graphic should appear on the top of the browser
4. now click on EXIT to exit the history mode

--> in console several errors appear and the user can't exit the history mode.

Hint: Bug is connected to Issue 1708

**Expected behavior:** User should exit history mode and error should not appear.

**Comment by bastianjoel** [comment]
I can't reproduce this with current main.

**Comment by luisa-beerboom** [comment]
> I can't reproduce this with current main.

Same
