### ISSUE TITLE
adding motions to motion blocks only visible after page reload.

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1739]
**Description:** If a user adds motions to a motion block, not all motions are visible until the user reloads the instance. Seems a like a missing autoupdate bug. 

![Screenshot_20221025_102055](https://user-images.githubusercontent.com/105491030/197721942-f79e86de-7a8d-402a-8488-5177f5ec55b3.png)

**Reproduction:**
1. open meeting as admin
2. open motions
3. create at least 5 motions via plus-icon
4. open the three-dot-menu and choose motions blocks
5. create a motion block via plus-icon
6. head back to motions menu
7. open three-dot-menu and choose multi select. choose at least 5 motions. click again on the three-dot-menu and choose set motion block. add the motions to the created motion block.
8. leave mutli selection mode. open the three-dot-menu and open motion blocks 
9. open the created block. 
10. --> Not all motions are included. On the top left, the number listing displays all added motions, but they are not visible.

**Expected behavior:** After adding a motion to a motion block, it should be visible without a forced reload of the page.

**Comment by luisa-beerboom** [comment]
Can't replicate, is there something different about this instance?

**Comment by MSoeb** [comment]
I'v tested it on testintern in meeting 2.  May be this helps to reproduce it.

**Comment by emanuelschuetze** [comment]
I can confirm it on testintern meeting 2 (only by using multi select). Other meetings and instances works.

**Comment by emanuelschuetze** [comment]
reason: datastore is corrupt and meeting2 has wrong relations. no general problem with motion block feature.
