### ISSUE TITLE
navigation between motions without number needs visual improvement

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1748]
**Description:** The navigation between motions without a number is quite hard, because it's hard to recognize the small arrows if the color contrast between the arrow and the background is not optimal. This occurs for example if the background color is red and the arrows are white. Without a number the arrows are hardly visible. Even more this is a problme for color blind or color disabled persons. This should be improved.

![Screenshot_20221025_171327](https://user-images.githubusercontent.com/105491030/197812821-b19655f7-f520-420b-beec-f429ed0a5a0f.png)

**Possible solution:** A circle around the arrow could solve this. The circle could be white and the arrow is in the color of the background. So it's more like a button which could easily distinguished from the background and it will work even without numbers or text. Just like the plus-icon right to the arrows.

**Comment by emanuelschuetze** [comment]
won't fix - works good enough in current 4.0 rc
