### ISSUE TITLE
Feature: add global settings for fonts and logos / logo on orga-level could be changed

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1752]
**Currnet situation:** 
Currently it is not possible to change the logo on the Organization-level. Also it is not possible to set a logo and fonts for all meetings as a default value.

**Expected behavior:** 
- [ ] The logo on the organization level could be changed 
- [ ] it is possible to set a logo and fonts as default values for all meetings. 

**Reason:** 
The reason for this feature request is, that most organizations have a corporate design which is organization wide and used on every level. With this feature an organization admin could set logos and fonts as defaults values for all meetings according to the CD.

**How it could be implemented:**
1. File menu is needed on organization level. (This is done by one of the next updates)
2. create different checkboxes in three-dot-menu behind uploaded files. same like the ones in meeting, only with different content.
Checkboxes for images:
- [ ] organization level logo
- [ ] set logo as global default 

Checkboxes for fonts:
- [ ] use font as global for .... (here we need several options like the ones in a meeting; like bold etc.)

3. After the files are set global, they are copied in a new meeting. This is necessary to change them on meeting level and switch back. 

**Important:** 
Most importan is the possibility to change the logo on organization level. The global setting would be a nice quality of live improvement for large organizations.

**Comment by luisa-beerboom** [comment]
This can probably be done by using the token functionality in orga-files without requiring any new backend functionality:

The client could use tokens like `global-default-font`, `orga-font`, `global-default-logo` and `orga-logo` to denote these files.
This would make them accessible to anyone, even those that are not logged in. (Which means that we could even use it on the login pages)
