### ISSUE TITLE
filter notification still active in filter-menu after deselection

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1769]
**Description:** After deleting a filter with the X-Button, the filter notification (number icon in filter-menu) still appear. By deselecting  the filter again, it gets active without a mark in the checkbox. It seems like an UI bug in the filter menu. 

This problem affects all filter-options.

The filter was disabled with the X-Button. Notification still appears. 
![Screenshot_20221102_132933](https://user-images.githubusercontent.com/105491030/199489853-36c0a3bb-56cb-4e60-a85b-11030a0d2096.png)

**Reproduction:**
1. open on organization level the account list
2. choose a filter
3. disable the filter with the X-button
4. open the filter-menu (notification of active filter is still visible)
5. tryp to disable the filter option. -> the filter gets active again

**Expected behavior:** If a filter user disables the filter with the X-Button the filter-menu should not display it as active anymore.

**Comment by rrenkert** [comment]
Additionally the filterboxes (see picture above "Status") are collapsed if an autoupdate happens in the list view.

**Comment by bastianjoel** [comment]
Filterboxes are still collapsing.
