### ISSUE TITLE
analog elections: majority can be selected for all results at the same time

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1774]
**Description:** If a user wants to add an analog election, it is possible to select a majority for all result options at the same time. This is simply wrong. 

**Reproduction:**
1. open a meeting
2. open elections
3. create a new election via three-dot-menu
4. add two or more users as candidates
5. create new ballot by clickling the new ballot-button
6. choose as voting type "analog". try to select the majorities. 
7. choose as voting method for example "Yes per candidat"
8. Select majorites: All could be selected and saved at once. 

**Expected behavior:** In comparison to an analog voting, ballots are a bit more complex. A majority for one candidat didn't result in blocking of the other candidates. For example: In list elections it is possible to have more than one candidat with a majority. Therefor the multiple selection options for candidates is correct.

Incorrect is to be able to select also valid votes, invalid votes or total votes cast as a majority. These options should not be selectable. This should be changed.

**Comment by luisa-beerboom** [comment]
@emanuelschuetze @MSoeb this will probably be a bit complex and it isn't completely clear what exactly should happen. Could you give a more detailed description as to how exactly we should change the way the form works?

**Comment by MSoeb** [comment]
The crucial point is, that it is currently possible to select _valid votes_, _invalid votes_ or _total votes cast_ as a majority. This should not be possible, because majorities in this context are only relevant for candidates not statistic values.
