### ISSUE TITLE
permission error as meeting admin: delete user from meeting not possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1775]
**Description:** As a meeting admin it is not possible to delete a user from the meeting. An error message appears on website and console.

![Screenshot_20221107_115414](https://user-images.githubusercontent.com/105491030/200293292-9b1a0841-490a-4b7f-b478-18a7b2637235.png)

![Screenshot_20221107_115433](https://user-images.githubusercontent.com/105491030/200293307-0e175e1b-740d-4455-9fda-593821fa0630.png)

**Reproduction:** 
1. create a meeting as superadmin
2. open participants
3. create a user and choose as group "admin". the user is now a meeting admin.
4. create another user. select group delegates.
5. open another browser, open the meeting and log in as the meeting admin
6. open participants
7. try to delete the other user. -> error

**Expected behavior:** The meeting admin should be able to delete a user from a meeting.

**Comment by luisa-beerboom** [comment]
Have only taken a short look at the code so far, but this makes it seem like the backend's `get_user_scope` presenter is checking for the OML.can_manage_users permission when, according to the wiki, it shouldn't be checking for anything.

What do you think @r-peschke ?

**Comment by jsangmeister** [comment]
As far as I see it, the presenter is not checking any permission in the backend and the error in the console also doesn't look like that's the case.

**Comment by luisa-beerboom** [comment]
Well, since evidently something is something going wrong with a presenter, and I couldn't find any other presenter being used while deleting from a meeting, I expected `get_user_scope` to be the cause of the problem, but it could of course be that these two errors are unrelated.

**Comment by r-peschke** [comment]
@luisa-beerboom, @jsangmeister:  The presenter `get_user_scope` only returns user scope, see [wiki](https://github.com/OpenSlides/OpenSlides/wiki/get_user_scope). The significance of the user_scope is documented [here](https://github.com/OpenSlides/OpenSlides/wiki/Users#user-scopes). Besides the user scope on this page you'll find more information on user rights and actions.

If you think the format of the presenter is wrong, we should look at it.
The permission error is a result of the action, the client uses. Which action do you use to remove the user from a meeting?

**Comment by luisa-beerboom** [comment]
@r-peschke Seems like it's user.delete for those users that don't have another meeting and user.update for those that do.
I wonder if maybe the presenter error (however it may have come to be) is causing the classification to go wrong and if it may cause the client to attempt to delete or update users that they have no business editing in that way

**Comment by r-peschke** [comment]
@luisa-beerboom: Yes, that's my idea, too. Can you reproduce the presenter problem?

But:
If the user is neither in a meeting nor in a committee, the user scope is Organisation/1. This results in necessary permission OML.can_manage_user to delete the user.

**Comment by luisa-beerboom** [comment]
Okay update: I tried it out and have confirmed what actually happens
The error isn't thrown in the deletion method itself, but in the `UserDeleteDialogService`, which uses the `get_user_related_models`-presenter. That one is throwing the `Missing OrganizationManagementLevel: can_manage_users`-Error

So what is happening is: 
A meeting admin sends a `get_user_related_models` presenter request for a user who is 
1. Guaranteed to be in this meeting and no others
2. Guaranteed to have done nothing yet
and he gets the message that he doesn't have the `OML.can_manage_users` and is therefore not allowed, when, realistically he should have the required meeting permission.

Can you take a look at this @r-peschke ?

**Comment by r-peschke** [comment]
@luisa-beerboom See https://github.com/OpenSlides/OpenSlides/wiki/get_user_related_models#permissions. The user needs the permission of the committee CML.CAN_MANAGE for each committee or the OML.CAN_MANAGE_USERS.

**Comment by luisa-beerboom** [comment]
@r-peschke 

From the wiki:
> The requesting user needs at least permissions to manage users. 
> This can be OML.can_manage_users.
> If the user has not the permission OML.can_manage_users, 
>    it is checked for every meeting (they are included), if the user has the permisssion user.can_manage in the meeting 
>    and for every committee, if the user has the permission CommitteeManagementLevel.CAN_MANAGE for every committee.

This says something about the meeting-permission `user.can_manage` too. The meeting admin certainly has that, why is this happening?
