### ISSUE TITLE
Mediafile bugs

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1776]
Two bugs in the meeting mediafile lists:

- [x] Using a logo that is placed in a restricted directory will make the logo visible in the base directory for users that don't have access to the restricted directory (It should be loaded, but filtered out of the list)
- [x] In a mediafile list with a restricted mediafile: View the list with an account that can see the mediafile, then log out and log back in with an account that shouldn't be able to see it WITHOUT reloading: The restricted mediafile will show up in the list

**Comment by bastianjoel** [comment]
It seems like it is not possible to determine if a logo file should be shown in the main directory listing or not. The `parent_id` is not included if the user does not have permissions to view that directory.

**Comment by jsangmeister** [comment]
By checking the `inherited_access_group_ids` and comparing it with the user's groups, you can check if the user can see the file (`inherited_access_group_ids` also take into account the restriction on the parent folder). If the user cannot see the file, you don't have to display it at all, if he has, you should also be able to see the `parent_id`, if any.

But AFAIK, this process should already be done by the restricter, so the mediafile should not even be delivered to the client if the user has no permission to see it (analogous to all other models which the user cannot see). @ostcar do you know whether the AU service does this kind of restriction? If not, we should implement it there.

**Comment by luisa-beerboom** [comment]
@jsangmeister @ostcar  This is something that specifically happens to logos and fonts when they are used.
They need to be accessed by the client in order to be used (otherwise any client who doesn't have access rights won't be able to display the nice custom logo that you devised for your meeting in the upper left corner), that's why the restrictor **must** make an exception here and deliver them regardless.

The fact that it is then displayed in the mediafile list when it shouldn't be is a pure client-problem.

**Comment by jsangmeister** [comment]
Ah, okay, then I misunderstood. Then the disctinction should be possible as described above.

**Comment by ostcar** [comment]
For completion: Here is the description for the mediafile restriction: https://github.com/OpenSlides/openslides-autoupdate-service/blob/main/internal/restrict/collection/mediafile.go#L13-L27
