### ISSUE TITLE
Show ids of groups somewhere in the ui

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1777]
Users should be able to connect group names with the corresponding ids without having to press `F12` and filtering through the browser logs.

Suggestion:
Show a read-only text line in the groups-settings-page's title edit-dialog

**Comment by rrenkert** [comment]
I think the group ids should not be user visible. These are internal data that no user should care of.

**Comment by luisa-beerboom** [comment]
Method to currently get group ids per meeting using the dev tools console:

1. Visit target meeting
2. Press F12 (to open dev-tools) and in there:
    - go to tab `console`
    - enter `meeting_detail_group`
    - pick the entry that starts with "autoupdate: from stream" and unfold the last object by clicking on it
    - it will have something like this structure:

```
{
    "group/10/id": 10
    "group/10/name": "Committees"
    "group/10/permissions": [...]
    "group/10/weight": ...
    "group/9/id": 9
    [...]
    "meeting/2/admin_group_id": 7
    "meeting/2/default_group_id": 6
    "meeting/2/group_ids": [ 6, 7, 8, 9, 10]
    "meeting/2/id": 2
}
```

You can read all of the meetings group ids from there:
> "meeting/2/group_ids": [ 6, 7, 8, 9, 10]
=> meeting 2 contains the ids 6, 7, 8, 9, and 10

> "group/10/name": "Committees"
=> the group with the id 10 has the title "Committees"

If from there one wants to check another meeting, one simply needs to click on the dev-tool-consoles clear button (i.e. the dust bin icon) and switch to the desired meeting

**Comment by luisa-beerboom** [comment]
Given that this method currently exists we'll have to see whether it's even necessary to actually print the ids in the ui

**Comment by emanuelschuetze** [comment]
This issue is no longer required. It is solved in external software by fetching all groups with their ids.
