### ISSUE TITLE
Show last_login timestamp in client

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1779]
`last_login` is a user-attribute that is already implemented in the backend. 
Show it in the client for users that have the rights to see it.

It should be shown in the account-detail-view and maybe in the account list.

Maybe add according filters and sorting options

**Comment by emanuelschuetze** [comment]
add new user/account filer for last_login

**Comment by jsangmeister** [comment]
PR in auth service: https://github.com/OpenSlides/openslides-auth-service/pull/139
