### ISSUE TITLE
Poll detail: Result lists can't show deleted users

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1804]
1. Create an anonymous poll
2. Vote with a few accounts
3. Stop and publish poll
4. Delete one of the accounts who voted
5. Reload page
6. Take a look at the poll result lists => The entitled users table is broken

TODO:
- [ ] Fix entitled ussers table
- [ ] See if the votes table is also broken (i.e. when you use a different method than anonymous) and, if yes, fix it

**Comment by bastianjoel** [comment]
Works for me

**Comment by luisa-beerboom** [comment]
Seems to be fixed in current main
