### ISSUE TITLE
Make PDFs in projector view scrollable

### ISSUE THREAD

**Issue by kjkriegel** [OpenSlides/openslides-client#1850]
**Is your feature request related to a problem? Please describe.**
PDFs that are projected are not scrollable/pageable nor zoomable.

**Describe the solution you'd like**
Add an option to fit pdf pages to projector viewport and switch pages.

**Additional context**
Pressing the scroll buttons or the zoom buttons has no effect.
![Screenshot_20200129_195525](https://user-images.githubusercontent.com/24280256/73387852-74005b80-42d1-11ea-9e4f-31c46696f3bc.png)

**Comment by emanuelschuetze** [comment]
Reopened: Use projector zoom buttons instead special pdf zoom buttons in "mediafile" section in projector detail.
