### ISSUE TITLE
Committee-detail-view: Setting a meeting as a public template empties the views meeting list

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1892]
Reproduction:
1. Set up a committee with two meetings
2. Use the menus of the views meeting list to set the first meeting to `public template` => The other meeting will vanish from the list
3. Reload => The meeting will be in the list again.
4. Reverse what you did in step 2 => Both meetings will vanish from the list

**Comment by luisa-beerboom** [comment]
After further investigation it seems that, for some reason, the resulting autoupdate from the `meeting_list` subscription causes the meeting models to be cleared.

It looks like this:
```
modelRequest: {
        viewModelCtor: ViewOrganization,
        ids: [ORGANIZATION_ID],
        follow: [
            { idField: `active_meeting_ids`, follow: [{ idField: `group_ids` }], fieldset: `list` },
            { idField: `archived_meeting_ids`, follow: [{ idField: `group_ids` }], fieldset: `list` },
            { idField: `template_meeting_ids`, follow: [{ idField: `group_ids` }], fieldset: `list` }
        ]
    }
```

Other subscriptions that deliver the exact same payload shortly before that (i.e. the `organization_tag_list`, `committee_list` and `committee_detail` subscriptions) don't seem to cause this phenomenon.

It seems like out autoupdate handling is not working quite as perfectly as we might want it to...

**Comment by bastianjoel** [comment]
This also affects the calendar. When a user changes a meeting to template the calendar entries disappear.
