### ISSUE TITLE
investigate if the models currently provided in root really need to be

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1914]
Instead of providing everything in root, we should consider providing many services in modules. (See https://angular.io/guide/providers)
This may speed up the app startup significantly

**Comment by bastianjoel** [comment]
From the documentation I do not see that this would get us any performance gains at app startup as `providedIn: 'root'` also supports tree shaking and therefore services only get loaded if used.

**Comment by rrenkert** [comment]
@bastianjoel @luisa-beerboom Can you please have a look if we can close here?

**Comment by bastianjoel** [comment]
As of the angular docs best practice is to use provider scope `root` as a default. As mentioned above this also has no performance benefits. 

https://angular.dev/guide/ngmodules/providers#provider-scope
