### ISSUE TITLE
Navigation inside "Add to meeting" wizard broken if no choice exists

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#1919]
If you enter data which does not match any user in the wizard and click "Next", the wizard automatically skips step 2 and goes directly to step 3. If you then click "Back", it goes back to step 2 and presents an empty page. If you then click "Back" and "Next" again, the same problem occurs. The empty "Choice" page should be skipped in every direction.

**Comment by luisa-beerboom** [comment]
To avoid confusion: This issue is about the meeting-side participant creation wizard (specifically the option to reference pre-existing accounts).
It has nothing to do with the organization-side `account-add-to-meetings.component`!
