### ISSUE TITLE
By deleting a meeting, the calendar doesn't show archived meetings until refresh

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1929]
**Description:** If a user deletes a meeting in committees, the meeting overview in the calendar doesn't display archived meetings anymore until the website is refreshed. 

**Reproduction**
Needed: An instance with two committees, one meeting in each one of it and also an archived meeting in one of it.
1. Open the calendar.
2. Open the committee with the active and archived meetings in a new tab(!). Delete the active one.
3. Switch back to the tab with the calendar and check the listing. The archived one should not appear anymore. Refresh the tab and it appears again.

**Expected behavior:**
Deleting a meeting should not affect the current meeting overview. All meetings shoould stay visible.

**Comment by luisa-beerboom** [comment]
Seems like it may be connected to #1892

**Comment by emanuelschuetze** [comment]
Retested: After deleting a meeting, the calender still shows the deleted meeting -> reload required.
(works with one tab and one meeting in a committee)

**Comment by bastianjoel** [comment]
With #1908 this behaves a bit different. 
The archived meeting will stay visible but the deleted meeting will not be removed from the list anymore.
