### ISSUE TITLE
Implement client-side list election polls

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#1967]
This will require the changes in OpenSlides/openslides-backend#1608 and any eventual autoupdate changes.

****CREATION****

In the assignment-poll dialog there should be an option allowing the user to switch between normal assignment polls and **list-elections**. (Something like a checkbox maybe)
For now those should use only one list per poll.

If, upon confirmation, that checkbox is toggled, the poll creation must be changed in the following ways:

1. Send the appropriate payload for a single-option list election (i.e. fill in the new field in the option scheme, instead of content_object_id)
2. The rest proceeds as usual

****Displaying the poll****
The candidate list should be sorted according to weight, numbered and displayed above the voting area. For the sake of comfort it should be expandable (closed by default?).

When the list is closed, instead of the title we may want to display a preview of the contained entries

Everything else should (hopefully) work just fine with the current system.

**Comment by jsangmeister** [comment]
Waiting for results of discussion in https://github.com/OpenSlides/openslides-backend/issues/1608 - description will have to be adjusted afterwards

**Comment by luisa-beerboom** [comment]
Waiting for OpenSlides/openslides-autoupdate-service#619
