### ISSUE TITLE
svg files can't be used as an image file

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1978]
Description: SVG files are not recognized as images and cannot be used as a logo, for example. The full selection bar that jpg, png or gif have is not available for svg files. 

Possible options for svg files:
![Screenshot_20230127_133039](https://user-images.githubusercontent.com/105491030/215087706-1aeefef2-8244-44a4-bbd9-4c9611256454.png)

Compare: Options for a gif file
![Screenshot_20230127_133108](https://user-images.githubusercontent.com/105491030/215087781-3ff42980-9cca-4652-b752-a250822af29c.png)

Reproduction:
1. open a meeting
2. open files
3. upload a svg and after it a gif file
4. use the three-dot-emnu behind the files and check to options

What should happen:
SVG files should have the same options to choose from as jpg, png or gif files.

**Comment by bastianjoel** [comment]
This requires a backend change.
