### ISSUE TITLE
Enlargement view - Text editor behind mainmenu

### ISSUE THREAD

**Issue by Eich-hoernchen** [OpenSlides/openslides-client#1983]
After using the enlargement button in the text editor, the editor is hiding by the mainmenu.

![image](https://user-images.githubusercontent.com/60174105/215468571-6c6ede1c-ce75-48ee-b3c8-f3f0bbf2aa8f.png)

**Comment by luisa-beerboom** [comment]
Discussed with @Eich-hoernchen : Menu must be hidden if editor is in fullscreen
