### ISSUE TITLE
Two problems with pdf export ballot papers

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1998]
Description: Two problems appear with pdf ballot papers.

1. The PDF export of ballot papers didn't work, if the PDF file contains an image file. By clicking the ballot paper button, the PDF loading bar loads, but didn't produce a pdf file. It seems that the image file isn't correctly linked. 

2. Addtionally it is not possible to deselect the check box PDF BALLOT PAPER LOGO of an image file, if the image file is selected as PDF headerlogo (left) and PDF ballot paper logo. 

Image file for case 1:
![Screenshot_20230202_115423](https://user-images.githubusercontent.com/105491030/216305844-7cb117f2-54c5-4d0d-b21f-8b50121410fd.png)

Reproduction of case 1:
1. open a meeting
2. open _files_ and upload a small logo image. set this image as **PDF ballot paper logo**
3. open _elections_
4. create a new election via plus-icon
5. add one candidate and create a new ballot by clicking _New ballot_. Choose non-nominal as voting type. the other atributes doesn't matter. 
6. click the three-dot-menu in new ballot and choose Ballot papers.

Reproduction of case 2:
1. open a meeting
2. open files and upload a small logo image. set this image as PDF headerlogo (left) and PDF ballot paper logo.
3. try to deselect PDF ballot paper logo.

What should happen:
- [ ] case 1: pdf export of ballot papers with logo should be possible
- [ ] case 2: deselection should work correctly

**Comment by m-schieder** [comment]
> 2. Addtionally it is not possible to deselect the check box PDF BALLOT PAPER LOGO of an image file, if the image file is
> selected as PDF headerlogo (left) and PDF ballot paper logo.

It's a different problem that we've had before. I'll look for the old issue or create a new one.
