### ISSUE TITLE
(German) Translation problem when sending multiple emails

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2010]
The success snackbar message when multiple emails have been sent is `%num% emails were send successfully.`
The `%num%` is replaced with the corresponding number after the string has been translated, creating a new message `2 emails were send successfully`.

Problem:
The German translation for this is saved as `{0}um% E-Mails wurden erfolgreich versandt.`
This will not be recognized by the number replacement command, and therefore `{0}um% E-Mails wurden erfolgreich versandt.` will be exactly what the user sees.

Please fix this.

**Comment by luisa-beerboom** [comment]
Also:
I do believe the correct English past tense for "send" is "sent", so the original message should probably be `%num% emails were sent successfully.`

**Comment by emanuelschuetze** [comment]
Currently, there is a bug in German translation in user history:
```
  "Teilnehmer*in hinzugefügt zur Gruppe \{\} in Veranstaltung \{\} group/866 meeting/140"
  "Participant added to group group/856 in meeting Board"
```

**Comment by emanuelschuetze** [comment]
Looks like "npm run po2json" generates broken de.json file. 

Example:
de.po contains 
```
msgid "%num% emails were send sucessfully."
msgstr "%num% E-Mails wurden erfolgreich versandt."
```
After run "npm run po2json" the de.json contains the broken German string:
```
"%num% emails were send sucessfully.":"{0}um% E-Mails wurden erfolgreich versandt."
```
Same problem with wrong escaping of history information strings in de.json, e.g.
```
"Participant added to group {} in meeting {}":"Teilnehmer*in hinzugefügt zur Gruppe \\{\\} in Veranstaltung \\{\\}
```



Maybe our old po2json-tmpfix could help?
@jsangmeister What do you think?

**Comment by emanuelschuetze** [comment]
see 52d622b624b147f702dd70b106debe8fc9432fbf which could fixed our issue

**Comment by jsangmeister** [comment]
Yes, I'm aware. I'm currently rewriting the translation system to not generate json files, since this is an unecessary step - instead, we can read the .po files directly.
