### ISSUE TITLE
Font and icon size in election result view

### ISSUE THREAD

**Issue by Eich-hoernchen** [OpenSlides/openslides-client#2037]
The election result view card is a bit untidy: different font sizes and different icon sizes. In the mockup you'll see that all font sizes are the same, exept nicht-namentlich. All icons scale down to the font size. Furthermore, the card is less high. The mockup solution of the election result view card is more harmonic. 
![electioresultharmony](https://user-images.githubusercontent.com/60174105/219360193-6434ee46-396c-49b9-b000-04c244de92ca.png)

**Comment by luisa-beerboom** [comment]
Corresponding component is the `single-option-chart-table.component`.

It can be reached in two ways:
1. Make a motion poll
2. Make an assignment poll with only one candidate (or make a list election if #1967 is finished)

It is more noticeable with the assignment polls
