### ISSUE TITLE
Sort motions by category is broken

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#2056]
**Reproduction:**
* Requires multiple motions with categories (and sub categories) e.g. A, A1, A2, B, B1, C, C1
* Motion have both, the category and a subcategory
* Sort motions by category
Now the motions order in tests was 
1. Motion with category A+A1
2. Motion with category B+B1
3. Motion with category C+C1
4. Motion with category C+C1
5. Motion with category A+A2
6. Motion with category A+A2 
7. Motion with category B+B2
8. Motion with category B+B2

Expected:
1. Motion with category A+A1
2. Motion with category A+A2
3. Motion with category A+A2
4. Motion with category B+B1
5. Motion with category B+B2
6. Motion with category B+B2 
7. Motion with category C+C1
8. Motion with category C+C1

**Comment by jsangmeister** [comment]
Detailled minimal working example:
1. Create new meeting
2. Create 3 categories: A, B, BB
3. Sort the categories in the following order (indent BB):
  - A
  - B
    - BB
4. For each category, create a motion (be sure to select the category during the creation dialog to automatically assign the correct prefix, this makes recognizing the wrong sort order easier)
5. Now, go to the motion list and sort by ascending category. The order will be A, BB, B while the correct order with respect to the subcategory relation would be A, B, BB.
