### ISSUE TITLE
Dynamic agenda subtitles cannot be supported

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#206]
I noticed something strange while working on https://github.com/OpenSlides/openslides-client/pull/204.

implicit agenda content objects cannot resolve the second level of underlying ViewModels.
https://github.com/OpenSlides/openslides-client/blob/fe0974d0f1490d4259f1ecaf5373c585c9d799b5/client/src/app/site/agenda/components/agenda-list/agenda-list.component.ts#L162-L171
As we see here, the content_object_id will be resolved to their corresponding `title` filedset. This us usually fine, but limits to use native values of the model only.

Since the detail of the ViewModel is hidden in this case (can be Motion, Assignment or Topic) we cannot resolve nested ViewModels anymore, since the fieldset can only access native values of their model.

That means, that we currently could not resolve the (motion) submitter (as user) from the agenda item. The subtitle of motions are their submitter, even in the agenda list.

**Comment by FinnStutzenstein** [comment]
Right, I'll do something about it. (When I designed it, this wasn't needed and implemented in OS3 yet;) )

**Comment by FinnStutzenstein** [comment]
(see #227 )

> Since the detail of the ViewModel is hidden in this case (can be Motion, Assignment or Topic) we cannot resolve nested ViewModels anymore, since the fieldset can only access native values of their model.

It is implemented, that you can try to follow a relation which is only valid for a subset of collections. In this case it is totally fine to follow `submitter_ids`. This will not work for assignments, users, topics, ... (and be skipped by the model request builder) but for motions it will work.
