### ISSUE TITLE
motions: wrong link in summary of changes

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2060]
**Description:** 
In the summary of changes to a motion, there is an incorrect link. The first link to the amendment (the text) is set incorrectly. The link opens the URL of the instance instead of the amendment. The arrow, on the other hand, links correctly.

Relevant text with link = Zeile 4 (Änderungsantrag -Ä03)
![Screenshot_20230225_124924](https://user-images.githubusercontent.com/105491030/221355256-7a83af2e-f02b-404b-95ad-a9a40b8b02b1.png)

**Reproduction:**
1. open a meeting
2. open motions
3. create a motion
4. create an amendment to it
5. open the motion, set check mark for amendments to see the summary of changes list.
6. hover over the text link and check the link.

**What should happen:**
The text link, just like the arrow, should link to the correct amendment.

**Comment by bastianjoel** [comment]
When clicking the link the browser scrolls to the amendment. This is what should happen.
