### ISSUE TITLE
Changes in `MatDatePicker` falsy detected

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2076]
When entering the general settings of a meeting, the "save" button is directly enabled, although no changes happened yet. Since this only happens on the "general" page, my guess is that the date picker is at fault.

Also, some QoL improvements for the date picker:
- You have to click twice to open the date picker. The dialog should open as soon as the form field is focussed.
- You have to explicitly click "Apply" after selecting a date, which is unnecessary IMO.

**Comment by jsangmeister** [comment]
This may become obsolete if we implement a date range picker as suggested in https://github.com/OpenSlides/openslides-client/issues/2059. Also has some overlap with https://github.com/OpenSlides/openslides-client/issues/1984

**Comment by luisa-beerboom** [comment]
We should really do the QoL improvements as part of the solution to #2059 
They fit better there
