### ISSUE TITLE
duplicated groups in cloned meeting in chrome(-based?) browsers

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#2081]
### Reproduce:

* Use Chrome browser
* Clone a meeting
* Enter the copied meeting
* navigate to participants -> groups (three-dot-menu) -> all groups listed normally
* go back to meeting list
* navigate to participants -> groups (three-dot-menu) -> all groups duplicated

This only happens once and only in the fresh copy of the meeting.

**Comment by luisa-beerboom** [comment]
Can't replicate.
@MSoeb can you please check if this is still an issue and, if yes, provide a working reproduction method?

**Comment by MSoeb** [comment]
Try to replicate it without success. Maybe it was already unintentionally fixed by another fix. Therefor I would close it now.
