### ISSUE TITLE
Motion amendments lose reference to main motion when main motion is not visible

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2082]
Reproduction:
1. Create a meeting (preferably disable setting "show amendments in main motion list")
2. Create a motion
3. Create an amendment for that motion
4. Ensure that the amendment and the motion have different states/are part of different workflows
5. Open a second window as someone (a Delegate for example) who doesn't have the right to see internal motions and open the motion list
6. Set the visibility of the main motions state to "internal"
7. The main motion should disappear from the delegates view.

Now there will be two problems:
1. The amendment will not have a reference to the main motion any more and display that "the origin motion has been deleted" in the detail view
2. If "show amendments in main motion list" has been disabled in step one, the amendment will now be displayed in the main meeting list, since the program doesn't recognize it as an amendment any more

Possible solutions:
- Ensure that amendments can't be changed from an internal state to a non-internal state if the main motion is still internal (client-only)
- Change the restrictor so that amendments will not be shown if the lead motion is restricted (probably not optimal, since it removes functionalities)
- Change the restrictor or the backend or the subscriptions (would need investigation which one it should be) so that the lead_motion_id is always known to any amendment, even if the main motion is not visible (this will enable the client to filter the list more accurately). Ensure that this doesn't cause any mistakenly shown client links.
- Introduce a new (calculated?) field in the backend motion model that clearly differentiates main motions from amendments

**Comment by ostcar** [comment]
I have no preference at all. If you want me to change the restricter, I can do this.

At the moment, there is no special case for amendments at all. For the restricter, a amendment is a motion like any other motion.

I could change the restricter, that if `lead_motion_id` is not `null`, a user can only see it, when he also can see the lead motion.

The solution 3 is probably not possible. The field `motion/lead_motion_id` is a relation-field. Currently, a relation-field is only visible to a user, if the user can also see the other side of the relation. I added this rule, so the client gets consistent data. On the server side, it would be a corrupted database, if the field `motion/42/lead_motion_id` would direct to a motion, that does not exist. I thought, that the restrictor should simulate the same behaviour for the client. In the past, there where other situations, where this was a problem. If you want, I can remove this rule and do not restrict relation-fields at all (only with the normal rules, but not with the rules of the other side of the relation). This would be helpful for performance, but you would have to handle any case, that the direction of a relation is not visible to a client.

**Comment by luisa-beerboom** [comment]
Talked with @rrenkert : We should go with Version number two: Restrict amendments if the lead motion is also restricted.
That should fix everything completely without any more coding work in other repos

I'll write an autoupdate issue

**Comment by luisa-beerboom** [comment]
> For the future: github has the feature to move issues around. So it would be possible to transfer this issue to the autoupdate-service. Should we do this in the future for simular situations?

Yeah I should have probably just done that
