### ISSUE TITLE
Default groups with voting rights ignored for agenda polls

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#2084]
When creating a agenda poll groups selected in `Settings -> Elections -> Default groups with voting rights` are not preselected in `Entitled to vote` field.

**Comment by jsangmeister** [comment]
https://github.com/OpenSlides/openslides-backend/issues/1675

Did not notice this when suggesting this issue for this sprint - we can move it to the backlog again for now.
