### ISSUE TITLE
`Import` button is clickable multiple times

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2086]
If you import a file e.g. under `/participants/import`, you can click the import button multiple times. This does not change any actual data, since the imported data should not differ from the data to import, but the counter does count up (so that it says "8 of 4 participants imported) and it is generally confusing and should be disabled.

**Comment by rrenkert** [comment]
Keep open for test after new imports are implemented.

**Comment by rrenkert** [comment]
Successfully tested with topic import on 4.0.8-staging-20230901-3e362fe. Immediately after clicking the import button a spinner comes up.
