### ISSUE TITLE
ICC count-user-service

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#2106]
The `user-count` does not work on bigger meetings. I don't know the reason but fond a bug in this context.

When a client receives a [cound-user-request](https://github.com/OpenSlides/openslides-client/blob/cda27523d520f6add054090320f044c646820dc2/client/src/app/site/pages/meetings/pages/home/pages/meeting-info/services/count-users.service.ts#L18), he sends a response like 

```
{
    "name": "count-user-response",
    "message": {
        "token": "nochmal bitte2",
        "data": {
            "userId": 16438
        }
    },
    "channel_id": "BBGaSEjZ:16438:15970",
    "to_meeting": 966,
    "to_channels": [
        "BBGaSEjZ:16438:15934"
    ]
}
```

This tells the ICC-Service to sends this message to the channel `BBGaSEjZ:16438:15934` AND to all users in meeting `966`. But only the user that clicked on "count users" should receive this messages. So the attribute `to_meeting` has to be removed.

When I read the client code, it seems, that the [notify.service](https://github.com/OpenSlides/openslides-client/blob/main/client/src/app/gateways/notify.service.ts) currently does not support to skip the `to_meeting` attribute. Maybe the client `notify.service` has to be rewritten. The attributes `to_meeting`, `to_channels` and `to_users` are optional. If non are provided, the message is send to nobody. If more then one of the attributes are provided, the message is send to all of them.

**Comment by luisa-beerboom** [comment]
The `to_meeting` in the request may be removed by PR #2201
