### ISSUE TITLE
Optimization: instance URL in mail should open in a real browser 

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2114]
Problem description: Many email clients on mobile devices or tablets open URLs in mails in a preview browser in the mail client. These browsers do not necessarily have the same functionality as standard browsers. Most users do not realize that they have not opened the instance in the default browser when they click on the URL. This can cause undesirable technical as well as usability problems. 

This problem specifically affects the access data mail and the included instance URL.

Proposed solution: The instance URL should be set so that the mobile device or tablet opens the URL OBLIGATORILY in the default browser.

**Comment by jsangmeister** [comment]
I don't think that's possible. We can only control the content of the mail, not what the email program does with this. The content is either plain text or HTML, an neither offers the possibility to control what program is started when clicking on a link.
