### ISSUE TITLE
Redesign election ballot

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#2128]
The ballot for elections should be redesigned. See following mockups:

Meeting Admin view includes progress:
![20230214JaNeinEnthaltungAdmin](https://user-images.githubusercontent.com/19685715/227577948-c4c41a31-26c7-499c-bf1d-d5bbc3bbcabb.svg)

Delegates view:
![20230214JaNeinEnthaltung](https://user-images.githubusercontent.com/19685715/227578398-5819e8b2-d591-4ece-8012-28fae9721a1a.svg)

**Comment by Elblinator** [comment]
Please talk to @MSoeb or @emanuelschuetze for detail questions about the design!!
