### ISSUE TITLE
Bulleted lists in amendments destroy the amendment presentation

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#2129]
`…/…/motions/…`

### Bug description
If an additional paragraph containing an unsorted bullet list is added at the end of a motion via an amendment, the changes are not displayed correctly.

![Bildschirm­foto 2023-03-25 um 09 31 36](https://user-images.githubusercontent.com/23032204/227706619-25e08721-b8a9-4ba0-8513-555da1438f9b.png)

### Expected behavior
Additions should be inserted and displayed correctly, even if they contain enumerations. Like this, but with bullet points:

![Bildschirm­foto 2023-03-25 um 09 32 39](https://user-images.githubusercontent.com/23032204/227706616-0ea947ce-29d4-400d-a8c7-359916f51fe2.png)

### Additional context
OpenSlides: → 4.0.1-main-20230309-2f5789e

**Comment by CatoTH** [comment]
Hi,

sorry for the delay. I created a Pull Request for this issue here: https://github.com/OpenSlides/openslides-client/pull/2226
