### ISSUE TITLE
Filtered motion list scrolls up after autoupdate

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#2130]
* create many motions (with categories) to get scrollbar
* filter motion list by one category
* scroll down (to get scrollbar not on top)
* now open motion list in new tab > open one motion of the (filtered) list and set e.g. state of this motion
=> filtered motion list (from tab 1) is scrolled up (until first motion)

**Comment by luisa-beerboom** [comment]
Can't replicate.
@emanuelschuetze @rrenkert Please check if this is still happening and/or include instructions that actually work.

**Comment by emanuelschuetze** [comment]
I cannot reproduce it any more with current main. Could be fixed by last autoupdate improvements. I closed this issue.
