### ISSUE TITLE
Motion text editor: justification of text format didn't work

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2135]
Description: Editing a text segment or the whole text of a motion in justification format doesn't work. The editing in the text editor works fine, but it isn't saved. The motion is still in the original text format. 

Text editor: text format changed to justify
![Screenshot_20230328_163113](https://user-images.githubusercontent.com/105491030/228272262-cce1412e-076e-4897-8e85-ec3c88af675e.png)

Motion view after save
![Screenshot_20230328_163139](https://user-images.githubusercontent.com/105491030/228272420-299583cb-f03c-4f38-a638-8d69f209dee7.png)

Reproduction:
1. create a motion with at least 3-4 lines.
2. edit the text format to justification and save it

What should happen:
Text format can be changed to justification (justify).

**Comment by bastianjoel** [comment]
See annotations in #2142

**Comment by emanuelschuetze** [comment]
As discussed: We don't want to support justified text in motions (PDF). So please just remove justified text also in tinymce editor.
