### ISSUE TITLE
Issue with setting "Only present participants can be added to the list of speakers"

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2150]
**Description:** The setting "Only present participants can be added to the list of speakers" doesn't work as it should. If this option is selected only the superadmin can add user to the list of speakers. No user could do it. This seems to be a permission issue.

**Reproduction:**
Condition: Three Accounts needed; superadmin, admin account on meeting level and a user with special permission to administrate the List of Speakers. 

as superadmin
1. open a meeting
2. open agenda and create a topic
3. project the topic in the autopilot
4. open settings > List of Speakers and mark "Only present participants can be added to the list of speakers"
5. go to participants 
6. grant the admin account admin permissions
7. grant the superadmin admin rights for this meeting
8. open three-dot-menu > groups and add a new Group called WMS (Wortmeldestelle). Grant the following permissions: Can see the projector, Can see agenda, Can see list of speakers, Can manage list of speakers, Can see motions, Can see elections, Can see participants, Can see the front page and Can see the autopilot
9. add the third user to the group WMS
10. create two addtional users, put them in group delegates and mark them as present

as meeting admin
1. open the meeting and autopilot
2. try to add one of the delegates to the list of speakers -> user could only add itself to the list

as third user
1. open the meeting and autopilot
2. try to add one of the delegates to the list of speakers  -> user could only add itself to the list

**What should happen?** 
It should be possible, that meeting admins or users with the right to manage the list of speakers (and see participants) should be able to manage the list and add present participants, just like the superadmin, to the list. In the current status the setting "Only present participants can be added to the list of speakers" is not usable, because only superadmins could add users to the list of speakers if this setting is marked.

**Comment by luisa-beerboom** [comment]
Tested it out:
Going to the participant list, then going back to the autopilot and trying again fixes the problem.
Seems to be an issue with the autoupdate subscriptions
