### ISSUE TITLE
Global head bar isn't fixed on several pages - should be always visible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2155]
**Description**: The head bar isn't fixed in several menus and could be scrolled away. 

menus:
- [x] autopilot
- [x] motion and amendment detail view
- [ ] motion call list
- [ ] comment fields list
- [ ] participants > three-dot-menu > groups
- [ ] user detail view
- [ ] projector menu
- [ ] chronic
- [ ] setting menu and all of it's sub-menus
- [ ] chat

**Reproduction:**
1. open a meeting
2. open the menus above and add some content to see a scroll bar. try to scroll it down to check, if the head stays visible. 

**What should happen:**
The head bar should always be visble.

**Comment by luisa-beerboom** [comment]
Views can have multiple types of "headbars" at once. See below:

![Screenshot_20230405_132847](https://user-images.githubusercontent.com/101706784/230069595-a2963ad8-ca41-4bfd-a098-41072f5bd7e0.png)

I have checked multiple of the above views and the view's headbar doesn't seem to vanish, are you talking about the global headbar?

**Comment by rrenkert** [comment]
Yes, its the global headbar that disappears in the views mentioned above.
