### ISSUE TITLE
statue amendments have no diff-visualization

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2160]
**Description:** 
Currently it is not possible to use statute amendments. They can be created, but the amendments miss a difference view. It is not possible to recognize, which part is changed. 

example of a statute amendment without dif-view
![Screenshot_20230331_124426](https://user-images.githubusercontent.com/105491030/229099644-2dcd9415-d4b4-489a-974f-60c38a97cb1f.png)

**Reproduction:**
1. open a meeting
2. open settings > motions > amendments > mark _Activate statute amendments_ check box
3. open motions > three-dot-menu > statute --> create a new Statute paragraph
4. go back to motions and create a new motion
5. motion creating process: mark checkbox for statute amendment and select the created paragraph in the drop-down-menu. Now change text and save it. 
6. --> The new statute amendment is displayed with changes, but without the necessary dif-dview.

**What should happen:**
Statute amendments must have the same dif-view like other amendments.

**Comment by emanuelschuetze** [comment]
We think about replacing statute amendments by (paragraph-based) amendments (with working diff).
