### ISSUE TITLE
Save sort order only on change

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2166]
Currently, when a list view is opened, the algorithm to check the sort order in `base-sort-list.service.ts` is as follows:
1. Try to fetch the saved sort order from the local storage
2. If not present, use the default sort order
3. Save the sort order to local storage

This should be changed so that step 3 is not executed anymore. The sort order should only be saved to the local storage if the user explicitely changes it. This means that a normal user who does not change her sorting order will always see the default sorting order, even when it is changed by the admin, which is the reason for this change.

**Comment by luisa-beerboom** [comment]
Discussed the the second and third point with @Eich-hoernchen (who has pledged to make a mock-up for this later)
The general consensus for changing the filter bar (as I've understood it) was as follows:
Concerning the second point:
- In order to not clutter the display too much and since we don't have any text to display anyway, we will use a smaller dot icon in the same colour
Concerning the third point:
- There will be a toggle button for ascending/descending between the sort button and the search bar. It will contain an icon (something akin to `v` or `^`) representing the current direction.
- The asc/desc arrow will be removed from the selector, the empty space on the left that has been reserved for such icons will therefore also be gone
- Instead the current selection will be shown by darkening selected row.
- The selector will always be sorted to display the standard selector at the top. This standard-selector-displaying first line will also be separated from the others using a divisor, a `*` will be appended to the name and there will be a tooltip for the entire line marking it as the standard sorting.

**Comment by jsangmeister** [comment]
> * don't save motion sort option into local storage if user is on default option

This might be be confusing again: If a user often changes his sorting order of the motion list and is currently again at the default option by chance (but by choice: he currently wants to sort by this option for whatever reasons) and the default sort order is changed, the sort order for the user will change without any interaction from his part. Not necessarily saying that this is a no-go, justb wanting to point it out.

**Comment by luisa-beerboom** [comment]
> > * don't save motion sort option into local storage if user is on default option
> 
> This might be be confusing again: If a user often changes his sorting order of the motion list and is currently again at the default option by chance (but by choice: he currently wants to sort by this option for whatever reasons) and the default sort order is changed, the sort order for the user will change without any interaction from his part. Not necessarily saying that this is a no-go, justb wanting to point it out.

As far as I've understood it from the meeting, the idea was more to not save sort options in local storage, except for the specific circumstance where the user has changed it himself (i.e. if the user has never changed the option he will always see whatever the current default is)

Or am I wrong @emanuelschuetze ?

**Comment by jsangmeister** [comment]
As I described it above, the process would be:
- The user opens the motion list for the first time -> nothing is saved to local storage
- The user changes the sort order manually -> the new order is saved
- The user changes the sort order back to the default -> the default order is saved
- The meeting admin changes the default order -> nothing changes for the user

As you described it (as I understood it), the process would be (changes in bold):
- The user opens the motion list for the first time -> nothing is saved to local storage
- The user changes the sort order manually -> the new order is saved
- The user changes the sort order back to the default -> **the local storage entry is deleted**
- The meeting admin changes the default order -> **the sort order changes for the user**

This might or might not be what we want, we should just formulate it clearly and precisely.

**Comment by luisa-beerboom** [comment]
> As I described it above, the process would be:
> 
>     * The user opens the motion list for the first time -> nothing is saved to local storage
> 
>     * The user changes the sort order manually -> the new order is saved
> 
>     * The user changes the sort order back to the default -> the default order is saved
> 
>     * The meeting admin changes the default order -> nothing changes for the user
> 

^ This is exactly what I tried to describe [here](https://github.com/OpenSlides/openslides-client/issues/2166#issuecomment-1503456809)

> 
> As you described it (as I understood it), the process would be (changes in bold):
> 
>     * The user opens the motion list for the first time -> nothing is saved to local storage
> 
>     * The user changes the sort order manually -> the new order is saved
> 
>     * The user changes the sort order back to the default -> **the local storage entry is deleted**
> 
>     * The meeting admin changes the default order -> **the sort order changes for the user**
> 

^ This is how I also understood [this](https://github.com/OpenSlides/openslides-client/issues/2166#issuecomment-1503040205)

> 
> This might or might not be what we want, we should just formulate it clearly and precisely.

Which is why @emanuelschuetze should clear up what he meant

**Comment by emanuelschuetze** [comment]
> As far as I've understood it from the meeting, the idea was more to not save sort options in local storage, except for the specific circumstance where the user has changed it himself (i.e. if the user has never changed the option he will always see whatever the current default is)

Correct.


> * The user opens the motion list for the first time -> nothing is saved to local storage
> * The user changes the sort order manually -> the new order is saved
> * The user changes the sort order back to the default -> **the local storage entry is deleted**
> * The meeting admin changes the default order -> **the sort order changes for the user**

Correct.

Background: The meeting admin needs the possibility to change directly the defaulit order during meeting for all users with default order (without reload). Only users with custom order should not changed.

**Comment by luisa-beerboom** [comment]
This:

> > As far as I've understood it from the meeting, the idea was more to not save sort options in local storage, except for the specific circumstance where the user has changed it himself (i.e. if the user has never changed the option he will always see whatever the current default is)

and this:

> > * The user opens the motion list for the first time -> nothing is saved to local storage
> > * The user changes the sort order manually -> the new order is saved
> > * The user changes the sort order back to the default -> **the local storage entry is deleted**
> > * The meeting admin changes the default order -> **the sort order changes for the user**

are antithetical.
If the user manually changes the sort option to default, he "changed it himself". According to the above definition it should therefore not change if the admin changes the default sort order. 

Please pick one @emanuelschuetze

**Comment by emanuelschuetze** [comment]
> * The user opens the motion list for the first time -> nothing is saved to local storage
> * The user changes the sort order manually -> the new order is saved
> * The user changes the sort order back to the default -> **the local storage entry is deleted**
> * The meeting admin changes the default order -> **the sort order changes for the user**

Ok, I understand. Then use this definition.
