### ISSUE TITLE
Add "non-binary" as gender option

### ISSUE THREAD

**Issue by colinmahns** [OpenSlides/openslides-client#2207]
The current three options for gender are less than ideal for my userbase ("male", "female", "diverse"). "Diverse" doesn't quite translate well with American vernacular, and some users may not feel they are "diverse" and are just a single gender (e.g. someone is non-binary and only that).  

This would be better as either a user-customizable text box similar to the pronouns field, or if admins would be able to set other genders as pre-programmed options.

**Comment by jsangmeister** [comment]
Thanks for your suggestion! We've had similar requests in the past and decided on the current implementation as a compromise which was easy to use and maintain, but also suffices for most users. We will debate whether to change this.

**Comment by jsangmeister** [comment]
That could certainly be a possible compromise.
