### ISSUE TITLE
Amendment diff error for nested lists

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#2219]
* Create new motion with nested list, e.g.
```
<ul>
<li>1</li>
<li>2
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
</ul>
</li>
<li>3</li>
</ul>
```
* create a (paragraph-based) amendment > select 2nd paragraph (with nested list) > click NEXT
* add new sub-item to list (e.g. entry "d") > click CREATE
=> amendment shows full diff (= all items are red/green). Expected: only new line should be green

**Comment by rrenkert** [comment]
I think this is a duplicate of #1767

**Comment by emanuelschuetze** [comment]
confirmed.
