### ISSUE TITLE
Editorial final version editor closed automatically by autoupdate

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#2233]
* Create motion and set to 'accepted'
* No create "Editorial final version"
* Open editor of editorial
* Click to "edit" icon
* Keep editor open
=> sometime (e.g. if you get some special? autoupdates) the editor closed automatically - without saving!

Can't reproduce it exactly - but while event I get this error serveral times.

**Comment by emanuelschuetze** [comment]
@bastianjoel Any idea? Can you stop all automatically switching from editor to read-only view?

**Comment by bastianjoel** [comment]
To replicate open motion in another tab, edit motion, add something to the motion text and save.
