### ISSUE TITLE
Livestream: Auto Playback of YouTube livestream didn't start on mobile devices

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2254]
**Description:** A YouTube livestream doesn't start automatically on mobile devices like smartphones or tablets. The user must manually start the livestream.

**Reproduction:** 
1. Open a meeting
2. open settings > livestream > add a YouTube livestream in _Livestream URL_
3. open the meeting on a mobile device and check the livestream

**What should happen:**
The YouTube Livestream should start automatically after user login or after it is setup by an admin. 

**My two cents:**
I guess, the issue can hardly be solved, beacuse from my point of view mobile devices have disabled autoplayback by default. Therefor I dont' labeled this issue with the bug-tag but with needs discussion, if it is not fixable.

**Comment by bastianjoel** [comment]
I don't think this is possible. 

https://developers.google.com/youtube/iframe_api_reference#Autoplay_and_scripted_playback
