### ISSUE TITLE
It should not be possible to scroll over (head-)bars

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2259]
Currently a bunch of views have problems where either the global headbar, the view headbar or the filter bar can be scrolled out of the view.

All of them should always remain fixed to their position.

Even if there is some sort of voting banner.

One possible approach to this would be to move all three possible bars into the same component (something like `HeadbarCollectionComponent`), control it via a global service (i.e. what kind of headbar should be shown, whether there should be a filter bar, what the filter bar should contain, etc) and place the new component where only the global headbar is currently placed.

**Comment by MSoeb** [comment]
Here is an image how the bars should look like:
![Screenshot_20230505_144048](https://user-images.githubusercontent.com/105491030/236460036-246a674e-4ddb-45be-b9a8-e567937358d6.png)
