### ISSUE TITLE
description for activating the Star-Icon needs improvement

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2283]
**Description:** The description of the function to active the star-icon in the list of speakers needs an improvement. In the current state it doesn't reflect that this function will activate the new option for speakers. It suggests that another account, like admin, could mark speakers with the icon. But that's wrong. The admin could do it even without this setting. In fact, the speakers could mark their speechs with it.

![Screenshot_20230511_145750](https://github.com/OpenSlides/openslides-client/assets/105491030/81a8d953-ea1a-4396-a86a-8e178b50392b)

**Where to find:**
1. open a meeting
2. open seetings > list of speakers > Enable star icon to mark speaker (e.g. for contribution)

**What should happen:**
The german description and all others should be improved.

Old: Stern-Icon zum Markieren von Redner*innen aktivieren (z.B. zur Einbringung eines Antrags)
New: Stern-Icon Markierung für alle Redner*innen aktivieren (z.B. zur Erkennung der Einbringung eines Antrags)

**Comment by MSoeb** [comment]
New text: "Stern-Icon Markierung darf auch von Redner*innen aktiviert werden"

**Comment by jsangmeister** [comment]
Current english string: "Enable star icon to mark speaker (e.g. for contribution)"
Suggested change: "Enable star icon usage by speakers"?

**Comment by MSoeb** [comment]
@jsangmeister sounds good.
