### ISSUE TITLE
List of speakers cannot be rearranged on mobile

### ISSUE THREAD

**Issue by eiclu** [OpenSlides/openslides-client#2306]
**Describe the bug**
When resizing the window the sliders to rearrange the speakers disappear

Wide View:
<img width="622" alt="image" src="https://github.com/OpenSlides/OpenSlides/assets/6774795/8ea1304b-4b69-4f38-95e2-e2b92bccee2f">

Narrow View:
<img width="624" alt="image" src="https://github.com/OpenSlides/OpenSlides/assets/6774795/17c913a3-bb40-4632-b677-70e1f8765ff2">

**How to Reproduce**
1. Add more than one person to the list of speakers
2. Resize the window so that the sidebar disappear

**System information**

- OpenSlides-Version: 4.0

**Comment by jsangmeister** [comment]
Thanks for the feedback! We will look into this.

**Comment by jsangmeister** [comment]
@bastianjoel I would suggest to reopen and merge the linked PR - having the feature without visual feedback is better than not having the feature at all. Or was there another reason why you closed it?

**Comment by bastianjoel** [comment]
I am not entirely sure anymore. I think it was just quite weird to use without that feedback. Before merging we should definitely test this again on a touch device.

**Comment by jsangmeister** [comment]
moved the label to the PR
