### ISSUE TITLE
Side nav bar is inconsistently shown/hidden for different window sizes

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2307]
- For sizes >= 960px, the side nav bar is shown.
- For sizes between 910px and 959px the side bar is (correctly) hidden.
- For sizes between 901px and 909px, the side bar is (incorrectly) shown again.
- For sizes <= 900px, the side bar is again correctly hidden.

Unfortunately (and irritatingly), this does not work in the responsive emulator mode of the dev tools, but only when resizing the window manually.

If you use chrome and open the dev tools, you can see the window size in the top right corner of the OpenSlides window while resizing.

Additionally, the animation to slide the nav bar in/out does not seem to work on firefox, although this has a rather low priority.

**Comment by bastianjoel** [comment]
Can't replicate

**Comment by jsangmeister** [comment]
I've been able to replicate it in both chrome and firefox. Note that using the responsive emulator in the dev tools does not work, you have to resize the actual window.

**Comment by bastianjoel** [comment]
The browser window has to have a certain height for the issue to occur so that it is handled as `portrait` mode.
