### ISSUE TITLE
Improvements to Search-Value Selectors

### ISSUE THREAD

**Issue by eiclu** [OpenSlides/openslides-client#2309]
**Describe the bug**
When adding people to the list of speakers, the selection dropdown remembers the last entered search query. When reopening the selection dropdown, newly entered text is appended to the last selection, so when quickly adding people to the list of speakers, one always has to delete the last query from the selection before finding other people, leading to a disruption of flow.

**How to Reproduce**
Enter the beginning of a name you want to add
![image](https://github.com/OpenSlides/OpenSlides/assets/6774795/94924ee8-dd57-4f68-9112-03ecd7e963ae)
Add the user
![image](https://github.com/OpenSlides/OpenSlides/assets/6774795/05866505-a831-45fa-bc00-28f9585537e7)
Reopen the dropdown
![image](https://github.com/OpenSlides/OpenSlides/assets/6774795/03d45ccf-f571-40ef-870f-5606ec38558b)
Start typing and don't find the relevant users
![image](https://github.com/OpenSlides/OpenSlides/assets/6774795/602cab67-f145-4ee1-8967-6bfaf43564bf)

**Expected behavior**
When opening the selection dropdown, one can always start typing a new query without removing the old query first.

**System information**

- OpenSlides-Version: 4.0

**Comment by emanuelschuetze** [comment]
Additional improvement:
Select a searched/filtered speaker with enter/cursor key.
(Currently, cursor down or enter key does not work. You have to use the mouse.)

**Comment by jsangmeister** [comment]
This goes for all search value selectors. 

Further improvements:
- Navigate through entries with up and down keys
- Select the current entry with the enter key
