### ISSUE TITLE
List of entitled groups in poll preview has spaces after each name

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2322]
If you create a poll in a motion or assignment, the preview in the detail page of the motion/assignment will contain a list of groups which are entitled to vote. After each name and before the separating comma, there is an unnecessary space.

**Comment by jsangmeister** [comment]
Putting it into Todo since it should be a pretty small fix

**Comment by rrenkert** [comment]
Tested in staging release 4.0.2-staging-20230608-5be7087. Fix does not remove the unnecessary space.
