### ISSUE TITLE
Add new timestamp for motions

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#2327]
`…/…/motions/workflows/…`

### Feature description

Rename the Setting "Set timestamp of creation" to "Set timestamp".

### Background
The text label "Creation date" (in the Motion itself also in the Workflow-Settings) is misleading because the timestamp does NOT indicate when a motion was created. The timestamp is only set when the status is selected for which the option has been activated. This point in time is used as the timestamp, and this does not necessarily have to be the first status.

**Comment by alveolus** [comment]
@emanuelschuetze : This case is a bit tricky... Basically both data are important:
When was the motion CREATED
When was the status selected/achieved for the motion, for which a timestamp has now been set.

**Comment by jsangmeister** [comment]
Currently, we have the two fields `created` and `last_modified`. The suggestion would be the following:
- `last_modified` stays the same and is updated on every change.
- `created` is reverted back to its original functionality and is filled automatically upon motion creation.
  - Additionally, it becomes updatable in `motion.update` with permission `motion.can_manage`, so users can manually set a date if e.g. the motion was submitted earlier and is now manually entered into OpenSlides.
- A new field (e.g. `workflow_timestamp`) is introduced which copies the current functionality from `created` and is controlled by the workflow setting. Rename this setting as suggested above (or maybe "Set workflow timestamp"?).

This way, we have all functionality clearly separated and no information is lost.
