### ISSUE TITLE
Replace libraries that use ViewEngine

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#2345]
`ViewEngine` libraries are deprecated with angular 16. To make an update easier we should update or replace libraries that currently use it. 

The following libraries are affected:
- @biesbjerg/ngx-translate-extract-marker https://github.com/biesbjerg/ngx-translate-extract-marker.git
- ngx-material-timepicker https://github.com/Agranom/ngx-material-timepicker.git (update available)
- ~~ngx-papaparse https://github.com/alberthaff/ngx-papaparse (update available)~~

~~Timepicker replacement:~~
- ~~https://github.com/tonysamperi/ngx-mat-timepicker (does not support material legacy components)~~

Extract marker:
This library is so small that we should just implement its functionality ourselves in a helper function.

**Comment by bastianjoel** [comment]
There is a new fork of `ngx-translate-extract` which seems to be maintained [here](https://github.com/vendure-ecommerce/ngx-translate-extract). 

I would suggest merging our changes from https://github.com/OpenSlides/ngx-translate-extract to that fork and switching the dependency source.

**Comment by jsangmeister** [comment]
Sure, sounds good. Although we will have to rebase our changes everytime the base changes. We could try to create a PR to the fork and see if the changes are useful for other users as well, but IIRC at least some if it was relatively specific to our code.

**Comment by bastianjoel** [comment]
PR created https://github.com/vendure-ecommerce/ngx-translate-extract/pull/21
