### ISSUE TITLE
UI: livestream window overlaps other ui elements

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2367]
**Description:** The livestream window in the lower right corner overlaps other ui elements like buttons for administration. For example: The buttons in the agenda list could not easily be used. This also affects other menus with lists. 

![Screenshot_20230605_115854](https://github.com/OpenSlides/openslides-client/assets/105491030/b7b6ccd5-fe49-48db-b334-0bac7a9263a5)

**Reproduction for agenda example:**
1. open a meeting
2. open agenda
3. generate a few topics
4. shrink the browser to see overlapping.

**What should happen:**
It should be possible to use all functions even with a livestream window. I'm not sure how it could be solved in the best way. A solution could be that a new bar at the bottom appears when a livestream window is active. So all UI elements could be used quite easily.

**Comment by luisa-beerboom** [comment]
@rrenkert @MSoeb @Eich-hoernchen How should views like the category detail view be styled?

Should there be an empty space below the card?
Should it be within the card?
Should the card maybe be styled the same as the other cards in OpenSlides? (i.e. empty space to both sides of the card)
