### ISSUE TITLE
meeting dupe don't work / language attribute not available in meeting edit view

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2371]
**Description:** If a user wants to create a new meeting on the basis of a template an error message appears and a new meeting can't be created. The error refers to a language attribute which can't be found. 

During the creation process of a new meeting, the language can be set. Afterwards, in the meeting edit view, the language attribute field is not visible anymore. I guess, that the missing language field is to reason for the duplication error.

**Problems:**
- [x] meeting dupe not possible (critical)
- [x] missing language field in meeting edit view (medium)

**dupe error:**
![Screenshot_20230605_155730](https://github.com/OpenSlides/openslides-client/assets/105491030/a6d1b04b-c75e-410e-810d-68613be61fe2)

**Reproduction:**
1. open an instance
2. open committee
3. create a new committee
4. create a new meeting
5. set this meeting as a template
6. open the committee page, click on the plus-icon to create another new meeting and choose the meeting template. try to create the meeting. (here the critical error appears)
7. open the first created meeting in the meeting edit view. language field is not available.

**What should happen:**
It should be possible to create a meeting from a meeting template. This should work with new and old meeting templates.
Addtionally the meeting language should be visible in the meeting edit view.  A new field is needed

**Comment by bastianjoel** [comment]
It is intended that the meeting language cannot be changed after a meeting was created.

**Comment by bastianjoel** [comment]
I am displaying the language in a disabled input now on edit and also when duplicate was selected.
