### ISSUE TITLE
Fix display with new side-nav width

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2415]
The side-navaigation now collapses if the display is 960px or less pixel wide.
At some point in time it collapsed at 959px. There are some leftover- artifacts which need adjusting.

Example of the first behaviour:
Screen if 961px (or more) wide: 
![961px](https://github.com/OpenSlides/openslides-client/assets/69210919/c8cf4957-0606-4253-96cc-34cde5739c64)
Screen if 960px wide:
![960px](https://github.com/OpenSlides/openslides-client/assets/69210919/1ed89407-6c95-4533-8ecf-964c2d56f47b)
Screen if 959px (or less) wide:
![959px](https://github.com/OpenSlides/openslides-client/assets/69210919/3efd521a-1d35-46ae-9c34-475507979292)

The following views display this behaviour:
- inside a meeting: settings
- Dashboard
- Motions in blockview (NOT motion blocks)

Example of the second behaviour:
Screen if 960px wide:
![960_NM](https://github.com/OpenSlides/openslides-client/assets/69210919/4692dd77-bef7-40f4-a8a8-54ffe7c6d5f7)
Screen if 959px wide:
![959_NM](https://github.com/OpenSlides/openslides-client/assets/69210919/217cdcbd-dd3f-467a-a885-5e65663c9a76)

The following view displays this behaviour:
- motions 

Problem:
both behaviours are not adjusted to the now 960px tablet view.

Wanted Behaviour:
For the first:
the screen at 960px should look and behave like the screen at 959px.

For the second:
the distance between the object and the border should not make such a jump. The changed width of the object should not be  visible. 

To recreate these behaviours go to the view in question and shuffle between a display 961px, 960px and 959px wide.

**Comment by jsangmeister** [comment]
We should just introduce a css var and use that everwhere
