### ISSUE TITLE
Motions: Styling around long lists of tags can be strange

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2430]
**Call list**
In the call list long lists of tags can squish the motion title together to an extreme degree:
![Call_list_tags](https://github.com/OpenSlides/openslides-client/assets/101706784/8cd24620-78ab-472e-8e12-88c469f052f6)
The title should probably have a minimum width to stop this kind of thing

**Motion list**
In the motion list the long tag lists have weird spaces before the separating commas. The text sometimes breaks lines in these spaces, causing new lines to start with these commas.
![motion_list_tags](https://github.com/OpenSlides/openslides-client/assets/101706784/e0f50f8f-e8dc-445f-a1fc-c9109299cc6d)
So that should be fixed as well.

**Comment by luisa-beerboom** [comment]
The call list doesn't even have commas, maybe we should also take care that these two places either both have commas or don't have them at all

**Comment by Elblinator** [comment]
Why are the tags displayed in a different manner than the orga tags? 
![tags](https://github.com/OpenSlides/openslides-client/assets/69210919/151dc3ea-951b-4ceb-bb4b-3ca49996a864)

I  recommend displaying them like the orga tags and removing the commas

**Comment by rrenkert** [comment]
We should split the styling things from the table layout.
Keeping the table layout in this makes it easy to resolve and we can decide the styling in the other issue.
