### ISSUE TITLE
The SAML config fields should get more descriptive labels and some helptext.

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2439]
Some fields in the orga settings have labels like `SSO IDP`, which explain very little about what is expected.
They should have more verbose labels and help texts that explain the functionality.

The content of these help texts and labels have currently not been decided on.
What should they be @emanuelschuetze ?

**Comment by emanuelschuetze** [comment]
Please use the following labels:
* Single Sign On settings -> Single Sign-On settings
* SSO enabled -> Enable SSO via SAML
* JSON source attribute -> Attribute mapping (JSON)
  _Helptext: "Use JSON key:value structure (key = OpenSlides attribute name, value = IdP attribute name)."
* SSO IDP -> Metadata of Identity Provider (IdP)
* SSO SP -> Metadata of Service Provider (SP)
* SSO private key -> Private key of Service Provider (SP)
