### ISSUE TITLE
Implement point of order customization

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2447]
- It should be possible to set custom point of order texts in the LoS settings and assign them ranks (smaller number => bigger rank).
- There also should be a setting that allows one to switch on rankings
- If there are custom point of order texts:
   - If there is only one custom text, rename the button to the text and use the text as the point-of-order name. 
   - If there are multiple custom texts open a selection field that lets the user select one of the texts from the list

Backend issue OpenSlides/openslides-backend#1774

**Comment by jsangmeister** [comment]
I think it's unnecessary work for the user to set the rank manually. I would suggest to use a sortable list where the rank is induced by the order of the list.

**Comment by luisa-beerboom** [comment]
> I think it's unnecessary work for the user to set the rank manually. I would suggest to use a sortable list where the rank is induced by the order of the list.

We already discussed that in the planning stage:
Using a sorting list wouldn't allow one to set the same rank for two categories, that is, however, a requirement.

**Comment by jsangmeister** [comment]
Okay, did not know this! Nevermind then
