### ISSUE TITLE
Prevent same group names

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2457]
At the moment it's possible to have two different groups with the identical names:

![same-groups](https://github.com/OpenSlides/openslides-client/assets/69210919/4394b294-8f60-4dd9-9858-9e2dc0c9578a)

They have to have the same rules at the moment. If a rule is selected/deselected for one of them the rule of the other is selected/deselected automatically

**Wanted behaviour:**
The users should not be able to create two groups with identical names. 
If they try to create a group with a name from another group a client error should appear and the group should not be created.

**Comment by luisa-beerboom** [comment]
Shouldn't this also include changes in the backend? I can see this causing problems with the participant import.

What do you think @r-peschke ?

**Comment by r-peschke** [comment]
> Shouldn't this also include changes in the backend? I can see this causing problems with the participant import.
> 
> What do you think @r-peschke ?

Yes, the backend must avoid this for groups, meetings and committees. I wrote https://github.com/OpenSlides/openslides-backend/issues/1783.

But I don't see problems with the participant import. W will check this anyway, but with the given meeting_id it should be always unique.
