### ISSUE TITLE
Fix Agenda sort collapse all/expand all

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2458]
while the agenda is being sorted it can happen, that the collapsed items expand all at once

**How to recreate:**

1. navigate to agenda > sort agenda
2. collapse all
3. let an autoupdate happen (e.g. change your own presence)
4. everything expands again

**wanted behaviour:**
the collapsed items should not expand because of an autoupdate, they should only expand when they are expanded again

**Comment by rrenkert** [comment]
Also happens in other filtered lists. @emanuelschuetze can give more information.
