### ISSUE TITLE
Fix Missing Groups

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2482]
In the account-detail-view the groups the account is belonging to is not displayed.

**Account-detail-view:**
![account-view](https://github.com/OpenSlides/openslides-client/assets/69210919/e9af60d7-7a6d-4d38-8e38-772f6457f53a)

**The groups which should be displayed**
![groups](https://github.com/OpenSlides/openslides-client/assets/69210919/ad5b1828-1344-4583-b1b8-b65b9938452e)

**wanted behaviour**
The according groups should be displayed in the account-detail-view

**Comment by MSoeb** [comment]
RTF should fix this -> issue in backlog. we will wait, what happens with rtf integration.

**Comment by Elblinator** [comment]
fixed by RTF
