### ISSUE TITLE
fix wrong and missing information of duplicated agenda items

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2496]
If agenda items are duplicated the connected tags vanish and the visibility (public/intern/hidden) can be wrong in the duplicated item

**current behaviour:**

1. go into agenda 
2. create a new topic A (visibility e.g. public)
3. activate multi select and select topic A
4. add a tag and change the visibility (e.g. to hidden)
5. stay in multiselect mode and duplicate topic A 
6. now one topic A with visibility hidden and a tag, and a topic A with visibility public and without a tag exist.

**wanted bahaviour:**
if a topic is duplicated the item should have the same visibility and the same tags.

**Comment by luisa-beerboom** [comment]
The duplication is done through the topic.create action which implementation-wise currently does not allow for tag_ids to be sent. This therefore requires changes in the backend before the client can do anything.

@jsangmeister @r-peschke what do you think?

**Comment by jsangmeister** [comment]
This is a bug in the backend, the wiki lists the `tag_ids` explicitely: https://github.com/OpenSlides/OpenSlides/wiki/topic.create. I will open an issue for this.

**Comment by jsangmeister** [comment]
https://github.com/OpenSlides/openslides-backend/issues/1813

**Comment by jsangmeister** [comment]
https://github.com/OpenSlides/openslides-backend/issues/1813 was merged, btw, so this can be continued
