### ISSUE TITLE
Deleted agenda items are still displayed in list when navigation back

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#2497]
1. Create two topic items
2. Delete one of the created items
3. Open the other topic item 
4. Navigate back

The deleted topic item is in the topic list again. When reloading the page the deleted entry disappears.

**Comment by luisa-beerboom** [comment]
In my pull request (#2563) I wrote this:

> The problem is the following: 
> 1. **Open agenda item list** => `agenda_list` subscription is open
> 2. **Delete one item** => The autoupdate sends a single-field update with the new value for the meetings `agenda_item_ids`, which will cause the client to consider these fields to be deleted, but NOT the autoupdate shared worker, which will continue to store them
> 3. **Go to the topic detail view** 
> 4. **Go back from the topic detail view** => In the short moment where the parameters change, the detailview doesn't have an id and therefore subscribes to the `agenda_list_minimal` (as it now believes itself to be the new topic form, which needs the agenda list information) The shared worker will send the already stored data (see point two: it includes the deleted models) as the initial data for the subscription which will then be used by the client completely unfiltered
> 5. **See that the deleted models seem to have returned**
> 
> Honestly we should do something about this quirk of our autoupdate handling system, but I didn't really have any idea what exactly can be done so I "fixed" it this way _for now_

We may need a follow up issue

@bastianjoel  what is your opinion on this

**Comment by bastianjoel** [comment]
I would consider #2563 a hotfix and therefore reopen this issue. 

I think the best way to fix this is by removing deleted elements from the autoupdate cache.

**Comment by Elblinator** [comment]
It is still possible for the removed agenda items to be displayed in the agenda. 
1. add an election to the agenda, then remove it and then add it again
2. you immediately go to motions and via multi-select add a motion to agenda
3. the election you removed and added is displayed twice in the agenda list and if you saw the agenda-list with too many items then the items will also be displayed in the agenda itself

**Comment by bastianjoel** [comment]
My approach solving this within the shared worker does not work as expected. We need to solve this somewhere else.
