### ISSUE TITLE
Some blank spaces are missing

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2500]
**Description:** In two cases blank spaces are missing.

- [x] **Case 1.** - motion projection: If a motion has more than one submitter, the submitter line missses a blank space.

example image:
![Screenshot_20230706_124323](https://github.com/OpenSlides/openslides-client/assets/105491030/a732c006-987c-4c6f-aadc-4fb3056969ed)

- [x] **Case 2.** - motion details view: If a motions contains a change recommendation a blank space bis missing in the summary of changes between line number and bracket.
![Screenshot_20230706_124607](https://github.com/OpenSlides/openslides-client/assets/105491030/e844385e-d9e8-4cdf-88e0-37bb50a56432)

**Reproduction:**
1. open a meeting
2. open motions
3. create a motion with two submitters > save
4. edit the motion text with a change recommondation
5. now set a mark in the amendmend checkbox to see the summary of changes. (case two appears)
6. open the three-dot-emnu in the motion and choose project
7. open the autopilot (case one appears=

**What should happen:**
Blank spaces should appear in the cases above.

**Comment by jsangmeister** [comment]
case 1 would be covered with my suggestion in https://github.com/OpenSlides/openslides-client/pull/2399#pullrequestreview-1510505932 - maybe it would be a good time to implement something like this

**Comment by MSoeb** [comment]
Note: check supporters and pdf

**Comment by luisa-beerboom** [comment]
Agenda tags have too many spaces

**Comment by emanuelschuetze** [comment]
motion relatoins in motion projection
