### ISSUE TITLE
Meeting create: small improvement for date picking

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2501]
**Description:** During a meeting create a user can set the date of the meeting. If the meeting date is only one day, the user needs click twice on the date to set it otherwise the meeting create won't save.

**Reproduction:**
precondition: a committee should exist.
1. open committes and open an existing one
2. clik on the plus-icon to create a new meeting
3. open the date field and try to set a date for a one day meeting. 

**What should happen**: If a user wants to create a one day meeting, one click on a specific date should be enough to set it. After clicking once on a date and clicking the Save button, the date field should have set the selected date as start and end date.

**Comment by jsangmeister** [comment]
Also the save button should not be enabled if there is an error in the form

**Comment by Elblinator** [comment]
while creating a new meeting the date-picker should initially be empty. 
Currently the date-picker has the current date selected

**Comment by Elblinator** [comment]
this is a new issue moved to #2612
