### ISSUE TITLE
[RTF] missing autoupdates

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2502]
- [x] default password is not displayed in account
- [x] in a meeting while editing a participant if anyhing from "Meeting specific information" (sans is_present) is changed, the information on the profile is not updated until a reload
- [x] in a meeting if you go into the editing mask from a participant who selegated their vote to someone: you have to reselect the participant the vote gets delegated to, otherwise an error is thrown: Cannot read properties of null (reading 'getMeetingUser')
- [x] superadmin: in meeting > motions > new motion > add to agenda Button is missing if the agenda is not reloaded (same for new election. To change the buttons default behaviour navigate to settings > agenda-settings > add to agenda. To be allowed to see the button for non-admin activate participants > group > can manage agenda

**Comment by bastianjoel** [comment]
>  in a meeting while editing a participant if anyhing from "Meeting specific information" (sans is_present) is changed, the information on the profile is not updated until a reload

This is not a autoupdate issue and I think this is not rtf specific. Also this might need discussion as changing a form which is currently in edit mode could introduce side effects. Other forms display a warning if somebody else is already editing.

**Comment by Elblinator** [comment]
> I think this is not rtf specific. 
This issue is RTF specific

**Comment by bastianjoel** [comment]
Only the meeting specific information does not get updated.

**Comment by bastianjoel** [comment]
> superadmin: in meeting > motions > new motion > add to agenda Button is missing if the agenda is not reloaded (same for new election. To change the buttons default behaviour navigate to settings > agenda-settings > add to agenda. To be allowed to see the button for non-admin activate participants > group > can manage agenda

To reproduce this the agenda needs to be empty.
