### ISSUE TITLE
[RTF] Fix in Motion Set Submitters > Add

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2509]
In motions > new Submitters cannot be added via the "New Submitters option

**Recreation:**
1. Create new motion without a submitter
2. navigate to motions 
3. start multi-select 
4. select the motion and "set submitters"
5. select a participant and press "add" 
6. Error: data must contain ['motion_id', 'meeting_user_id'] properties

**wanted behaviour:**
new submitters should be addable via multi-selection

**Comment by reiterl** [comment]
I cannot reproduce step 3. . How do I *start multiselct*? I have looked under the three-points and don't find it.

**Comment by jsangmeister** [comment]
In the motions list (e.g. https://demo.os4.openslides.com/1/motions), the first menu point in the three-dot menu is "Multiselect".

**Comment by reiterl** [comment]
Okay, mmh, in a new meeting I can select "multi-select".
