### ISSUE TITLE
deletion of user from archived and active meeting as meeting admin still possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2527]
Description: PR #2522 still has a small bug for meeting admins. As a meeting admin it is still possible to delete a user, which is part in an active and archived meeting, globally. 

Reproduction:
Precondition: The deletion should be done as a meeting admin.
1. Create 2 meeting
2. Create 1 user and add him to both meetings. 
3. Archive one meeting
4. Go to the participant list of the active meeting and delete the user from there

Expected result: The user itself is not deleted, but only removed from the meeting, since he is also part of an archived meeting.

**Comment by luisa-beerboom** [comment]
Can't replicate
