### ISSUE TITLE
enhance state extensions

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2529]
In a motion: If motions or committees are extended to a state the same motion and committee can ba added several times
Example:
![board board](https://github.com/OpenSlides/openslides-client/assets/69210919/f7cdbd2f-2080-4d0d-96f5-2a210dc36761)

**How to recreate:**

1. navigate into a motion
2. start to extend something to the state
3. add motion A
4. add motion A again
5. save
6. the extension will have motion A as extensions two times

**wanted behaviour:**
each motion and committee should only be addable ONCE per motion

**Comment by jsangmeister** [comment]
There's no harm in being able to repeatedly adding motions, so we currently won't implement this.
