### ISSUE TITLE
Fix follow recommendation in motion blocks

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2530]
if we follow the recommendation in a motion block but one of the motions with recommendation is already at an end state (e.g. angenommen) then the Error: Fehler: State '877' is not in next or previous states of the state '877'.

**how to recreate:**

1. create a motion block 
2. put at least ttwo motions in this motion block
3. set motion A onto an end state (e.g. angenommen) and set a recommendation 
4. set motion b's recommendation 
5. try the checkmakrs/"Follow recommendation for all motions" 
6. the error is thrown

**wanted behaviour:** 
Even if a recommendation is set for a motion, if this motion is in an endstate, the recommendation should not try to be realized

**Comment by jsangmeister** [comment]
The client should prevent this error. For all selected motions it should check whether the recommendation is in the next or previous states of the motion's state. If that's not the case, a snackbar should be opened with an error message indicating that the recommendation of the motion could not be followed. If the motion's state is already the recommendation, a specific message for that should be output. For all other motions, the request should be sent to the backend, which should succeed without error.

**Comment by emanuelschuetze** [comment]
done in #2613

**Comment by jsangmeister** [comment]
Motions that could not follow their recommendation are now silently ignored, aren't they? Is this intended? Because the description we came up with in the coordination meeting said to raise a warning snackbar.

**Comment by emanuelschuetze** [comment]
> Is this intended? 
Yes, it is intended.
