### ISSUE TITLE
Amendments > Categories: Assignment of identical identifiers not possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2546]
**Description:** If a user wants to create a new categorie with a prefix that already exists, he cannot create it. The option to save it is grayed out. Unlike OpenSlides 3, OpenSlides 4 blocks the creation of identical prefixes. 

Additional information: To avoid this problem, users find a workaround which causes other problems: To use identical prefixes, spaces are inserted after a prefix. This causes further problems. 

**Example:**
![Screenshot_20230724_093627](https://github.com/OpenSlides/openslides-client/assets/105491030/3e791ce9-5735-4b2f-aa72-2b7d9f028418)

**Reproduction:**
1. open a meeting
2. open motions
3. open the three-dot-menu > choose categories
4. create a new categorie with prefix A and description XYZ -> create an additional categorie with prefix A and description bcv. 

**What should happen:**
It should be possible to create categories with identical prefixes. This would allow users to structure the motions more individual.

**Comment by jsangmeister** [comment]
This was only implemented a few months ago: https://github.com/OpenSlides/openslides-backend/issues/1612. It's not efficient to change the requirements this much. Are you sure this is needed?

**Comment by jsangmeister** [comment]
tracked in https://github.com/OpenSlides/openslides-client/issues/2551
