### ISSUE TITLE
High usage of 'operator' although operator is not ready

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#255]
The first time the client loads (and staying signed in on any(?) page) the console logs a huge amount (~650) of `operator not ready'-warnings. This leads to freezing of the console for few seconds.

**Comment by FinnStutzenstein** [comment]
What triggers them? It seems that some UI is already loaded, but the operator not ready?

**Comment by GabrielInTheWorld** [comment]
> What triggers them? It seems that some UI is already loaded, but the operator not ready?

Yes. It seems, that reloading while staying on a `list-view-table` causes high querying of `operator.hasPerms` (because of the projector-button).
