### ISSUE TITLE
Prevent Error messages in motion > multi select > set submitters

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2566]
**Description:**
In motions (amendments) > multi select > set submitters: in some constellations errors are thrown if submitters are addded or removed, and the action of adding is not finished

**How to recreate:**
motions/amendments > multiselect  > set submitters 
1. if a submitter is added who already is a submitter in one of the motions/amendments an error occurs.
2. if a submitter is removed who is not a submitter of any of the motions/amendments an error occurs.

**Wanted behaviour:** 
1.  if someone tries to add a user as a submitter who is already a submitter, the wanted state is already reached: no error should be thrown, the adding for the affected submitter and the affected motions/amendments should be skipped, and the rest should be finished
2. if someone tries to remove a user as  a submitter who is not a submitter, the wanted state is already reached: no error should be thrown, the removal for the affected submitter and the affected motions/amendments should be skipped, and the rest action should be finished

**Comment by reiterl** [comment]
I found three possible problems:
- empty actions leads to error
- add a user which already is submitter leads to unique error
- remove a user which is not a submitter leads to an missing error
Also I needed to update the motions, so no longer old data is used.
