### ISSUE TITLE
Prevent Error messages in Participants > multi select > add/remove group

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2569]
**Description:**
In participants > multi select > add/remove group: if a submitter is added to a group they are already a part of an error is thrown and the action is interrupted

**How to recreate:**
1 participants > multiselect 
2. select two participants who are in different groups (e.g. participant A: admin, participant B: delegate)
3. > add/remove group
4. select a group one of them is a part of (e.g. gelegate)
5. try to add this group
6. error is thrown and participant A and B stay in the groups they were before (nothing was added)

**Wanted behaviour:** 
If a participant is added to a group they are already a part of: no error should be thrown, the adding of the already existing group should be skipped and the rest of the action should be finished

**Comment by rrenkert** [comment]
fixed by #2813
