### ISSUE TITLE
Fix list of speaker bugs

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2577]
This is a list of the issues found in the speaker list while changing group rules.
The described issues potentially have nothing to do with each other and own issues need to be created for them

- if  a participant is on the LoS but is not allowed to put themselves onto the list, then they cannot remove themselves from the list 
- same issue as above with PoO
- (while a participant has a LoS opened):
   -  can_put_themselves_onto_LoS needs to be deactivated simulateneously with can_see or needs to be deactivated to begin with
   - after can_see is deactivated Openslides presents a  "You are not supposed to be here..."-page
   - this page should not be shown IF the User is on the LoS themselves! 

**Wanted behaviour:**
A user should always be able to remove themselves from a LoS independent from LoS can_see and can_put_themselves_onto_list

**Comment by emanuelschuetze** [comment]
as discussed: won't fix
