### ISSUE TITLE
[RTF] Fix motion/new motion if user did not preload participants

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2578]
**Description:**
While the participants are not loaded: if a motion with a submitter is opened the mat-chip with the submitter name is empty and the console throws errors.

**Recreation:**
1. open one session with a user (B) who is not allowed to see participants, but is allowed to see motions
2. empty the cache of B (to have the participants NOT preloaded)
3. navigate into one motion with a submitter
4. the submitter mat-chip is displayed but empty and the console throws errors

A user who is not allowed to see the participants and therefore can never load the participants should never be able to see the submitters abd should always have errors in the console

**Wanted behaviour:**
The submitters should always be displayed for users who are allowed to see the motions (to which the submitters belong)

**Comment by bastianjoel** [comment]
Cannot reproduce
