### ISSUE TITLE
Hide Motion or election options in chronik

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2582]
**Description:**
If a participant (not superadmin) is allowed to see the chronik, then they are able to choose between two modules: Election and motions.
Which module they can choose is independent from their ability to see motions/elections.
If they are not actually allowed to see motions or elections then they cannot see/choose any motion/election for the chronik. 

**Enhancement:**
If a participant is allowed to see the chronik but is not allowed to see motions, they should not be able to choose the module motions
same with elections

**Comment by emanuelschuetze** [comment]
needs clean-up for chronic

**Comment by bastianjoel** [comment]
We updated the chronic to only be available to superadmins. For that reason I think this is obsolete now.
