### ISSUE TITLE
Block participants from entering a tag-page 

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2584]
**Description:** 
If a participant is allowed to see the motions, then they are not redirected to an error page if they try to enter the tag page via the adress bar. 
The page shows the tag-detail page but is not allowing the user to actually edit the tags.

**Wanted behaviour:** 
The participant should be redirected away from this page if they are not allowed to manage the tags

Both views are identical:
![motion-tags](https://github.com/OpenSlides/openslides-client/assets/69210919/81e87b09-3417-40f0-902e-13bb8cc4fc99)

**Comment by emanuelschuetze** [comment]
confirmed

**Comment by reiterl** [comment]
The problem seems to be missing permission in the route file. I tried to fix it.
