### ISSUE TITLE
Enhance download files function

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2586]
**Description:**
If _download folder_ is selected not everything is downloaded.

**Current behaviour:**
1. If  _download folder_ is selected only files are downloaded and no folders and the items in the folder
2. If only a folder is selected in multi-select and downloaded, then an empty zip-file is downloaded

**Wanted behaviour:**
_download folder_ should download every available file and folder.
if a folder is specifically selected and then downloaded the folder and it's content should actually be downloaded

**Comment by rrenkert** [comment]
We need a limit of max zip size. The media service should handle creating the zip file.
