### ISSUE TITLE
Fix behaviour when projector is deleted

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2587]
**Description:**
If a projector is deleted while in the projector-detail-view the user stays in the detail view of the deleted projector.

**Recreation:**
1. create a new projector
2. navigate into the detail view of this projector
3. delete the projector
4. you stay in the detail view
5. some elements (e.g. start/stop of the countdowns or countdown names) can still be manipulated other actions (e.g. zoom in/out) are throwning errors

**Wanted behaviour:**
If a projector is deleted while in the projector detail view the user should be automatically navigated into the main projector view. 
The same wanted action already happens when a motion is deleted.

**Comment by emanuelschuetze** [comment]
confirmed
