### ISSUE TITLE
Fix "reset to factory defaults" in settings

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2589]
**Description:**
In a meeting: it is not possible to restore the factory settings for some of the setting pages (main settings page, general settings page and motions settings page)

**Wanted behaviour:**
it should be possible to restore the factory settings

**Comment by emanuelschuetze** [comment]
confirmed for motions settings -> erro "Fehler: data.motions_default_workflow_id must be bigger than or equal to 1"

**Comment by Elblinator** [comment]
additionally custom translation -> reset should delete all custom translations
