### ISSUE TITLE
Fix display of "Name of recommender of statue amendments"

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2593]
**Description:**
Even if a _Name of recommender of statue amendments_ is selected this field is never displayed in a status amendment

**How to recreate:**
1. in a meeting > settings > motions -> decide for a name of recommender of statue amendments and activate  statue amendments
2. motions > three dot menu > statue > create new statue paragraph
3. motions > new motion > tick _Statute amendment_ ->select the staute and create amendment
4. navigate into the statue amendment
5. the name of recommende block is missing

settings: 
![settings](https://github.com/OpenSlides/openslides-client/assets/69210919/ee6b931f-64c2-4fa1-8b64-ca85882cd2c8)

statue amendments with these settings:
![statueamendment](https://github.com/OpenSlides/openslides-client/assets/69210919/870de5d0-7f2f-4db3-808b-3798632a6272)

**Wanted behaviour:**
the name of recommender should be displayed and work like the _name of recommender_

**Comment by MSoeb** [comment]
Note: Set it to low, because we need to discuss further status of statute amendments.

**Comment by emanuelschuetze** [comment]
You created a normal amendment - not a statut amendment. But anyway - we want to remove the whole feature with all configs.
