### ISSUE TITLE
[RTF] Do not request non existing Fields

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#2600]
Currently, the Client is requesting fields from the autoupdate-service, that do not exist. For example:

https://github.com/OpenSlides/openslides-client/blob/314a96163fbb731a734ec660430578dc3b84f947/client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts#L58

https://github.com/OpenSlides/openslides-client/blob/314a96163fbb731a734ec660430578dc3b84f947/client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts#L78

https://github.com/OpenSlides/openslides-client/blob/314a96163fbb731a734ec660430578dc3b84f947/client/src/app/site/pages/organization/pages/dashboard/dashboard.subscription.ts#L15

There are probably many more. 

The autoupdate-service will handle unknown fields as invalid fields in the rtf-branch as soon as this PR is merged: https://github.com/OpenSlides/openslides-autoupdate-service/pull/738

There are two ways we could handle this. The autoupate-service could ignore invalid fields (and unknown fields). Or you could remove the non existing fields from the client requests.

I would prefer that the client would not request non existing fields, since there is no reason to request a field, that does not exist. I would say, that requesting a non existing field is always a bug. If the autoupdate-service rejects requests with unknown fields, it will probably help to find this bugs. But I can understand, if you don't want to check all subscriptions now.

Please tell me how you want to solve this.

I labeled this as high, because it blockes the [PR in the autoupdate-service](https://github.com/OpenSlides/openslides-autoupdate-service/pull/738) from being merged.

**Comment by jsangmeister** [comment]
I agree, we should remove these fields from the subscriptions
