### ISSUE TITLE
expand cross-reference links in motions

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2604]
**Description:** 
Cross-referencing between motions only works in the motion that was referenced. The original motion contains only a textual reference, but no link. 

**Image - motion with reference:**
![Screenshot_20230808_135747](https://github.com/OpenSlides/openslides-client/assets/105491030/8e729680-fb5a-4c36-a10f-9bc7344fdf01)

**Referenced motion with link to other motion:**
![Screenshot_20230808_135808](https://github.com/OpenSlides/openslides-client/assets/105491030/863d0229-80f9-4006-896e-b428817c1758)

**Reproduction:**
1. open a meeting
2. open motions > create two motions with complex workflow
3. open motions > three-dot-menu > workflows > open complex workflow > activate setting Show recommendation extension field for state Vertagung/vertagt
4. open settings > motions > add under Name of recommender ABK > save
5. head back to motions > open first motion > open in meta data the recommendation field, choose state Vertagung, click on the pen and select the other motion. Now the state should be Vertagt with motion reference (like in image 1)
6. open the other motion and check the meta data. There should be a link to the other motion (image 2)

**What should happen:**
The original motion (see image 1.) should get a link to the referenced motion under recommendation state. If more than one motion is referenced, then the listing of the motions should be separated with a dot.

**Comment by jsangmeister** [comment]
Note: The relations `state_extension_reference_ids` and `recommendation_extension_reference_ids` can be used for this (the reverse relations to the ones used in the second image, `referenced_in_motion_state_extension_ids` and `referenced_in_motion_recommendation_extension_ids`).
