### ISSUE TITLE
LoS: Moving speaker bug

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2622]
**Description:** If a user moves a speaker in the list of speakers while a delegate adds themselves to the list, an UI error occurs.

**Example of broken UI**
![Screenshot_20230811_141444](https://github.com/OpenSlides/openslides-client/assets/105491030/a6c73b0d-f159-46f2-bc31-f6a3bb4e550d)

**Reproduction:**
precondition: an admin and a user with permission to add himself to the LoS is needed. Also a second device is needed.
1. open the meeting as superadmin
2. open the agenda > create a topic
3. open participants > create four participants as delegates
4. open the autopilot > add three of them to the LoS
5. Open on SECOND device the meeting as a delegate
6. open autopilot
7. Now you need both devices: On first devices as admin open Autopilot, grab a delegate in the LoS and move him to another position. IMPORTANT - Hold this! - Switch to the other device and add the delegate to the LoS. - Switch back to devices one: Move the position of the delegate and release it. -> UI bug.

**What should happen:**
The interaction between adding a user to the LoS and moving a user in the LoS should not result in an UI bug.

**Comment by luisa-beerboom** [comment]
I took a look at this and it seems that the misplaced element has a transform3D element style, that I guess comes from the cdkDropList which is being used. I couldn't tell exactly why this is happening.
Also it seems that the problem primarily appears when one creates a weight distribution with a gap and then tries to exchange the items on the edges of that gap (i.e. put 4 items (A, B, C, D in that order) into the list, remove C, reload, hold D, move it to the second position, re-add C, drop D => B and D should overlap)
