### ISSUE TITLE
Updating Participant data via csv import won't work

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2625]
**Description:** The meeting user import has a bug when updating meeting specific data. The data won't be updated. The existing participant is recognized correctly but it will not be updated. 

**Reproduction:**
Precondition: At least one existing participant in a meeting is needed.
1. open a meeting
2. open participants > open three-dot-menu > export current user list as csv 
3. open the csv file an > edit some meeting specific data
4. head back to OpenSlides and open participants > open three-dot-menu > choose import
5. import the selected edited file

**What should happen:**
Updating meeting specific user data should be possible csv reimport of the current participant list.

**Comment by rrenkert** [comment]
Should be solved by https://github.com/OpenSlides/openslides-backend/issues/1714

**Comment by reiterl** [comment]
I tested this issue using the instructions, I changed last name and groups, and it worked, so far.
There have been some changes to this import.  So I assume, that this issue is already fixed and I close this issue.
