### ISSUE TITLE
Account deletion error if user is part of election

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2635]
**Description:** If an ccount is part of an election which is done, the account can't be deleted from the instance. An error message appears which refers to the poll. 

**error message:** 
![Screenshot_20230814_152907](https://github.com/OpenSlides/openslides-client/assets/105491030/e94e34d3-4230-4a32-bc61-f54c317dbc8b)

**Reproduction:**
1. open a meeting
2. open participants > create a new user
4. open elections > create a new election > add new user to candidates > create ballot as list election > do voting > publish it
5. head back to the organization level 
6. open accounts > try to delete the new user account

**What should happen:**
It should be possible to delete an account even if the account is linked with an election. After the deletion process is done, the ballot should include a "deleted user" instead of the user name. The user should not silently be deleted without an anonymous reference. This is needed as a protocol.

**Comment by jsangmeister** [comment]
Needs backend changes, see https://github.com/OpenSlides/openslides-backend/issues/1869

**Comment by luisa-beerboom** [comment]
With the backend this works now, but if the replication instructions are precisely followed, the operator now gets `this.poll is null` TypeErrors in the console right after the account deletion (i.e. while still on the account list).

Doesn't actually seem to break anything (the poll itself is completely fine), but we should probably take a look at it.

**Comment by luisa-beerboom** [comment]
Probably an issue with the user deletion dialog

**Comment by luisa-beerboom** [comment]
I tried it out again and the error message is gone, final fix might have occurred #2723 or #2640 

I'm closing this now
