### ISSUE TITLE
Fix is_present Checkbox

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2644]
**Current behaviour:**
If the present checkbox is activated the activation animation appears tw o times

**Recreation:**
1. navigate to participants
2. activate the present checkbox
3. animation should be there twice

**Wanted behaviour:**
the activation animation should only be displayed once

**Comment by reiterl** [comment]
I can reproduce it. This issue is still a thing. But I have no idea, why.

**Comment by bastianjoel** [comment]
@Elblinator Please check if this issue still exists with the material update
