### ISSUE TITLE
Change of wording and appearance of Dialog

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2656]
**Current appearance of delete dialog:** 
![delete_dialog](https://github.com/OpenSlides/openslides-client/assets/69210919/007d48fb-adb1-446a-92b7-6ce5b04f3659)

**Wanted changes:**
- the sentence "These accounts will be removed [...]" should be changed to "These participants will be removed [...]"
- if some participants are removed AND some accounts are deleted then the sentence "These acocunts will be deleted:" should have a margin to the last item above the sentence

**Example appearance of change delete dialog:**
![new_delete_dialog](https://github.com/OpenSlides/openslides-client/assets/69210919/3cec8881-d97f-4a87-8f15-8c74d59cadb5)

**Comment by jsangmeister** [comment]
Also:
- Use 2 different, independently scrollable lists which both take half of the vertical space.
- If one is empty, it can be completely hidden.
- The "deletion" list should be moved to the top and the "removal" list to the bottom, since deletion is the more significant change.
