### ISSUE TITLE
Prevent too long structure level title 

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2677]
**Current behaviour:** 
While counting completed requests to speak, if the structure level is too long it will create an additional scrollbar 

**additional mini scroolbar:**
![count_speaker](https://github.com/OpenSlides/openslides-client/assets/69210919/4d1ebf64-412e-4ee3-89bf-d931474a760f)

**Recreation:**
1. add a long structure title to a participant 
2. put the participant on a LoS, start and stop the contribution
3. navigate to top right corner > legal notice
4. activate "count complete request to speak"

**Wanted behaviour:**
If a structure title is too long the column width of the structure title should be widened, and the two other widths should be shrunken.
If the structure title  is still to long to be displayed without a scrollbar then it should be ellipsed before the scrollbar appears

**Comment by luisa-beerboom** [comment]
Given that the other columns seem to only contain numbers and time-strings, their content shouldn't really grow beyond a certain length.
We could therefore just make the other two columns thinner by default.
