### ISSUE TITLE
Prevent Error for motions multiselect

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2692]
**Current behaviour/Reproduction:**
1. Navigate to Motions
2. create a new motion 
3. start multiselect and select the new motion
4. chose set favourite > set as not favourite
5. Error thrown, The error is only thrown for motion which were not favourite beforehand

**Wanted behaviour:**
No Error should be thorwn and the motion should stay not favourite

**Comment by rrenkert** [comment]
The Error is: `Can't create personal note without star or note.`

**Comment by reiterl** [comment]
I can reproduce the problem.
In motion-multiselect.service.ts bulkSetFavorite uses setPersonalNote. If no personal note exists, it tries to create a personal note with star = false. I tried to filter the motions, but the motion.getPersonalNote() method, which is needed for the filtering isn't reliable in this context.

**Comment by reiterl** [comment]
I will continue here with @luisa-beerboom tomorrow.
