### ISSUE TITLE
Fix forward motions (multiselect)

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2694]
**Current behaviour:**
If motions are forwarded then following error is thrown:
_Error talking to autoupdate service_

**Reproduction:**
1. create two meetings , one meeting needs to be allowed to forward motions to the other
2. go into the meeting which can forward
3. create a motion 
4. activate multiselect > select the reated motion > forward it
5. error is thrown

**Wanted behaviour:** 
the motion should be forwarded

**Comment by rrenkert** [comment]
Can not reproduce in 4.0.8-staging-20230901-3e362fe.
