### ISSUE TITLE
Groups not filtered in meeting

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#2699]
When adding existing participants to a meeting all groups of that user are displayed in the group select. Also when accessing the groups edit page after that all these groups are displayed there.

**Comment by Elblinator** [comment]
After the participant is added all potential groups from every meeting of this participant/account are displayed, for every participant.
If the page is reloaded then the correct groups are displayed again

**Comment by rrenkert** [comment]
Duplicate of #2736.
