### ISSUE TITLE
Add option to Re-add last PoO

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2715]
**Current behaviour:**
In a LoS it is currently possible to re-add last Speakers

**Wanted behaviour:**
this option should be extended to last speakers from  a PoO. 
The description should stay the same as it was before the contribution as finished (it should look like a normal PoO)
The tooltip should change from "Re-add last speaker" to "Re-add last contribution"

**Comment by bastianjoel** [comment]
This requires a backend change. Currently the backend is responding with `The last speaker is a point of order speaker and cannot be re-added.` when trying to readd a point of order speaker.
