### ISSUE TITLE
Fix flickering Arrows/Number(Bezeichner) in motion-detail

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2722]
**Current behaviour:** 
If you switch from one motion to the next via the arrows in the top right are then it can happen that they flicker and need quite some time to reappear

**Reproduction:**
1. create 10 motions everyone long (>1000 words)
2. navigate to the first motion
3. reload 
4. navigate to the next motion via arrows
5. the flickering should at least be very tiny, the flickering becomes more dominant the more data there is to load

**Wanted behaviour:** 
the arrows should not flicker

**Comment by bastianjoel** [comment]
Cannot replicate this anymore. Might has been fixed with #2749.
