### ISSUE TITLE
Adjust projector view to new detail-view

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2729]
The detail views from Motion, Election and Agenda got changed (#2728) when they are now projected the projection needs to adjust accordingly:

**Description from the other Issue:**
What was changed:
- every title should stay how they are (relevant for Motion, Agenda and Election)
- H1 should not have primary or accent colours, but should be black/greyish like the rest of the text (UPDATE: font-weight: 400)
- H2 should have font-weight: ??? -> was marked as fine in last discussion; Open new issue please.
- H3 should have font-weight: 600
- H4 should have font-weight: 600 and font size: 1 em
- H5 should be kursive and have font-size: 1 em
- H6 should not be kursive or bold, and font-size: 1 em

waiting for https://github.com/OpenSlides/openslides-client/issues/2728

UPDATE 2024-07-18 (ES):
Needs discussion with @Eich-hoernchen

**Comment by Elblinator** [comment]
waiting for https://github.com/OpenSlides/openslides-client/issues/2728

**Comment by rrenkert** [comment]
Please write change requests in comments and do not edit the initial message to change the requirements if a PR is already opened.
