### ISSUE TITLE
Fix linter warnings

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2733]
When executing the `make run-cleanup` command, 162 linting warnings are reported for me. We should either fix them or supress them if we are sure that they are irrelevant to us. Most of them should be easy, like the `no-unused-var` errors about `_` - we can just add an exception for the variable name `_` in the `package.json`.

**Comment by bastianjoel** [comment]
This is intended and was already mentioned in #2279. The warnings should stay active to prevent adding more of these issues. In the future all of these should be changed to error.  

`no-unused-var` is indeed trivial to fix. But there are also other rules which aren't.

**Comment by jsangmeister** [comment]
Mmh, okay. I don't think the prevention will work, though -  as long as they are just warnings, everyone will probably ignore them and especially not even notice when a new one pops up. To save future work, we should probably fix them alltogether soon and then promote them to errors.

**Comment by bastianjoel** [comment]
Normally these warnings should be displayed within the IDE directly in the editor. Therefore I would not say that one would not notice them.

**Comment by bastianjoel** [comment]
Reopening as there are still warnings.

**Comment by Elblinator** [comment]
this was partically fixed in #3035 

#3065 added new linter warnings
