### ISSUE TITLE
Fix missing autoupdate (when group changes in participant list)

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2743]
**Current behaviour:**
If you remove your admin status via the edit detail dialog (in the participant-list click on the group names of your participant), the dialog opens correctly, but afterwards you can still open this dialog but not change anything in it.

**Recreation:**
in a meeting: 
1. login as a (normal/only) meeting-admin
2. go into the participant-list
3.  via the edit dialog remove your own admin-right
4. open the dialog again (correct behaviour would be  that you cannot open it again)

**Wanted behaviour:**
the edit detail dialog should only open if you are allowed to manage participants

**Comment by luisa-beerboom** [comment]
Can't replicate

**Comment by Elblinator** [comment]
Cannot be reproduced in newest version (build 20230915)

Will close Issue
