### ISSUE TITLE
Fix wrong display of non-active-account icon

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2744]
**Current behaviour:**
If you remove yourself as an admin via the edit detail dialog then some participants (potentially nonsuper/orga/account-admins) have the icon for not-active accounts

**Recreation:**
in a meeting: 
1. login as a (normal/only) meeting-admin
2. go into the participant-list
3.  via the edit dialog remove your own admin-right
4. the icon for not-active accounts/participants is displayed for some participants

**Wanted behaviour:**
The icons for any participants should not change if you stop being an admin

**Comment by luisa-beerboom** [comment]
Can't replicate, can you look if there's any other notable things about the participants involved?

**Comment by Elblinator** [comment]
I cannot reproduce it in the newest version 

I will close the issue.
