### ISSUE TITLE
Thrown correct Error if motion  in wrong status is forwarded

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2764]
Edited: 13.02.24

**Current behaviour:**
Even if a motion is in a status which cannot be forwarded, you can "try" to forward it via multi-select.
This action will result in an error:
```Error talking to autoupdate service```

**Reproduction:**
1. create two meetings , one meeting needs to be allowed to forward motions to the other
2. go into the meeting which can forward
3. create a motion
4. make sure that this motion is not in a status which can be forwarded
5. activate multiselect > select the related motion > forward it
6. error is thrown

**Wanted behaviour:**
If a motion which is not allowed to be forwarded is selected via multi-select, then the forwarding option should throw a **correct** error, aka the wrong autoupdate error message should be prevented

**Comment by luisa-beerboom** [comment]
This would require calculating the current forwarding situation at every turn, which may not be the most efficient use of processing power, especially if it is done for other multiselect options as well.

@rrenkert is this really necessary?

I would be more inclined to say that we should take a look at the reason for the strange error message

**Comment by jsangmeister** [comment]
I think the processing power is actually not that high: If I see it correctly, the only thing differing from motion to motion that can allow or disallow forwarding is the motion's state's `allow_motion_forwarding`. That can just be requested together with the motion list and then it's just a simple iteration. Or am I missing something?

**Comment by luisa-beerboom** [comment]
It's a simple iteration that has got to take place at the very least whenever the selection changes and whenever there is an autoupdate while there is a selection. Especially if  we expand this type of behaviour to other buttons and someone (even accidentally) selects "select all" with longer motion lists that could potentially be a lot.

My key point however was:
As standard we are currently not really doing this check-each-model type of permission check for our multiselect functions. We do it for single-actions, but not lists. In those cases we are instead relying on the backend to send an error if the data is invalid. That has the benefit that we don't need to iterate over a potentially giant list of models multiple times with every update.
If we start doing this here, I'm afraid there'll be calls to do it with other actions and lists as well.
In the past we've already had troubles with performance when certain end-users with weak devices open extremely long lists, I fear this may potentially add onto that.

**Comment by jsangmeister** [comment]
I'm not saying we should do it, I was only pointing out how it could be done :) Some solution should be found for the error either way.

Another suggestion: In https://github.com/OpenSlides/openslides-client/issues/2530 we filtered those elements out which would have triggered an error. Maybe this could also be a solution here, as then, you only need to iterate the list once before sending it instead of on every autoupdate.

**Comment by jsangmeister** [comment]
> Another suggestion: In #2530 we filtered those elements out which would have triggered an error. Maybe this could also be a solution here, as then, you only need to iterate the list once before sending it instead of on every autoupdate.

Looked into the code and saw that this is exactly what is done (see https://github.com/OpenSlides/openslides-client/pull/3275), it only fails if no eligible motions were selected. So I opted to keep this solution and only fixed the error.
