### ISSUE TITLE
Mediafile List: set images and logo not indicated

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#278]
The singleMediafileMenu cannot indicate if files or fonts are currently used as web_header, pdf_header, regular, etc.

The function `used_as_logo_in_meeting_id` and `used_as_font_in_meeting_id` in mediafile.ts never return anything.
https://github.com/OpenSlides/openslides-client/blob/f06e59901d94907517042c2d1a8df087db70fe82/client/src/app/shared/models/mediafiles/mediafile.ts#L42-L48

the correct follows should be set over the repo `LOGO_FONT_VALUES: AdditionalField[]`
https://github.com/OpenSlides/openslides-client/blob/f06e59901d94907517042c2d1a8df087db70fe82/client/src/app/core/repositories/mediafiles/mediafile-repository.service.ts#L16-L23

**Comment by GabrielInTheWorld** [comment]
I have noticed, that the used functions to indicate if an image or font is used as web_header or pdf_header or ... in the html-template was wrong.
The necessary autoupdate-requests are correct. It seems that the autoupdate-service does not send the necessary and requested fields for mediafiles. See also [openslides-autoupdate-service#228](https://github.com/OpenSlides/openslides-autoupdate-service/issues/228).
