### ISSUE TITLE
Client relation handling doesn't do back-relations anymore

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2789]
It used to be that if one followed a relation field in a subscription, the contra-relation would automatically be filled for the other viewModel as well.

I.e. if one subscribed to a meeting and followed the motion_ids, the `ViewMeeting` would have a field `motions` with all of the corresponding `ViewMotion`s and the corresponding `ViewMotion`s would all have a field `meeting` that was filled with the `ViewMeeting` in question.

It seems like that has somehow stopped happening. 
There have recently been multiple bugs that were caused because a subscription followed a field, but the counter-relation wasn't named anywhere in the fieldset, causing the connection to either not be built, or only be built one-way (I'm not quite sure which).
An example of this would be #2710 which could not be fixed without adding the back-relation for the meeting-users `user_id` field into the fieldset of the follow.

**Comment by bastianjoel** [comment]
I was not able to find anything that looks like doing something like that. I mainly looked for this in the datastore related services and model request handling.
