### ISSUE TITLE
Wrong line numbers in amendment after adding change recommendation

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2820]
How to reproduce:
1. create motion with multiple lines
2. create amendment which changes some of the later lines (the amendment detail view must not start with line number 1)
3. create change recommendation to any line in the amendment
4. delete change recommendation -> the line number in the amendment reset and start at 1

If you try to create a new change recommendation afterwards, the displayed line numbers are used and the lines from the original motion are used, which is especially confusing.

**Comment by Elblinator** [comment]
Step by step guide:
1. created a new motion with several (in my case 7) lines and paragraphs (every line is a paragraph
2. created an amendment which changed 4 lines  (first, third, fourth, fifth) 
3. created a change request for Line 4 
4. reloaded page (see #2945  for reasons for reload)
5. line numbers are wrong:
![010 A](https://github.com/OpenSlides/openslides-client/assets/69210919/30730ad7-4dda-4680-bf44-0fcc99a80896)

after deleting the change recommendation and reloading the page the correct lines are displayed again

**Comment by Elblinator** [comment]
the issue is moved to a meta-issue #2946 
This issue will be closed
