### ISSUE TITLE
Client loses connection to ICC service after some time

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#2836]
When in a meeting, the client does not receive messages from the ICC service anymore. This can be tested, e.g., by opening a meeting in two windows with two different users and waiting some time (a few minutes?). Then, open the C4 dialog and search for players in both windows. Both windows will not receive the invitation and will continue searching.

Note that the ICC service is broken in the current demo alltogether, so this has to be tested locally or on nightly.

**Comment by bastianjoel** [comment]
The issue here seems to be that icc service connections do not get reopened on failure. 
To replicate this issue it is also possible to just restart the icc service.
