### ISSUE TITLE
Prevent vote weight of 0

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2865]
**Description:** Setting the vote weight in a meeting to value 0 is not possible. It can be changed to 0, but the value will not be saved. Also it is not possible to import a user in a meeting with the vote weight value set to 0.

**Reproduction:**
1. open a meeting
2. open _Settings_ > _Participants_ > activate option _Activate vote weight_
3. open Participants: create a new user, change the vote weight to value 0 and save it. -> value is not saved
4. open Participants > Three-Dot-Menu > Import: Import a new generated user with a vote weight set to 0 and check if it is correctly imported. 

**Note:** Changing the value to 0 works, if the user can change data on organisation level in Accounts. If the default value of an account has changed to 0, it is possible inside a meeting to change the value to another number and back to 0 again. 

**What should happen:**
- [ ] Accounts which can administrate meetings should be able to set the vote weight value to 0.
- [ ] user import: Import should work with the vote weight value set to 0.

**Comment by jsangmeister** [comment]
As discussed: vote weight of 0 should be forbidden, see https://github.com/OpenSlides/openslides-backend/issues/1926. This should be consistently implement in all views.

**Comment by reiterl** [comment]
Prevent Zero in new-account dialog is done in #2911
