### ISSUE TITLE
Motions: Filter stays active after meeting switch

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2870]
**Description:** Selected filters in motions stays active after switching to another meeting. The selection seems to be set to  global default value over all accessible meetings. 

**Reproduction:**
Precondition: At least two meetings with the same user base.
1. open meeting A > motions > set a filter
2. head back to organisation level and open the other meeting B > motions. The selected filter is still active.

**What should happen:**
The selected filter should only be active inside the meeting where it is set and not global in all other meetings.

**Comment by rrenkert** [comment]
Also have a look at sorting.

**Comment by reiterl** [comment]
search entry also stays the same after a meeting switch.

**Comment by reiterl** [comment]
Search entry seems to be handled differently.
