### ISSUE TITLE
[Imports] Implement motion import via backend

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2871]
See OpenSlides/openslides-backend#1713

The motion export should be extended to allow for exports in correct backend `motion.import` format.
We want to keep the old format as well for the sake of customers who were using it for some purpose. Especially for the users, the proposal was to keep the old functionality and add username columns.

There was also a discussion whether OpenSlides should recognize if the user tries to import a previously exported amendment and remove it from the payload pre-emptively. For that purpose we want to export if the motion is an amendment (see description in Wiki) as a new boolean column `motion_amendment` in the export.

**Comment by Elblinator** [comment]
https://github.com/OpenSlides/openslides-client/pull/3042#issuecomment-2485253624
> The motion import will not be developed further and no bugs will be fixed
