### ISSUE TITLE
Fix display of motion block list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2876]
**Current behaviour:**
If a motion block list is displayed the displayed sequential numbers are wrong (displayed are not the sequential numbers but probably the internal ids) and there is a missing space in front of "sequential number"

**Reproduction:**
in a meeting:
1. create a motion block 
2. create a motion and put the motion into the motion block
3. look at the motion block 
(Hint if you have only one meeting with only one motion then it is possible that the sequential number and internal id are identical, to prevent that create more motions in other meetings) 

**displayed motion in the motion-block (please note the missing space before "sequential number"):**
![motion-block](https://github.com/OpenSlides/openslides-client/assets/69210919/48e66838-6fff-497a-a3ca-08d59c7e3745)

**actual sequential number of the motion:**
![motion](https://github.com/OpenSlides/openslides-client/assets/69210919/01e5550e-b3a8-480b-a7c7-ec84025420ad)

**Wanted behaviour:**
1. The correct sequential number should be displayed 
2. there should be a space added before "sequential number"

**Comment by reiterl** [comment]
I can reproduce the problem.
