### ISSUE TITLE
Missing Autoupdate in call list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2892]
**Current behaviour:**
If the call list is changed in motions > multi-select then the call list is not automatically updated in the call-list

**Reproduction:**
To be able to test you need to wait for or checkout #2861 
1. create two motions 
2. open a second tab with the call-list 
3. change the order of the call-list via multi-select in the motion-list-view
4. look at the tab with the call-list
5. the call list is not updated automatically 
6. if the page is reloaded then the call-list is up-to-date

**Wanted behaviour:**
the call-list should be automatically up-to-date

**Comment by emanuelschuetze** [comment]
> the call-list should be automatically up-to-date

this is NOT desired. Don't need a fix.
