### ISSUE TITLE
LoS Search Selection: field gets inactive

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2893]
**Description:** #2842 has a small bug. The search field gets inactive after typing a few letters. Without clicking in the field again, the user can't write anymore. 

The requirement is, that the search field should always stay active for typing letters AND, which works in #2842, that the first user could be selected with enter.

**Reproduction:**
1. open a meeting
2. open participants: add some users
3. open agenda: create an item and project it
4. open the autopilot and use the search field in the LoS to add users to the list -> by typing a few letters, the search will get inactive.

**What should happen:**  
The requirement is, that the search field should always stay active for typing letters AND, which works in #2842, that the first user could be selected with enter.

**Comment by bastianjoel** [comment]
I suggest reverting #2842, reopening #2721 and closing this issue as we might need to fix #2842 differently.
