### ISSUE TITLE
Meeting edit view: search field didn't load

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2897]
Description: If a superadmin or organization-admin wants to add an account as a new admin via the meeting dialog, the search field didn't load, if the meeting has other accounts as meeting admins. Only the account list is visible without the search field. 

![Screenshot_20231016_163554](https://github.com/OpenSlides/openslides-client/assets/105491030/02fadf0d-c942-4f6a-82d1-49fb438dbc22)

Reproduction:
1. open committee as superadmin: create a new com. and create a new meeting. Save it.
2. open the meeting edit view again and try to add another user. Search field is missing
3. Hint: Eventually another extra user is required to trigger this. If pos. 2. fails, please add a another user. 

What should happen:
The search field should always appear in the meeting edit view.

**Comment by emanuelschuetze** [comment]
same like #2925
