### ISSUE TITLE
Disable Save button and show hint if email or default vote weight in <new account>/<new participant> is faulty

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2899]
**Current behaviour:**
new account:
If the <new account> mask is opened and a wrong e-mail address or vote weight is put into the field the save button is not disabled and if the new account is saved the error  ```Cannot read properties of undefined (reading '0')``` is displayed but the mask with every input stays on screen
new participant:
If in step 1 or step 3 in the <new  participant> mask a wrong email-address is assigned to the new participant then the save button is not disabled and if pressed the error ```Error: email must be valid email.``` it thrown and the are navigated back to the participant-list (the input for the new participant is being lost)

**Correct input (as far as I understand it):**
Correct vote weight: number >= 0.000001

Correct Email: <word>@<word>.<word>
Description in words: 
A correct mail-address consists out of three strings with to separators:
- a string 
- "@"
- a string
- "."
- a string

**Wanted behaviour:**
If there is a wrong input in these masks then two things should happen:
1. the save button should be disabled
2. the input-field which has the faulty input should get coloured in the warn colour and a text should be displayed unter the line:
   - for a wrong email: "Please enter a valid email address. "
   - for a wrong vote weight: "Please select a vote weight bigger than or equal to zero."

**Comment by reiterl** [comment]
We should use a email validation from Angular or a lib. Email validation is more complex than what @Elblinator  wrote.

**Comment by rrenkert** [comment]
Yes, email validation is more complex but a regex should be enough for the validation we need at this place.

**Comment by reiterl** [comment]
We should use the default Angular Validator here.

**Comment by jsangmeister** [comment]
Vote weight must be at least 0.000001, see https://github.com/OpenSlides/openslides-backend/issues/1926. Updated the description.

**Comment by reiterl** [comment]
Yes, that is right, but this requirement is part of an own client issue.

**Comment by reiterl** [comment]
I have added the default vote weight Validator and error check and have updated the error message.
(To prevent zero)
