### ISSUE TITLE
Login loop after logout

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2906]
**Current behaviour:**
If you logged out and try to login again, then you are stuck in a loading loop for 

**Reproduction:**
1. Login as any person
2. log out 
3. log in with the same account 
5. there is a spinning login button
6. reload the page and you are logged in

**Wanted behaviour:**
The indefinitely long spinning time should be prevented

**Comment by bastianjoel** [comment]
The error does not seem to be related to the login issue

**Comment by bastianjoel** [comment]
This seems to be related to the operator not getting ready. There were already issues regarding this kind of issue (e.g. #1609, #1390). 
After fixing that we might also want to add an integration test for this.

**Comment by bastianjoel** [comment]
This seems to be a race condition within `autoupdate-stream.ts`. 

On logout the client sends the following messages to the shared worker:
1. Individual subscription closes
2. Endpoint update
3. Auth change

It seems that subscriptions do not get correctly closed if the set endpoint or auth change message (not exactly sure which one, maybe both) get sent before the close message was sent.

**Comment by bastianjoel** [comment]
I cannot replicate this anymore.

**Comment by Elblinator** [comment]
I updated the Issue description

**Comment by MSoeb** [comment]
Problem is solved.
