### ISSUE TITLE
Workflows: UI problem with Firefox browser

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2916]
**Description:** If a workflow setting is activated the check box position changes. If the menu is closed and opened again, the check box is correctly set and the settings works. Just a small UI bug.

**Check box (disabled):**
![Screenshot_20231019_135742](https://github.com/OpenSlides/openslides-client/assets/105491030/b82bea2d-6351-4096-b48c-3846bc2248d2)

**Check-box activated:**
![Screenshot_20231019_135837](https://github.com/OpenSlides/openslides-client/assets/105491030/60eeef21-5a0e-4476-8069-91442765dc9b)

**Reproduction:**
0. Use Firefox
1. open a meeting
2. open motions > three-dot-menu > workflows
3. change a setting

**What should happen:**
The check box should stay on it's position during edit.

**Comment by luisa-beerboom** [comment]
Can't replicate

@MSoeb 
Are there some other factors that may take part in this? 
If not please close this

**Comment by reiterl** [comment]
Also cannot replicate. Used FF 115.6.

**Comment by luisa-beerboom** [comment]
@MSoeb ping

**Comment by bastianjoel** [comment]
I am closing this now as we did not receive a response and also the checkbox components got replaced.
