### ISSUE TITLE
Fix "+ create User" action in participant search fields

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2921]
**Current behaviour:**
If you search for a user in a participant search field and the participant is not in the participant-list then it is possible to run into one Error: ```Error: A user with the username <name> already exists```

**Reproduction:**
1. create the account Firstname: xx, Surname xx; automatically will create username: xxxx
2. navigate into a meeting > motion > LoS
3. Search for a participant xxxx
4. you should get the option to "+ create User"
5. if you activate the option the Error is thrown: ```Error: A user with the username xxxx already exists```

**Wanted behaviour:**
1. the input field: `Select or search new speaker ...` should send the whole string as the surname 
    If you have the input `Kim Meier` and create a new user, then the created account should have no first name and the surname `Kim Meier`
2. the User which is created should be inactive
3. after a user is created a snackbar should open which says: "A user with the Surname '<name>' and the username '<username>' was created"

**Comment by reiterl** [comment]
The `createNewSelectedUser` uses the `userRepo.createFromString` function. 
A possible solution is to clean the parsed username in this function and use the backend generate code to set the username. As far as I know, this was the solution, we want to go for.
