### ISSUE TITLE
Prevent white projector when motion switch

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2922]
**Current behaviour:**
If one motion is projected and then another motion is projected there is a 1-2 sec delay where the projector has no text but white space 

**Reproduction:**
in a meeting:
1. create two motions with different titles and texts
2. project one of the motions 
3. open the projector-list
4. now project the other motion
5. there should be a short moment where the projector is completely white

**Wanted behaviour:**
The time to switch the motions should be reduced

**Comment by Elblinator** [comment]
As a first step to enhance the behaviour please look at #2066

**Comment by bastianjoel** [comment]
#2066 has nothing to do with this.
