### ISSUE TITLE
Committee > meeting edit: Account search field is missing in add Administrator field 

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2925]
**Description:** If a superadmin or organization admin wants to add another user as an admin for a meeting in the meeting detail view, the search field for users is missing. Only the Account list is visible. As a superadmin it always happens, as organization-admin it happens sometimes. I can't figure out, why it occurs as orga-admin only sometimes. I hope, that the solution for superadmins can fix the orga-admin issue.

**See Administrator field:**
![Screenshot_20231020_124445](https://github.com/OpenSlides/openslides-client/assets/105491030/c33fc612-c51b-4e5a-8557-6e00909218a4)

**What is actually displayed:**
![Screenshot_20231020_124413](https://github.com/OpenSlides/openslides-client/assets/105491030/6157671e-cedf-44b6-995d-b0ad3e54f606)

**Reproduction as SUPERADMIN:**
1. open an instance
2. open accounts: create two new accounts
3. open committees and create a new committee
4. create a new Meeting and try to add other users as Administrators.

**What should happen:**
The add new administrator field should have a search bar.

**Comment by reiterl** [comment]
I cannot reproduce this. I followed the steps and a search bar is shown.

**Comment by bastianjoel** [comment]
I can reproduce this. The search field is there but seem to be transformed out of view.
