### ISSUE TITLE
Motion-list: Prevent wrong display in motion-list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2927]
**Current behaviour:**
It is possible that the UI of a motion does not load correctly for the motion-list

**Reproduction:**
in a meeting: 
1. create a motion 
2. activate recommendations: 
3. navigate to settings > motions 
4. search for "Name of recommender" and put a string in this field
5. navigate back to the motions
6. the string you used as "Name of recommender" ist the recommendation-field 
7. select something in recommendation 
8. navigate to the motion-block overview 
9. reload page
10. navigate back to the motion-list 
11. UI is wrong
12. reload page in motion-list to get the wanted UI

**wrong UI:**
![002_motion-list-wrong](https://github.com/OpenSlides/openslides-client/assets/69210919/6156b391-490e-47ae-a3a1-fbb9ceae22eb)

**Correct UI:**
![002_motion-list](https://github.com/OpenSlides/openslides-client/assets/69210919/00c9a2cd-e2a4-4a08-b865-c215f686e02a)

**Wanted behaviour:**
The correct UI should always be displayed

**Comment by reiterl** [comment]
Where is the difference between good and wrong ui?

**Comment by Elblinator** [comment]
@reiterl there is not only more space in between the state (zugelassen) and the recommendation (Annahme), in the wrong Ui there is also no margin between the recommendation and the end of the row

**Comment by Elblinator** [comment]
@reiterl  I added steps 2 to 6 to explain how to activate the recommendations

**Comment by Elblinator** [comment]
This issue was solved by #2924
