### ISSUE TITLE
Motion blocks: Follow recommendations for all motions text is gone

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2930]
Description: If a user has opened a motion block and want to follow all recommendations, the function is hiding behind an icon with two hooks. For unexperienced users or users of OS3 this is an unclear or strange behavior.

OS4:
![Screenshot_20231020_142619](https://github.com/OpenSlides/openslides-client/assets/105491030/feb0e7dd-2b2a-4609-96d6-d19241e9bb1a)

OS3:
![Screenshot_20231020_142711](https://github.com/OpenSlides/openslides-client/assets/105491030/862355b9-2eb2-45ed-b30a-1388e64e74e0)

Reproduction:
1. open a meeting
2. open motions > create a motion 
3. open settings > motions > add a recommender
4. head back to motions and add the recommender to the motion
5. open the motion block menu and create a motion block. 
6. add the motion to the block and open the block

What should happen:
Like in OS3 beside the icon with two hooks should be the text "Follow recommendations for all motions" visible. Also the text and the icon should be one button.

**Comment by reiterl** [comment]
The text "Follow recommendations for all motions"  is in the tooltip of the icon. I will try to add it to the icon/button.
