### ISSUE TITLE
Fix text alignment

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2938]
**Current behaviour:**
If mulitselect is activated the "Nr selected" text is not aligned in the middle:

![004](https://github.com/OpenSlides/openslides-client/assets/69210919/280f681c-b29c-4ee6-bf9b-7984510ea5ff)

**Wanted behaviour:**
the "Nr selected" should be aligned in the same way as the arrow. 
(meaning that the text should have the central-axe as the arrow)

**Comment by maheshchandra10** [comment]
tried working on this issue, but I am facing a hard time running the application in local.

It says that `Using OpenSlides over HTTP is not supported. Enable HTTPS to continue` when accessing the application on http://localhost:9001/ , and local won't run on https://localhost:9001/.

If you know how to run it in local, please let me know, I'd love to work on this issue! Thanks.

**Comment by bastianjoel** [comment]
We have a guide in our main repository https://github.com/OpenSlides/OpenSlides/blob/main/DEVELOPMENT.md

With the full development setup your need to access the application on port 8000 via https.
