### ISSUE TITLE
Motion Block: Titles with spaces leads to wrong filter sorting

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2939]
**Description:** If a motion block has a title with one or more spaces, the motion block will be listed in the motion filters on the highest position.

**Example: Motion block title "   Z" -->**
![Screenshot_20231023_152254](https://github.com/OpenSlides/openslides-client/assets/105491030/adf1aa32-bd31-42cc-a69e-ccbc1ab53f7b)

**Reproduction:**
1. open a meeting
2. open motions > three-dot-menu > motion blocks: Create a block with the title "Test" and another one with the title "   Z". Take care of spaces. The listing in the motion block menu should be fine.
3. head back to motion menu > click on filters and check the order of the motion blocks. wrong order of blocks. 

**What should happen:** 
To avoid this behavior, spaces at the beginning of a motion block title should not be allowed.

**Comment by reiterl** [comment]
I think the solution here is to add sorting to the filter properties. It should be based on "trim" labels.
