### ISSUE TITLE
Change counted Requests to speak from minutes to hours

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2942]
**Current behaviour:**
If you count the requests to speak the time is counted as mm:ss
![007](https://github.com/OpenSlides/openslides-client/assets/69210919/612a6f5d-461e-4cc7-aacd-f69125c3ac78)

**Reproduction:**
in a meeting:
1. add yourself as an admin
2. put someone on a LoS
3. start and stop their contribution (wait a few seconds between starting and stopping)
4. click on your user name in the top right corner
5. select "Legal notice  Privacy policy"
6. scroll down to "Requests to speak" and start "Count completed requests to speak"
7. you should see something similar to the picture above

**Wanted behaviour:**
the displayed time should not be counted as mm:ss, but as h:mm

**Comment by reiterl** [comment]
Okay, I can reproduce the issue.
The seconds are cut with a solution to this requirements.
