### ISSUE TITLE
Fix Icon in dark-mode

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2951]
**Current behaviour:**
If a meeting is edited by an committee-admin, then the datepicker-icon has the wrong colour in light and dark mode 

**Colour in dark-mode (it is still dark):**
![011 B](https://github.com/OpenSlides/openslides-client/assets/69210919/30bd017d-6fde-43f8-909c-61ca5bf70aac)

**Colour in light-mode (it is too dark):**
![011 A](https://github.com/OpenSlides/openslides-client/assets/69210919/8432e3d9-303f-4966-9970-3a400b2fbf1d)

**Correct colour in light-mode (the colour is more greyish):**
![011 C](https://github.com/OpenSlides/openslides-client/assets/69210919/842aaa27-57a3-4171-962d-df58e908400d)

**Reproduction:**
in the orga-level:
1. create an account which is also a committee admin
2. login as the new account
3. if your committee has no meeting yet, create a new meeting
4. open the edit mask for a meeting 
5. the icon should have the wrong colour

**Wanted behaviour:**
The datepicker-icon should have the correct colouring

**Comment by luisa-beerboom** [comment]
Can't replicate

@Elblinator Is there some other factor at play? If not, please close this

**Comment by Elblinator** [comment]
cannot be replicated
