### ISSUE TITLE
Text in ActionWorkerBar is not readable

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2958]
**Current behaviour:**
If the ActionWorkerBar appears then the last word is unreadable:
![014](https://github.com/OpenSlides/openslides-client/assets/69210919/0d1ebf64-30e1-4f78-a3bf-1b43864acbcb)

**Reproduction:**
1. prepare a csv-file with a big amount of accounts
2. got into a meeting and import this file
3. the ActionWorkerBar should appear while the data is processed 

**Wanted behaviour:**
The word wait should have the same colour as the rest of the text and given that it is a link should have the underline from links

**Comment by reiterl** [comment]
The _Wait_ is a link. That is the reason it has a different color. Theme problem, won't fix.

**Comment by reiterl** [comment]
The component is 'wait-for-action-banner'. Changing scss doesn't help. Perhaps it is a mat-button? Adding color input doesn't help. So no idea.
