### ISSUE TITLE
Amendments with bullet points and change recommendation :  wrong line numbers and wrong text content relation

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2970]
**Description:** 
- [ ] If an amendment has bullet points with change recommendations in it, the line numbers are switching to a wrong numbering.
- [ ] Additionally, after the first problem appears, the text base for more change recommendations doesn't fit anymore.

**Original motion text with correct line numbers:**
![Screenshot_20231102_092204](https://github.com/OpenSlides/openslides-client/assets/105491030/369a3320-040c-4b78-8d3e-288d8f0ce5b7)

**Amendment with correct line numbers**
![Screenshot_20231102_152347](https://github.com/OpenSlides/openslides-client/assets/105491030/c8cde31e-5ad3-4d9a-9de2-651b9820d4ae)

**Amendment with change recommendation: wrong line numbers** 
![Screenshot_20231102_152442](https://github.com/OpenSlides/openslides-client/assets/105491030/a3c084b6-2080-4ddd-9f43-83922a155837)

**Additional change recommendation to second bullet point. text content didn't match to amendment. base is now the original content of the motion -> wrong**
![Screenshot_20231102_093437](https://github.com/OpenSlides/openslides-client/assets/105491030/d9638525-e902-4d19-83f2-31272fe32348)

**Reproductions:**
First issue:
1. open a meeting
2. open motions
3. create a motion with at least one paragraph and two bullet points
4. create an amendment which changes content in each bullet point
5. add a change recommendation to the first bullet point of the amendment
6. reload the amendment. Now Diff-version should load. If not, open it.-> line numbers are broken 

Second issue (based on the steps before)
8. try to add a change recommendation to the second bullet point and compare the text base (see the last image)

**Comment by CatoTH** [comment]
Hi,
hopefully, this following PR should fix the issue: https://github.com/OpenSlides/openslides-client/pull/2978

**Comment by rrenkert** [comment]
Thanks! works fine!
