### ISSUE TITLE
Participant import: importing standards groups in different language creates duped groups

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2971]
**Description:** If different languages are used in the OS client and in the import file, groups are incorrectly duplicated when importing participants. 

**Example:** The client is set to German and the English term for delegates is used in the import file. This results in the Delegates group being created again. One with the German term and one with the English term. To make it worse, this will lead to both terms being displayed in German in the participant filter options. 

**Group listing before import:**
![Screenshot_20231103_111658](https://github.com/OpenSlides/openslides-client/assets/105491030/74a748e7-f808-4999-8852-78982092a79b)

**group listing after data import with different languages:**
![Screenshot_20231103_111615](https://github.com/OpenSlides/openslides-client/assets/105491030/0841fffd-bf4b-42bf-a4b6-64d4d1d73600)

**Reproduction:**
0. Create a meeting in gemran language. 
1. open a meeting in german language 
2. open participants 
3. open the three-dot-menu > import menu 
4. download the example file and import it. The file should contain the english terms for Delegierte, Mitarbeitende.
5. open the participant menu > three-dot-menu > groups. Delegates and Staff should now be created.
6. open participants again and check filter menu > groups. Two Delegierte groups should be available.

**What should happen:**
When importing groups, it is necessary to check whether a standard group exists and whether this can be referenced in the selected client language. If the client is set to German, no second group should be created during import when using the English term in the import file, instead the accounts should be correctly integrated into the existing Delegates group. The aim is to ensure that groups are not unnecessarily duplicated.

This behavior should also apply to the other standard groups.

Notes: 
- This desired behavior was already common practice in OS3.
- Please check, if this fixed when the new import is integrated: https://github.com/OpenSlides/openslides-client/issues/2670

**Comment by Elblinator** [comment]
We once decided that it should be allowed to create groups with similar names (Deli vs deli) 
I would want to open the discussion of how different languages fit into this behaviour

**Comment by luisa-beerboom** [comment]
Now that the backend participant import is integrated, the import won't create groups any more and will instead ignore groups that it can't find, while using the default group if all are invalid. This means that accidental group duplication in imports is now impossible and therefore this issue is fixed.
