### ISSUE TITLE
Motion supporters: wrong sorting in motion detail and export

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2974]
**Description:** If a motion has supporters, the sorting of them in the motion detail view and in the pdf export is wrong and follows no obvious logic. 

**Example of wrong sorting in meta data:**
![Screenshot_20231103_124036](https://github.com/OpenSlides/openslides-client/assets/105491030/e42b1f0b-6652-43f2-9ef6-4596677a34e1)

**Reproduction:** 
pre condition: A few users are needed to add them as supporters.
1. open a meeting
2. open settings > motions > supporters > change number of minimum voters to 5 > save it
3. open motions > three-dot-menu > workflows > simple workflow > add Allow support to all states
4. open motions > create a motion with simple workflow > add users as supporters > save
5. check in the motion detail the supporter sorting
6. export the motion and check the sorting of the supporters. 

**What should happen:**
The sorting should follow the same rule like the participant sorting or if this is to complex to handle a clear rule like sorted by first name would be good.

**Comment by reiterl** [comment]
Tested this, the sorting follows the the order in which you insert the users and the sorting is changeable in the detail view. This would be more an "enhancement".
