### ISSUE TITLE
Missing Autoupdate in election

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2984]
**Current behaviour:**
If a election has a result and the page it reloaded then every candidate is displayed as "deleted user"

**Reproduction:**
in a meeting:
1. create an election
2. add a candidate which isn't you
3. start an election and publish the results
4. reload the page:  
![017](https://github.com/OpenSlides/openslides-client/assets/69210919/62446a46-3bad-450a-913c-8a630dc4c302)

**Wanted behaviour:**
The names of the candidates should always be displayed

**Comment by bastianjoel** [comment]
Only happens in Chromium
