### ISSUE TITLE
iOS devices: Two browser issues

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3007]
**Description:** On mobile iOS devices two issues occur, which need to be solved:

- [ ] The whole website content as one unit could be moved by touching and holding the screen with two fingers. 
- [ ] By clicking twice fast on the screen, a zoom in functions gets active. This is annoying. Example: By navigating between motions and clicking to fast on the buttons the zoom in starts. 

**What should happen:**
- [ ] The website should not be moveable. (Hint: If I get it right, this must be solved separately in portrait and landscape format)
- [ ] The gesture zoom in option should be deactivated in OS.

**Comment by rrenkert** [comment]
These are normal Safari/iOS features.
