### ISSUE TITLE
Polls/elections: problem with default value analog

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3008]
**Description:** If a user changes the default value of voting type for polls or elections to analog in the settings, votes didn't work anymore. (Also an error message appears in the console.) Even if the value is switched back to other voting types, it's not possible to reactivate the voting function.

**Affected setting - voting type of ballots (elections)**
![Screenshot_20231113_121059](https://github.com/OpenSlides/openslides-client/assets/105491030/14044567-1593-48dc-98f0-b7197465301d)

**Affected setting - voting type of motions**
![Screenshot_20231113_121129](https://github.com/OpenSlides/openslides-client/assets/105491030/ada1067e-010f-4a49-8dd6-2fedb5db5fa4)

**error message during vote creation - motions**
![Screenshot_20231113_121243](https://github.com/OpenSlides/openslides-client/assets/105491030/b3371aed-b5b7-46c3-b583-1618a72fd853)

**error message during ballot creation:**
![Screenshot_20231113_121313](https://github.com/OpenSlides/openslides-client/assets/105491030/4905ffd8-1095-4f19-bae7-b4026147e45b)

**Reproduction:**
1. open a meeting
2. open settings > motions > default voting type > change to analog
3. open settings > elections > default voting type > change to analog
4. open motions > create a motion > change status to a state were voting is possible > create a vote
5. open elections > create a new election > add candidates > create a new ballot 
6. Try to switch back the default voting type for motions and perform step again -> won't work -> voting is not possible anymore

**What should happen:**
Changing default voting types for elections and/or motions to analog shouldn't lead to a fatal error of the whole voting system.

**Comment by bastianjoel** [comment]
Regression from #2963
