### ISSUE TITLE
Remove the participant default_number

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#3030]
As discussed with @emanuelschuetze it makes problems and is not used.

**Comment by reiterl** [comment]
Begin to remove the default_number from the user code (accounts and participants)

**Comment by jsangmeister** [comment]
I assume the same has to be done in the backend. What should happen with the existing data? With the `default_structure_level`, it was migrated into the normal structure level (if a participant did not have a structure level, the default structure level from the account was used). Should something similar be done here? Or should the default number simply be dropped?

**Comment by jsangmeister** [comment]
@emanuelschuetze @rrenkert

**Comment by jsangmeister** [comment]
Opened https://github.com/OpenSlides/openslides-backend/issues/2117 for this
