### ISSUE TITLE
Add the motion.preamble to the motion.create view

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3059]
**Current behaviour:**
If a motion is created and a preamble is saved in the settings then the preamble is not displayed int the motion-create view but it is displayed in the motion-detail view

**Reproduction:**
in a meeting: 
1. settings > motions > save something in the "Motion preamble" input
2. create new motion 
3. the preamble is nowhere to be seen
4. save the motion 
5. the preamble is at the beginning

**Wanted behaviour:**
the preamble should be visible in the creation mask directly above the editor from the motion.text

**Comment by luisa-beerboom** [comment]
Do you mean instead of the `text` label or above it?

**Comment by Elblinator** [comment]
there is no "text" label while you create a new motion 

![new_motion](https://github.com/OpenSlides/openslides-client/assets/69210919/0084ede9-1481-4968-8220-c5fd4d680942)

The preamble should be between the title and the editor
