### ISSUE TITLE
Re-Login problem after logout

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3071]
**Description:** If a user is in a meeting and logs out of it, an error occurs when logging in again directly. The login page displays a permanent spinning wheel. Logging in is only possible after reloading the page. When reloading, the user is logged in directly. 

**Reproduction:**
1. open a meeting
2. log out
3. log in
4. -> spinning wheel appears.

**What should happen:**
Logging should be possible without a page reload and without a permanent spinning wheel.

**Comment by bastianjoel** [comment]
For some reason in `autoupdate.service.ts` the operator subscription is missing from `_activeRequestObjects`. Ill will investigate this further tomorrow.
