### ISSUE TITLE
Add a count up timer option

### ISSUE THREAD

**Issue by qstickmurph** [OpenSlides/openslides-client#3076]
**Is your feature request related to a problem? Please describe.**
Currently, we are using a countdown timer of 0 minutes to mimic a count up timer (stopwatch). Some of our members have expressed confusion about why the timer is negative and red, so we would like a upwards counting timer.

**Describe the solution you'd like**
I would like an option that allows the timer to count upwards rather than down. This would act as a stopwatch instead of a timer for timekeeping purposes.

**Describe alternatives you've considered**
Mentioned above.

**Additional context**
None

**Comment by jsangmeister** [comment]
This will be implemented as part of the LoS extension. If the `default_time` of a countdown is 0, it is a count-up timer and should be represented as such. This is required for interposed questions which count up.

**Comment by Elblinator** [comment]
this issue will be closed together with #3247
