### ISSUE TITLE
Deactivate statute feature

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#3085]
The feature statute amendments can be removed. It's never used any more.
Recommended way to create statute amendments: Copy full statute in a normal motion (with special category). Now, user can create (normal) amendments to this statute/motion. You get the full support for diff/amendent/pdf/projection. No special function for statute amendments. So please remove old code of statute amendments. BTW: the feature currrently not work (`NullInjectorError` after try to open list view).

**Comment by jsangmeister** [comment]
I assume the same holds true for the backend: https://github.com/OpenSlides/openslides-backend/issues/2053. Does this only pertain to statute _amendments_ or statute _paragraphs_ as well? Meaning, is https://github.com/OpenSlides/openslides-backend/issues/1715 still needed or can that be closed and all statute paragraphs related features be removed as well?

**Comment by MSoeb** [comment]
Discussed clean up process with @rrenkert. Clean up should be done in two steps:
1. Deactivate the check box in the settings and make it invisible. -> Feature can't be used anymore
2. After 2 weeks second step starts with clean up of everything that is associated with the feature.

**Comment by emanuelschuetze** [comment]
As discussed with @MSoeb: You can hide the statue amendment checkbox in settings now.

**Comment by jsangmeister** [comment]
Checkbox is hidden now

**Comment by Elblinator** [comment]
The statute amendment can be removed now
