### ISSUE TITLE
Fix import-file handling after one error in account import

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3100]
The change request from #3094 is moved into it's own issue.
> Previously when the import failed with a non-preview-related error (i.e. a string error that doesn't update the preview with an  explanation), a snackbar with the error would be shown, but the view would continue showing the preview in a context that implied the import to still be ongoing. -> Fixed that by making the view revert to a clean pre-import state

Change request:
> After running into the fix for 1 once, you need to reload the page to import the same file again in chromium

**Reproduction:**
chromium specific:
1. open account import
2. upload a faulty file (e.g. gender null)
3. try to import
4. you get correct behaviour
5. now try to select the same file again
6. nothing happens

**Comment by luisa-beerboom** [comment]
This should currently happening in every import that is handled via backend btw
