### ISSUE TITLE
Make motion submission date editable 

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3148]
needs https://github.com/OpenSlides/openslides-backend/issues/2112 

**Current behaviour:**
currently the submission date is automatically created by the program

**Wanted behaviour:**
- This submission date should be editable by participants with the permission motion.can_manage_meta_data.
- The submission date needs the edit icon next to the string 
- if the submission date is being edited a date and time picker needs to open.

**Comment by reiterl** [comment]
The backend issue needs to be resolved first.

**Comment by jsangmeister** [comment]
Backend PR exists: https://github.com/OpenSlides/openslides-backend/pull/2194
