### ISSUE TITLE
Fix LoS if structure levels are connected with the countdown and a participant has no structure level

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3150]
Prio A

**Current behaviour:**
If "default structure level speaking time in seconds" is activated (>0), then participants without one (or more) structure level(s) cannot be put on a LoS

**Reproduction:**
1. activate "Default structure level speaking time in seconds" 
2. have a participant without a structure level
3. navigate to any LoS 
4. try to put the participant onto the LoS 
5. nothing happens visually 
6. the console thrown following Error: 
```
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
```

**Wanted behaviour:**
Even if the structure levels are connected with the countdowns, a participant without a structure level should be able to be on the LoS

**Comment by reiterl** [comment]
I see an `ERROR Error: Uncaught (in promise): TypeError: user.getMeetingUser().structure_level_ids is undefined
addUserAsNewSpeaker/ [...]` if I try to add a participant without structure_level.

**Comment by reiterl** [comment]
Mmh, it is not possible to add a structure level to a speaker in a list os speakers without one.

**Comment by reiterl** [comment]
The structure level of a speaker should be in the list of the user's structure levels.
