### ISSUE TITLE
Fix Structure level display even without countdown

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3151]
**Current behaviour:** 
The structure level is not displayed/changeable in a LoS if "Default structure level speaking time in seconds" is 0

**Reproduction:**
Preconditions: 
- at least one structure level
- at least two participants need a structure level
reproduction:
1. in settings -> LoS -> "Default structure level speaking time in seconds" > 0
2. navigate to a LoS and put the participant with a structure level on it
3. the structure level is selectable and deselectable
4. navigate to settings -> LoS
5. put "Default structure level speaking time in seconds"  to 0
6. navigate to the old LoS the structure level is not deselectable
7. put the other participant on the LoS -> the structure level is not selectable

**Wanted behaviour:**
Even if the structure levels are not connected with the countdowns, they need to be displayed in the LoS.
If the structure levels are not connected with the countdown then **all structure levels** should be displayed, automatically. They should be separated by a comma)

**Comment by reiterl** [comment]
I don't understand the description of this issue. @Elblinator pls look over it and correct it.
