### ISSUE TITLE
Change interposed Questions warn dialog

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3168]
**Current behaviour:**
If an interposed question is stopped while no speaker is selected the following dialog opens:
![sel](https://github.com/OpenSlides/openslides-client/assets/69210919/a1c8efbc-dbe5-47ab-9326-69b1562f81f1)

**Reproduction:**
1. navigate to settings -> LoS -> activate interposed question
2. project something onto the autopilot
3. navigate to the autopilot
4. put someone on the LoS and start their contribution
5. activate the interposed question
6. start and stop it
7. dialog opens

**Wanted behaviour:**
There should be a text which says "Are you sure you want to stop the interposed question without selecting a speaker, the "Last speakers"-List will display this interposed question with a "Deleted user"?"
And the dialog needs an additional "continue" button

**Comment by bastianjoel** [comment]
This is intended behavior.
