### ISSUE TITLE
Change behaviour of interposed question

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3169]
**Current behaviour:**
If the parent from an interposed question is stopped the interposed question is left behind without it's parent

**Wanted behaviour:** 

-  if the child does not have a start time yet, then it should be dismissed
- if the child has a start time then the child should be saved and the end time  should be the same as the parents (if no speaker is selected then it should be saved as Deleted User)
- A dialog should open which warns the user of each of this 
  - Title "Are you sure you want to end a contribution which still has interposed question(s)?"
  - content = "_(number of interposed questions without start time)_ interposed questions will be cleared, _(number of interposed questions which have a start time)_ will be saved with an inaccurate time,  _(number of interposed questions which have a start time and NO selected User)_ of them will be saved with 'Deleted User' as their speaker"
  - the content should only show the categories which have a number bigger than zero

**Comment by jsangmeister** [comment]
> * if the child does not have a start time yet, then it should be dismissed
> * if the child has a start time then the child should be saved and the end time  should be the same as the parents (if no speaker is selected then it should be saved as Deleted User)

These should be changed in the backend and is tracked in https://github.com/OpenSlides/openslides-backend/issues/2136
