### ISSUE TITLE
Projector currently ignores updates from AU-Service

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#317]
Initially loading slides from the works fine, however, Incoming auto updates with new / updated slide data are currently getting ignored by the projector.

**Comment by FinnStutzenstein** [comment]
Is this really a client bug? I tried it with all current masters. The autoupdate service hangs. If I do a request containing `content`, I do not get a response (tried with curl, too, so no client bug). If I Ctrl+C curl, I get `Error parsing slide projection/6/content: fetching projection 6 from datastore: fetching data: getOrSet for keys `[projection/6/id projection/6/type projection/6/content_object_id projection/6/meeting_id projection/6/options]`: context canceled` in the autoupdate service, so something is wrong there.
