### ISSUE TITLE
List of speakers time management: permission issue

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3185]
**Description:** Users who don't have the permission 'Can manage list of speakers' can nevertheless edit the list of speakers time managment table in the list of speakers of for example an agenda item. 

![image](https://github.com/OpenSlides/openslides-client/assets/105491030/920acb57-666b-4657-85b3-9ad8a99fb2e0)

**What should happen:**
Editing this table should only be possible for users with the permission 'Can manage list of speakers'. Other user - with the  permission to see the content with the associated list of speakers - can see the table, but can't edit it.

**Comment by reiterl** [comment]
The `speakers-time-management` component will be replaced by the `speaking-times` component.
So I close this issue with "won't fix".
