### ISSUE TITLE
Moderation notes: Editing issue

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3186]
**Description:** Editing existing moderation notes in a different tab or as another user is currently bugged. By opening the edit tool, the text box is empty. The original text is not visible. Editing is not possible.

**Existing moderation notes:**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/f7ffe7f2-ee8c-4561-a4de-89290896b747)

**Editing mode without existing content:**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/35598f1b-2e50-4881-8a5d-78ad68100009)

**Repro:** 
1. open a meeting
2. create an agenda item and a moderation note
3. try to edit it in another tab or as another user

**What should happen:**
Editing should display the original text, so that it can be edited.

**Comment by reiterl** [comment]
The `moderatorNotesForm` Component is not correctly initiated.
