### ISSUE TITLE
Widget Speaking time: permission problem

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3187]
**Description:** Users who don't have the permission to administrate the projector (Can manage the projector) see the 3-dot-menu in the new widget speaking time. The menu can be used, but content can't projected, because this is currently not working. Nevertheless it's wrong, that user can see it. 

**Example: 3-dot-menu on the right side**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/718b4aea-ae1a-4fc3-93ee-620df968f6f9)

**Repro:** 
1. open a meeting
2. open settings > list of speakers > enable the new widget
3. open agenda > create an item > project it
4. open participants: create a new user without the group delegates
5. log in with the new created user and open the autopilot you should see the new widget with the wrong permission

**What should happen:** 
The three-dot-menu in the new widget should only be available for persons with the permission 'Can manage the projector'. Other user should not see it.

**Comment by reiterl** [comment]
The user needs the "can see los" right to see the los and the speaking times.

**Comment by reiterl** [comment]
The use of the permissions system is wrong in the speaking times component. I will add a PR to fix this.
I cannot fully test it, because of non-functional speaking times for non-superadmins.

**Comment by bastianjoel** [comment]
Included in #3176
