### ISSUE TITLE
Widget Speaking Times: No one except of admins can see content

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3188]
**Description:** Currently on the admin can see content in the speaking time widget. I'm not sure, what is the reason for the problem. Maybe this is associated with the problem, that structure levels can't be seen by other users in the autopilot expect of admins. 

**Repro:**
1. open a meeting
2. create an agenda item
3. open participants: create two structure levels, create two users with structure levels and give them delegates rights
4. activate the new widget in the settings
5. project the agenda item
6. open autopilot and add one user with a structure level
7. login as the another user and check the widget

**What should happen:**
User with the permission 'can see list of speakers' should see the content in the speaking time widget.

**Comment by Elblinator** [comment]
cannot be reproduced
Issue will be closed

**Comment by reiterl** [comment]
I have this problem here, a meeting admin cannot see the full speaking times.

**Comment by reiterl** [comment]
Ah, I tested it with newer component, here I don't see the problems anymore. So closed again.
