### ISSUE TITLE
Group permission menu: layout issue

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3189]
**Description:** The group permission menu has a layout issue. It is shrinked on full screen browser. The bug first appears during los-extension PR. Therefor I've added the label for it. 

![image](https://github.com/OpenSlides/openslides-client/assets/105491030/87ec7c38-792f-4367-9d8a-bf8286b21061)

**Repro:** 
1. open a meeting
2. open participants > groups menu

**What should happen:**
The groups menu should be visible on full screen and not shrinked.

**Comment by reiterl** [comment]
The reproduction steps are different.

1. open a meeting
2. participants -> groups (the whole screen is used)
3. autopilot with speaking times 
4. participants -> groups (now only the left part of the screen is used)
