### ISSUE TITLE
List of Speakers: csv export - more values needed

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3211]
**Description:** The csv export of the list of speakers (menu) miss some data and a column name should be changed to make it more understable. In the current state it is not possible to determine when someone has spoken. Also the duration is hard to recognize. Therefor the column name time should be changed. 

**What should happen:**
The csv file should contain the new values 'start time' (when did the contribute start).
Also the column name for 'time' should be renamed to 'duration in sec'.

New csv file columns order:
Title, Given name, Surname, Structure level, Participant number, Speech Type, Start time, Duration in sec, Element

**Comment by bastianjoel** [comment]
Time contains the duration of the speech in seconds.

**Comment by MSoeb** [comment]
Okay, i take it into account and change the issue according to this.
