### ISSUE TITLE
General abstain not listed in single votes

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#3218]
Create an election (yes per candidate) with option "general abstain". 
Vote for "general abstain".
Single vote tab does NOT show the general abstain vote, see example screenshot:

![election-abstain](https://github.com/OpenSlides/openslides-vote-service/assets/2075427/6e1af149-fbbc-4474-9cab-0b09d8a4d7b0)

Same for general rejection.

**Comment by jsangmeister** [comment]
Cannot reproduce on current main:

![image](https://github.com/OpenSlides/openslides-client/assets/33004050/258db29e-2cf9-4f8c-a66d-05151e558d99)

Please test again with up-to-date images and give a detailled way to reproduce the error (which instance, which users, superadmin or not, any reloads/logouts/etc. in between...)

**Comment by reiterl** [comment]
I didn't find the cause of the problem.
In `assignment-poll-detail.component.ts` in the method `createVotesData` the poll.global_option has `vote_ids` but no `votes`. I wonder, why the votes are not loaded. It uses the poll-detail subscription and should load the votes. But no.
I stop here.
