### ISSUE TITLE
Add structure level to interposed questions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#3221]
An interposed question with a selected speaker should display their structure level in the same way as a normal speaker and should allow to select a specific level if the user has multiple structure levels. This does not impact the timer of the structure level in any way and is purely for visual purposes.

**Comment by bastianjoel** [comment]
The time is currently subtracted from the structure level when a structure level is selected for an interposed question. This need to changed in the backend.
