### ISSUE TITLE
Workflow of amendment switches by editing

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3257]
**Description:** If a meeting has set different workflows for motions and amendments, the workflow of the amendment switches back by editing it. 

**Reproduction:**
1. open a meeting
2. open settings > motions > change Workflow of new amendments to Complex workflow. (New motion should still have simple workflow)
3. open motions > create a new motion. The preselected workflow should by simple workflow
4. create now an amendment. The status should now display "in Bearbeitung" or the english string for it. this reflects the frist state of the complex workflow.
5. Edit the amendment and check the workflow box at the bottom. -> The preselected workflow has changed to simple workflow. 

**What should happen:**
Editing an amendment should not change the workflow of the amendment automatically. The workflow should be the one which the amendment got during creation process.

**Comment by reiterl** [comment]
I can reproduce the failure with the steps. It seems that the `os-repo-search-selector` with `defaultDataConfigKey` overwrites the initialized value of `workflow_id` in `os-motion-detail-view`. 
This default value is not needed, because we are in edit mode.
