### ISSUE TITLE
Improve meeting-wide list of speakers

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#3267]
- [x] Add a filter for the content object type of the speaker's LoS. Possible types according to the [`models.yml`](https://github.com/OpenSlides/openslides-meta/blob/7abac793ed4f9c3df99210baf1404b4b7b4e7156/models.yml#L2107-L2112) are `motion`, `motion_block`, `assignment`, `topic` and `mediafile`, but AFAIK the last one is not used anywhere in the client, so we only need a filter for the first four.
- [x] Exchange the current flag icon in front of the content object's title with the appropriate icon for the content object type:
  - Motion: `assignment`
  - Motion block: `widgets`
  - Assignment: `how_to_vote`
  - Topic: `today`

**Comment by Elblinator** [comment]
This issue concerns the contribution page
