### ISSUE TITLE
Problem with nominal election and entitled users

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-client#3285]
Steps which I did:

1. Create a meeting, add two participants, both in the Delegates group
2. As admin create a poll, add the two as candidate
3. Create a nominal ballot
4. Start the election.
5. As one participant and vote for himself
6. As admin stop election
7. Click on ballot and try to click on entitled users

Now I see a Type error: TypeError: this.vote_delegations_from_ids() is undefined and the entitled users table doesnt appear.
I don't want this type error and see the entitled users table.

It seems to be an assignment poll.
Small observation, if I enter sth into search field so no user is found, I can change to the entitled users list.

**Comment by Elblinator** [comment]
With the given reproduction I can only get the console error:
```
 base-poll-detail.component.ts:291 ERROR ReferenceError: Cannot access 'clearSubscription' before initialization
    at Object.next (base-poll-detail.component.ts:294:17)
```
the error occurs if the participants which tries to see the ballot is not allowed to see the participants

@reiterl is this the behaviour you meant? If not, please specify your reproduction
