### ISSUE TITLE
Fix loading problems if browsers is closed/opened

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3291]
**Current behaviour:**
And if I start my Pc and then open/ call the url of the instance (also in productive Setup) then there is a loading symbol and 'Loading data. Please wait ...'

**Wanted behaviour:**
Opening openslides for the first time of the day should not send you into a indefinitely spinning wheel

removed login-part of issue, because it was due not code-related things

**Comment by MSoeb** [comment]
Additionally, this problem also occurs by opening content (e g. menus) in another tab. The problem is, that there is no clear reproduction.
