### ISSUE TITLE
Speaking times widget: Enhance time edit menu

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3296]
**Description**: In the current state, the three-dot-menu behind a structure level misses some time edit options,which leads to some problems. 
- If someone has spoken, the time can't be edit. This results in the worst case scenario, that the list of speakers needs to be created again from the scratch.
- If there is a need to add, remove or reset the time, the menu doesn't provide the edit options.

![image](https://github.com/OpenSlides/openslides-client/assets/105491030/4dc25a3c-e853-4389-b8e5-88ffbf670087)

**What should happen:**
- [x] Editing total time should always be possible. The 'edit total time' options should always be active/enabled. 
- [ ]  Additionally other edit time options should be added, which should always be active. This include three options: 
1. Reset timer: The timer should be resetable to the start time of the set structure level timer. NOT the general default time value for structure levels. 
2. Add time option: It should be possible to manually add time to the structure level timer. 
3. Remove time option: It should be possible to manually remove time from the structure level timer.

**Comment by luisa-beerboom** [comment]
I created a backend PR for this: OpenSlides/openslides-backend#2220

It changes the functionality is as follows:
1. Setting `initial_time` is no longer inhibited by whether or not someone has spoken yet
2. If `initial_time` is changed, `remaining_time` is increased/decreased by the same amount

**Comment by Elblinator** [comment]
I'm sorry, your message was not displayed and I opened another backend Issue due to that
I already closed the issue again
