### ISSUE TITLE
Speaking Times Widget: Edge case with deleted person and structure time

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3297]
**Description:** Scenario: There are several people with different structure levels on a list of speakers. There is one person who contributes an structure level for the speaking time widget. All other people have other structure levels. If this one person is deleted from the list of speakers because he or she was placed on the list by mistake and there is no other person with an identical structure level, the structure level is deleted from the speaking time widget. This is correct. The problem is that the person's speaking time is deducted from the total speaking time of the structure level. This is incorrect. 

**What should happen:**
It would be good to include a possibility to transfer the resulting speaking time to the outline level via dialog prompt in order to reset the time. 

This requirement is directly linked to the issue #3296 . Once this issue has been resolved, the majority of this problem should also be solved. Nevertheless, automating the time transfer would simplify processes and better intercept edge cases. Especially if a person has already spoken at the same structure level and a subsequent person who has already spoken is to be deleted. This time could be edited manually by solving the issue #3296 , but this manual editing can lead to unwanted errors.

**Comment by Elblinator** [comment]
we need revisit this after some customers actually used this function

**Comment by Elblinator** [comment]
The time widget is manually changeable now. Because of that this issue will be closed
