### ISSUE TITLE
Fix Moderation Note visibility

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3301]
**Current behaviour:**
If a person is allowed to see the moderation note but not allowed to manage it, then they cannot see the moderation note

**Reproduction:**
1. project sth with a moderation note
2. allow group A to see the moderation note
3. assign the group to a participant 
4. login as this participant 
5. navigate to the autopilot 
6. the moderation note is not visible

**Wanted behaviour:**
the moderation note should be visible if the participant is allowed to see the moderation note

**Comment by reiterl** [comment]
I cannot reproduce this. If a moderation note has a value, a user with a group with canSeeModerationNotes
can see the moderation notes. Perhaps you have forgotten to set a value to the moderation notes?

**Comment by Elblinator** [comment]
The moderation note is invisible (for ppl. with only canSee) if the moderation note is empty. 
This is the wanted behaviour (talked about with @emanuelschuetze and @MSoeb)
