### ISSUE TITLE
Fix not displayed moderation note

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3310]
**Current behaviour:**
If you navigate into a LoS-Detail view then the moderation note is only visible after the 'Speaking times' card is visible, 
The moderation note should always be visible

**Reproduction:**
1. activate teh structure levels
2. assign at least one participant a structure level
3. create a new object wih a LoS (e.g. motion)
4. Navigate to the new LoS-Detail view
5. the moderation note should not be visible 
6. add a participant (with a structure level) to the LoS
7. the speaking times card and the moderation note become visible

**Wanted behaviour:**
The moderation note should always be visible

**Comment by reiterl** [comment]
I build a fix. No longer need countdown enabled to show moderation note.
**Note:** The moderation note must be filled to be shown for can see moderation notes permission.
