### ISSUE TITLE
Add structure level in participant export

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3315]
**Currently:**
When you export a participant list then the structure level are not exported 

**Reproduction:**
1. navigate to participant-list
2. add some structure levels to some participants
3. export the participant-list
4. the structure levels are not exported

**Wanted:**
The structure levels should be exported

**Comment by reiterl** [comment]
I have looked at this. Updating the import will fix this too, if done correct. So waiting on the import to include the structure_levels.
