### ISSUE TITLE
Motion creation: default workflow not displayed

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3319]
**Description:** During motion creation the default workflow is not shown/preselected. 

![image](https://github.com/OpenSlides/openslides-client/assets/105491030/f2544777-11ba-416c-8ee1-cb33dfc3dc7a)

**Reproduction:**
1. Open a meeting
2. open Motions > create a motion > Check workflow box. It is empty. 

**What should happen:** 
During motion creation the workflow box should not be empty. There is always a workflow set-up which should be preselected.

**Comment by Elblinator** [comment]
The default workflow is preselected but the preselection is not displayed

**Comment by reiterl** [comment]
Could that be, that the reason for this is the default part which I removed from the selector, so the working_id is no longer
overwritten?

**Comment by bastianjoel** [comment]
The default workflow is not preselected. It is set by the backend.
