### ISSUE TITLE
Point of Order button

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3339]
**Question:**
How should Openslides behave if a Users is allowed to put point of orders for other people on the LoS and is on the LoS with a point of order

**Reproduction until issue occurs:**
1. login as an admin
2. navigate to settings > LoS
3. activate 'Enable point of orders for others' and 'Enable point of order'
4. navigate to a LoS
5. press point of order and ok
6. you put yourself on the LoS with a Point of order
7. now the button changed to 'Withdraw Point of order'
8. And you have no possibility to add another User with a Point of order

**What is wanted?**
- should a new button appear next to 'withdraw [...]' which is the same a the point of order button now?
- should the withdraw button be changed (in what way) to have the same amount of buttons but more options?
- should the status quo be kept?

**Comment by jsangmeister** [comment]
obsolete with https://github.com/OpenSlides/openslides-client/pull/3348
