### ISSUE TITLE
Unreadable label in forms when in dark mode (default theme)

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-client#3341]
**Reproduction**

* Select default theme
* Switch to dark mode
* Open some form
* Focus a form field
* Watch the label moving to the top and changing the color.

-> the text no more readable since the contrast is not high enough.

**Comment by reiterl** [comment]
I can reproduce this. The light-blue label on a light-grey background is not visible.
Tested with new structure level form (label Name) in dark mode.
