### ISSUE TITLE
Committee admin cannot appoint themselves as meeting admins if too

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3353]
old issue from the backend with updated information: https://github.com/OpenSlides/openslides-backend/issues/2205

**Current behaviour:**
if an committee admin tries to appoint themselves as a meeting admin in a meeting with a date the following error is thrown: 
```
Error: You are not allowed to perform action meeting.update. Missing Permission: meeting.can_manage_settings
```

**Reproduction:**
Orga-level:
1. login as a committee admin
2. create a new meeting with a date
3. remove yourself as the meeting admin
4. try to add yourself as an meeting again
5. the Error appears

**Wanted behaviour:**
If a user is a committee admin then they need to be able to appoint themselves as meeting admin in every meeting from their committee, even if other meta-data is set about the meeting

**Comment by reiterl** [comment]
I can reproduce this.
