### ISSUE TITLE
Prevent change of speech state for current_speaker

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3358]
**Current behaviour:**
In a LoS if a speaker already started to speak then the speech state can be changed to any other speech state

**Reproduction:**
1. activate pro/contra speech state, enable star icon, activate intervention, activate countdowns for structure levels, enable point of orders for other participants
2. navigate to any LoS
3. put someone on the who has a structure level
4. select the structure level
5. start the participant
6. now change the normal contribution to any of the above
7. the countdown for the structure level will continue to count down even if the speech state is changed to a state without/with it's own countdown

**Wanted behaviour:**
- the speech states PoO, Pro, Contra, star should be exclusive to each other, only one of them should be active at a time 

If the currently speaking person speaks for/as....
- person speaks with no chosen speech  state/PoO/Pro/Contra/star, then the different speech states (no chosen speech  state/PoO/Pro/Contra/star) should still be selectable/deselectable
- If the person speaks as intervention, then nothing should be changeable 
- If the person speaks with a structure level, then only pro contra and star should be selectable/deselectable

**Comment by jsangmeister** [comment]
Why is this a meta issue? This will also need equivalent changes in the backend.
