### ISSUE TITLE
Remove amendments if motion is deleted

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3361]
**Currently:**
If a motion with amendments is deleted then the amendments are left behind and practically unusable.

**How to reproduce:**
1. create a motion
2. create an amendments for this motion
3. delete this motion
4. a dialog opens which warns you that some amendments will lose their parent motion

**Wanted:**
When a motion which has amendments is deleted then the amendments should be deleted together with the motion
The warning should be adjusted accordingly

**Comment by luisa-beerboom** [comment]
OpenSlides/openslides-backend#2253

**Comment by reiterl** [comment]
@luisa-beerboom have you seen my pr?

**Comment by luisa-beerboom** [comment]
@reiterl why weren't you assigned to this issue?

**Comment by reiterl** [comment]
Ah, sorry, I forgot this. Your pr is more complete. So I closed mine.
