### ISSUE TITLE
Fix resetting 'Default groups with voting rights'

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3382]
**Current behaviour:**
If the 'Default voting type' or 'Add to agenda' is changed then every entry from 'Default groups with voting rights' is deselected

**Reproduction:**
1. navigate to Settings -> continue to Agenda/Motions/Elections
2. select anything in 'Default groups with voting rights'
3. save the change
4. change 'Default voting type' (in Motions and Elections) or 'Add to agenda' (in Agenda)
5. save the change
6. the old default groups are still displayed
7. reload page
8. the default groups are empty

**Example payload from election:**
```
[
    {
        "action": "meeting.update",
        "data": [
            {
                "assignment_poll_default_group_ids": null,
                "assignment_poll_default_type": "pseudoanonymous",
                "id": 2
            }
        ]
    }
]
```

**Wanted behaviour:**
The 'Default groups with voting rights' should not ne automatically changed. They should stay the same even if other settings are changed

**Comment by luisa-beerboom** [comment]
Can't replicate

**Comment by Elblinator** [comment]
Tested with Chromium and firefox

Tried again with reproduction: 
- make stop-dev
- make services-tomain
- make run-dev
- login as admin
- navigate: demo meeting > settings > elections
- (pre selected: default election method = Yes per candidate, default groups with voting rights = Admin, Staff)
- I added Committees and Delegates to Default groups
- save change 
- reload page (all four groups are selected)
- I changed default election method to No per candidate
- save change
- reload page (none of the four groups are selected)

**Comment by reiterl** [comment]
I can reproduce this problem.
I tried to debug it. In meeting-settings-group-detail-field.component.ts the onChanged seems to be called with a false null on init for groups typed settings. I looked into the html code and find the os-list-search-selector there. I don't know, why the null value is set.

I will add a fix, which uses special treatment in the valuesChanged part.
