### ISSUE TITLE
Free Text submitter: committee selection

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3429]
Description: The new feature free text submitter (solved in #3362) needs an enhancement for committes. The aim is to add a committee selection field under the new free text field.

- Data base: The data of the selection field is based on the committees that can forward a motion to the meeting and NOT committees, that can receive a motion from this meeting. So the data base is the counter part to motion forwarding.
- Layout: The selection field should follow the layout of other committee selection fields like for example the one for recommendation extensions. (see example bellow)

![image](https://github.com/OpenSlides/openslides-client/assets/105491030/d7f801db-eeac-4e0a-836b-adf6809a4297)

**Comment by jsangmeister** [comment]
This will require an update to the `get_forwarding_meetings` presenter as it currently returns only the meetings which can be forwarded to.

**Comment by Elblinator** [comment]
The issue is waiting for https://github.com/OpenSlides/openslides-backend/issues/2356
