### ISSUE TITLE
Agenda: New navigation + addtional positioning of moderation notes

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3447]
**Description:** The agenda needs to be enhanced with a new navigation (just like in motions) and every agenda item should include moderation notes.

**What should happen:**
- [x] Currently the moderation notes are located in the list of speakers of an agenda item. -> Additionally they should also be available in the agenda item itself right beneath the item description. The 'new vote' button will be under the moderation notes. -> see below.
- [x] Integrate a new navigation between agenda items. The navigation should follow the rule to navigate _only_ accross agenda items. If a motion (and motions blocks and so) and/or election is part of the agenda, theys will be skipped by the navigation. -> see below
- [x] Add the new navigation on the top right side just like in motions. The navigation need to have a forward and backward button as well as the agenda numbers (e.g. TOP XY), if they exists. -> see below 
- [x] To activate/deactivate the new navigation please add an option settings > List of speakers.

**Comment by reiterl** [comment]
I will work on the moderation notes part.

**Comment by reiterl** [comment]
I worked on the arrow navigation in the topic detail view.

**Comment by reiterl** [comment]
agenda items can be topic, motion, motion blocks, ... I suppose, that nav should go thru topics.
topics has a title and a sequential_number, I display the sequential number in the arrow navigation of topics.

**Comment by reiterl** [comment]
Add an issue about the new meeting setting in the backend.

**Comment by reiterl** [comment]
Resolved: the missing #3517 was merged on last Friday.
