### ISSUE TITLE
Mandat swap: rework 

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3450]
**Description:** The mandat swap in it's current status needs a rework to made it more accessible and easy to use. Additionally, the layout/ui should be improved.

**What should be done:**
- [x] The mandat swap should be placed in a three-dot-menu behind a participant (see image one)
- [x] This menu should include further more options to choose from (see image two)
- [x] mandat swap: If a user chooses the mandat swap option, an dialog field opens, where a participant can be selected. After the selection is done, a comparison is shown. To perform the mandat swap the user needs to click on "Mandat swap". (see image 3)
- [x] Permission for swap: Same as before. 
- [x] old mandat swap: The old mandat swap positioning can be deleted. 

Image 1:
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/e1cf9397-54f5-4c4a-853a-b6d7ab9fe511)

Image 2:
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/6a285f63-72f5-45ba-94f3-6aec7f275bca)

Image 3:
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/c09c0e15-eed0-4e30-a074-ab8a1024331b)

**Comment by bastianjoel** [comment]
I won't add the edit button to the three dot menu as we currently do not have an explicit route to the participant edit form and updating the component to support an additional route would require some effort.
