### ISSUE TITLE
Check all tree lists (agenda, category, call list) when the sorting is fixed in the backend

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#347]

**Comment by GabrielInTheWorld** [comment]
When is the sorting in the backend fixed? Is there a related issue?

**Comment by FinnStutzenstein** [comment]
https://github.com/OpenSlides/openslides-backend/issues/809 / https://github.com/OpenSlides/openslides-backend/pull/879
