### ISSUE TITLE
Fix committee Export missing data

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3475]
**Current behaviour:**
Several entries are missing from the committee example import file

**Reproduction:**
1. navigate to committee import page
2. download example file
3. several column are empty beside the colum title

**Wanted behaviour:**
The implemented data from the example file should also be exported into the example file

**Comment by rrenkert** [comment]
As decided in https://github.com/OpenSlides/openslides-client/pull/3476#issuecomment-2044372169 we can close here.
