### ISSUE TITLE
Participants > vote delegation: New permissions for principals (limit actions)

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3477]
**Description:** At the current state, principals have the same permissions as proxys. For example, they can add themselves to the list of speakers or they can create motions/amendments. This permission system needs an improvement to restrict some permissions of principals (that are not present). 

**What should happen:**
Add four new settings to limit the actions of principals which are not present. 
- [ ] Principals may not place themselves on the list of speakers
- [ ] Principals may not submit motions/amendments
- [ ] Principals may not support motions

**Comment by MSoeb** [comment]
Need to discuss where this feature should be implemented. Add restrictions via vote delegation seems not to be a good option. We need to discuss options.

**Comment by luisa-beerboom** [comment]
This will need significant backend changes, including meta changes -> backend issue is OpenSlides/openslides-backend#2348
