### ISSUE TITLE
Fix three dot menu for participant in participant-list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3486]
**Current behaviour:**
The three dot menu is always visible even if no options are available

**Reproduction:**
1. have a group who can see the participants but not manage the participants
2. login as a user from this group
3. navigate to participant-list
4. three-dot menu is visible and clickable but opens empty 

**Wanted behaviour:**
The three dot menu should only be visible if an option is availavle/if the participant can manage participants

**Comment by reiterl** [comment]
This should wait until #3158 , because that issue changes what actions are available in the participant-list.

**Comment by jsangmeister** [comment]
#3158 is done
