### ISSUE TITLE
Group switch: Switch needs an unnecessary reload to be visible active on user device

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3491]
**Description:** 
If the group of a participant is changed, the displayed items in the menu on the left are wrongly displayed. To be correctly displayed a reload is needed.

**Reproduction:**
1. open a meeting
2. Create two new groups (A and B)
3. Give group B every permission but can Manage participants (Note for more info on the permissions*)
4. Give group A only the permission to see the front page
5. Create a new participant P and assign group A
6. open a new browser and log in as P
7. As admin: change the user group from A to B

*Note: If every permission is activated (in one of the groups) this bug does not happen, as far as I could figure out the menu on the left is correctly updated when the one of the groups has the permission **to manage participants**, if the bug still doesn't happen even if this permission is not activated in both groups, then please only activate the following permissions for group B:

- can see autopilot
- can see projector
- can see agenda
- can see motions
- can see elections
- can see participants
- can see files
- can see front page
- can see history
- can manage settings
- can manage the chat

**What should happen:**
The displayed menu on the left should always hold the right items (which the participant can access) even if the groups are swapped

**Comment by reiterl** [comment]
I cannot reproduce this.
I checked following: Open the app with admin (FF) and test_user1(Chromium) and changed the group of test_user1
with admin. At least in the participant page this has effect on the menus in list view and displayed information.
This issue needs more info.

**Comment by reiterl** [comment]
@MSoeb showed it. The problem seems to appear with the sidebar and change of Delegate to Admin group.
I will try to reproduce it.

**Comment by reiterl** [comment]
I can reproduce the problem. The sidebar doesn't update, if someone changes the group to/from the Admin Group.

**Comment by bastianjoel** [comment]
Cannot reproduce

**Comment by Elblinator** [comment]
I updated the reproduction as best as I could and added a Note.
