### ISSUE TITLE
Contributions menu: identifier - loading bug

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3499]
**Description:** The motion identifiers are not loaded in the contributions menu until the motion menu has been opened.

**Reproduction:**
1. open a meeting
2. open motions > create a motion and take care, that it has an identifier
3. open the list of speakers of the motion and add yourself as admin on the list.
4. open participants > contributions menu. Now you should see your contribution with the identifier in the metadata.
5. Delete cache and reload the website (contributions menu). Now the identifier should not not be visible anymore until the motion module is opened again. 

**What should happen:**
The motion identifiers should load in the contributions menu even without opening the motions module first.

**Comment by reiterl** [comment]
I cannot reproduce this. The identifier (German: "Bezeichner") is in the contribution list before and after cache clear and reload.

**Comment by reiterl** [comment]
Arg, this is already fixed.
