### ISSUE TITLE
Speaking time – current contribution projector: enhance with more speaking categories

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3500]
**Description:** The Speaking time – current contribution projector needs to be enhanced with more speaking categories and an information about the speech category for each one in the projection. Currently it only displays a speech time and the name of a structure level, which isn't sufficient. 

**What should happen:**
The Speaking time – current contribution projection should als include the following speech categories and times:
- interventions
- interposed questions
- point of orders
- normal contributions

The projection should switch between these contributions. Also it should display a short information about the category of the speech. Example: If a person speaks for a structure level, the structure level is displayed. If a person has an intervention, the description intervention should be displayed. The name should not be included. Only speech time and category.

**Comment by bastianjoel** [comment]
The `speech_state` property is already sent to the client with the los projection.

**Comment by bastianjoel** [comment]
Needs to be added to the projection in autoupdate
