### ISSUE TITLE
Speaking Time Widget - wrong time visualization

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3503]
**Description:** The time values are sometimes incorrectly displayed. This can have two different outcomes. A) Times are displayed in a 'NN:NN' style. B) Times are displayed with a high number value.

**Reproduction:** The reproduction is unclear. It seems to me, that the issue has a connection to a missing autoupdate, because this problem occurs sometimes in cases, were other menus (like for example participants) hadn't been opened. The crucial point is, that there is no clear reproduction.  

Error for 'NN:NN' happened again: Repro still unclear, but failure message appears  in console.
Cannot read properties of undefined (reading 'map')

**What should happen:**
The speaking times should always be visible in the correct time style Minutes:Seconds.

**Comment by reiterl** [comment]
I cannot reproduce this. In the speaking times component is the countdown-time component used. It always uses
string to display the time. @MSoeb Pls provide a way to reproduce this failure or this issue will be closed.

**Comment by MSoeb** [comment]
Thanks for your feedback and analysis, @reiterl. I've discussed this with @rrenkert and @Elblinator. We came to the decision that the issue will remain open for documentation and transparency.

**Comment by reiterl** [comment]
@bastianjoel I assign you here, because you did the #3960 to fix it.
