### ISSUE TITLE
Fix not projected change recommendations

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3508]
**Current behaviour:** 
in an amendment: If a change recommendation changes a line which is not changed by the amendment then the change recommendation is never projected onto a projector

**Screenshots:**
![amendment](https://github.com/OpenSlides/openslides-client/assets/69210919/67d785b6-5e1c-458c-9d2a-ee0095b89e15)

![projected amendment](https://github.com/OpenSlides/openslides-client/assets/69210919/34ee2a4b-a32e-488c-adc7-c6d69f9756a3)

**Reproduction:**
1. create a motion with one paragraph with several lines
2. create an amendment which changes only one line 
3. in the amendment add a change recommendation which changes a different line than the amendment
4. project the amendment (in the diff version)
5. the change recommendation is not projected

**Wanted behaviour:**
If an amendment is projected then every changed line (amendment and change recommendation alike) and every line in between should be projected; in my screenshot line 7 to 9 should be projected.

**Comment by bastianjoel** [comment]
Duplicate #2503
