### ISSUE TITLE
Fix dashboard card in darkmode

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3513]
**Current behaviour:**
In darkmode: If a category (future/ended) has no meeting then the corners from the mat-card/the empty card are not in darkmode

screenshot:
![dashboard](https://github.com/OpenSlides/openslides-client/assets/69210919/2dfa91da-25ea-4934-85f9-193d9f12881a)

**Reproduction:**
1. navigate to the dashboard
2. turn on darkmode
3. make sure at least one of the different categories has no meeting

**Wanted behaviour:**
The corners from the card should follow the darkmode theme 
-> navigate to meeting > startpage to see one example of the wanted corners

**Comment by bastianjoel** [comment]
Duplicate
