### ISSUE TITLE
Syntax Error: list_of_speakers_hide_contribution_count does not exist

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#3516]
Open meeting from dashboard (in current 4.1.6 stable):
=> Autoupdate error:
`"field \"list_of_speakers_hide_contribution_count\": meeting/list_of_speakers_hide_contribution_count does not exist"`

**Comment by Elblinator** [comment]
Some part of the reproduction is still unclear 
@emanuelschuetze if possible please complete the reproduction
Reproduction: 
1. Go into a meeting 
2. reload the page 
3. navigate to the dashboard
4. navigate into an other meeting

**Comment by bastianjoel** [comment]
This is not reproducible

**Comment by reiterl** [comment]
I think this was a problem with a too old autoupdate service. I cannot reproduce this.

**Comment by bastianjoel** [comment]
I will close this now as there is no info provided since last week.
