### ISSUE TITLE
List of speaker overlay escaping projector

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#3521]
The list of speaker overlay sometimes escapes the projector view. 

To reproduce:
1. Project content object with LoS
2. Open Projector
3. Project LoS overlay
4. Open home
5. Reload
6. Navigate to autopilot

For a brief moment the LoS overlay should be visible in the right corner

**Comment by reicda** [comment]
Neither @Elblinator nor I can reproduce the case. Probably fixed within another issue?

**Comment by bastianjoel** [comment]
Looks like this only happens in firefox.

**Comment by reiterl** [comment]
I tried to reproduce this problem with firefox 115.10.0esr from Debian. I **cannot** reproduce it.
I created a motion with los and followed the instructions.

**Comment by rrenkert** [comment]
I can not reproduce this, too.

**Comment by bastianjoel** [comment]
Still happens.

**Comment by reiterl** [comment]
@bastianjoel Which browser version are you using? Sth that can help to reproduce this?

**Comment by bastianjoel** [comment]
This seems to be a firefox bug.
