### ISSUE TITLE
Motion forwarding: enhance dialog options

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3527]
**Description:** The current motion forwarding dialog should be enhanced in several aspects. In general the aim is to provide a broader range of different options which the user can choose from. 

**What do we need?**
The forwarding dialog needs to be enhanced with new options where the user can choose which content (version of motion), which submitter, which identifier and in which meeting the motion should be forwarded. Below is a list of the new dialog options:

Motion version:
- Orginal motion text with amendments/change recommendations
- Final version (note: if Editorial final version is available, use this one)

Submitter:
- original submitter name
- committee name 

Identifier:
- original identifier 
- without identifier

Meeting selection

Here an example image, how this forward dialog should look like
![002](https://github.com/OpenSlides/openslides-client/assets/105491030/d65afbb9-0bd1-4785-9cf4-2c0170375285)

**Comment by luisa-beerboom** [comment]
There's a backend PR for this: https://github.com/OpenSlides/openslides-client/issues/3527

Please look into if this works for you

**Comment by reiterl** [comment]
The backend PR for this is https://github.com/OpenSlides/openslides-backend/pull/2399
It allows to set use_original_submitter and use_original_number. I include the two options in my pull request.

What should be done with `Motion version`?

**Comment by luisa-beerboom** [comment]
Use the text the client generates for the named version and write it into `motion.create_forwarded`'s `text` argument

**Comment by Elblinator** [comment]
Given issue #3609:
If the committee is selected as submitter in the new dialog then no new User should be created but the committee name should be written into the extension text field for submitters

What should happen if the 'original submitter name' is selected? 
What I expect:
- no new user is created
- extensions are written into the extension
- If a User exists in the forwarded to meeting, then the User is assigned as a submitter
- If a User does not exist in the forwarded to meeting, then the User's name is written into the extension
- [the order of names in the extension should be the same as it was in the original motion, at least as much as possible ]
