### ISSUE TITLE
PDF Export: file attachment has wrong URL

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3539]
**Description:** If a motion with a file attachment is exported, the URL of it is wrong in the PDF file. The URL contains one / too much.

problem - double slash behind .com:
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/cd7aca2b-8e55-4c98-8536-8b3ca2f96bdc)

**Reproduction:**
1. open a meeting
2. open files and add a file
3. open motions > create a motion and add the file as an attachment
4. open motions > three dot menu > Export > PDF Options > activate Attachments > click 'Export'
5. open PDF File and check to attachment link.

**What should happen:**
The file attachment URL in the pdf should be correctly included - without the double slash - in the pdf file.

**Comment by reiterl** [comment]
Ah, I have tested it here: In default configuration it is e.g: "antrag.txt:  https://example.com/system/media/get/2".
I suppose, that the url config of the test.staging.server is "https://testintern.staging.openslides.com/" which is wrong. 
It should be "https://testintern.staging.openslides.com".

**Comment by reiterl** [comment]
Another thought about this: I will trim the trailing of the url setting in pdf export. Then this should no longer be a problem.
