### ISSUE TITLE
Make Username visible if ```can_see_sensible_data``` ist true

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3548]
**Current behaviour:**
Even if a person is allowed to see sensible data the Username in the participant-list will never be displayed

**Reproduction:**
1. login as an admin
2. navigate to a participant list
3. create a participant without surname and firstname and only username; save
4. navigate back into the participant-list 
5. User ## will be displayed in the participant-list 

**Wanted behaviour:**
Given that a participant has the permission to see the username:
In the participant-list:
The display should be like the display in the account list
account-list:
![accound-list](https://github.com/OpenSlides/openslides-client/assets/69210919/8d1aa84c-c09e-4f8f-9ca1-52ecd2869faf)
participant-ist:
![participant-list](https://github.com/OpenSlides/openslides-client/assets/69210919/99cf0127-5fa2-44d1-9b71-01a0c84d56a9)
(description: the username should be displayed under the other name, if vote weight is activated then the username should be on the most left hand side and vote weight and name should be separated with a middot)

Several snackbars, views or pages: 
with diverse actions you can see the string "User ##" so far I cannot identify an actual loss of functionality **IF** the username is also additionally displayed in the participant-list. this may need some revisiting after the participant-list is fixed. But this should be done is a separate Issue then.

**Comment by reiterl** [comment]
I tried to add the operator and a perm check to the getName method in user-repository. But it broke the app.
The login screen was no longer visible. I wont continue here.

**Comment by bastianjoel** [comment]
This is intended behavior. See for reference #3464. 
The reasoning to remove the username from displaying as fallback was that in real instances first and lastname for all users are normally set.

**Comment by bastianjoel** [comment]
If you still want to change this see #3489

**Comment by jsangmeister** [comment]
I second that this is not necessary. Users with `can_see_sensitive_data` can still see the usernames on the detail page of the user. Implementing a permission check in the user repo does not sound feasible and workarounds or alternative solutions will require more work than what this issue is worth.

**Comment by Elblinator** [comment]
(23.04.24) 
I updated the wanted behaviour
