### ISSUE TITLE
Fix Participant detail view if the User cannot manage participants

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3549]
**Current behaviour:**
If a participant is not allowed to manage other participants then every participant detail view displays the icon for inactive users:

![Screenshot_20240411_155548](https://github.com/OpenSlides/openslides-client/assets/69210919/8e46a451-76b7-4962-b976-5da1576dc199)

**Payload if you are not allowed to manage:**
{
    "meeting_user/7752/id": 7752,
    "meeting_user/7752/meeting_id": 288,
    "meeting_user/7752/user_id": 7139,
    "user/7139/default_vote_weight": "1.000000",
    "user/7139/email": "",
    "user/7139/first_name": "",
    "user/7139/id": 7139,
    "user/7139/is_physical_person": true,
    "user/7139/last_name": "",
    "user/7139/meeting_user_ids": [
        7752
    ],
    "user/7139/username": "fjyfyt"
}

```
user/7139/is_active: true
```
is missing from the payload

**Reproduction:**
1. create participant A 
2. Activate Can see participants, Can see sensitive data, Can manage presence of others, Can update participants
3. Login as A and navigate into any participant detail view (make sure that the participant is not actually inactive)
4. The participant will (in the detail view) be displayed as inactive

**Wanted behaviour:**
A participant should only be displayed as inactive if they are indeed inactive

**Comment by reiterl** [comment]
As far as I understand this problem: It is an autoupdate server problem.
The subscription participant-detail doesn't give is_active for an user with UsercanUpdate.
The subscription participant-detail give is_active for a user with admin rights.

**Comment by reiterl** [comment]
@bastianjoel Can you verify this? How can we continue here?

**Comment by Elblinator** [comment]
This issue is incorporated in the issue #3552
