### ISSUE TITLE
Participants: Inactivity visibilty issues with new permissions

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3552]
**Description:** Some issues occur with the inactive attribute in the participants list. The icon for inactivity in the participant list or in the user details is not coherent shown/ not shown in relation to permissions. Also the filter doesn't work anymore for users which are not admins.

- [ ] Filter "Active" doesn't work anymore
- [ ] user with permission "Can see sensitive data" and "Can see participants" can't see inactive icon in list nor the user detail view of users who are inactive
- [ ] user with "Can update participants", "Can see sensitive data" and "Can see participants" can't see inactive icon in listing. Additionally they see a wrong inactive icon in the user detail view, for users, which are not inactive

**Reproduction:**
First four users are needed: User 1 in group Admin, user 2 in group staff, user 3 as delegate and user 4 as delegate

0. open the instance in two browser. log in as user 1 in browser 1 and as user 2 in browser 2
1. open a meeting
2. open participants in both browsers
3. as admin: set user 3 as inactive
4. open as admin the group permission page > grant staff in participants only "Can see participants"
5. as user 2: check, if you can see the inactive icon in the listing / detail view -> should not be visible (good)
6. as admin: grant permissions "Can see sensitive data" and "Can see participants" for staff
7. as user 2: check if icon is visible in the list and if the icon is visible in user detail view
8. as admin: grant permissions "Can update participants", "Can see sensitive data" and "Can see participants" to staff
9. as user 2: icon should not be visible in listing. Additional the active user - user 4 - is shown as inactive in the user detail view.

**What should happen:**
- If a user has the permission "Can see participants" the inactive icon in the list or in the user detail view should not be visible. 
- If a user has additionally "Can see sensitive data" he can see the activity icon in the list and the detail view
- If a user has additionally "Can update participants" he can update the activity of the user and see activity icon in list/detail view
- the activity filter option should work for all users that have at least the permissions "Can see participants" and "Can see sensitive data"
- open question: How should we handle the filter for users with permission "Can see sensitive data"

**Comment by reiterl** [comment]
I have tested the problem with a can_update user. See #3549 .

**Comment by reiterl** [comment]
In the meta/models.yml:
```
user:
 [...]
  is_active:
    type: boolean
    restriction_mode: D
```
In the autoupdate repo (internal/restrict/collection/user.go):
```
// User handels the restrictions for the user collection.
[...]
// Mode B:
//
//	Y==X
//	Y has the OML can_manage_users or higher.
//	There exists a committee where Y has the CML can_manage and X is in committee/user_ids.
//	X is in a group of a meeting where Y has user.can_see_sensitive_data.
//
// Mode D: Y can see these fields if at least one condition is true:
//
//	Y has the OML can_manage_users or higher.
//	X is in a group of a meeting where Y has user.can_manage.
```

This seems to be one problem.
