### ISSUE TITLE
Fix LoS - with active structure level countdowns when user is cleared

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3555]
**Description:** 
If an currently speaking user (with a structure level) is cleared from the list of speakers with an active speaking times widget, an error message appears in the console and the structure level countdown continues to count down

**Error message:** 
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/8452ac0f-4eb3-4633-9e34-53141b777ded)

**An additional Reproduction:**
1. create a new meeting 
2. create a structure level 
3. assign yourself the structure_level
4. add time value for the structure levels/activate structure level countdowns
5. project sth with a LoS onto the autopilot 
6. add yourself on LoS
8. start yourself
9. clear yourself (CLEAR not stop)
10. Error is thrown and countdown continues

I will update the ovverall description of the Issue 

**What should happen:**
Deleting a user with a structure level from the list of speakers (with an active speaking times widget) should not trigger an error message in the console.

**Comment by reiterl** [comment]
I have tested a bit. I found some strange error messages while clearing a question user sith a strlvl from the los, but not all the time. And they seems to have different causes. The problem above could be solved by adding a conditional to the speaker, I think.

**Comment by reiterl** [comment]
I failed to reproduce the problem today.
If I reload, I will see only the **NotifyService** console error.
I tried: the  steps, superadmin/meeting_admin, start the interposes question and clear then, add another user with structure level to the participants and use them, reload the docker.

**Comment by Elblinator** [comment]
A consistent reproduction of the Error I managed to create: 
1. create a new meeting 
2. create a structure level 
3. assign yourself the strucutre_level
4. add time value for the structure levels
5. project sth with a LoS onto the autopilot 
6. add your self on said LoS
7. start yourself
8. clear yourself (CLEAR not stop)
9. Error is thrown

Additional Bug: 
The time on the speaking times card continues to run down

I will update the ovverall description of the Issue
