### ISSUE TITLE
Filter in list-view: language switch needs reload to be active

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3580]
**Description**: If a user is in the contributions menu and sets the language from German to English, the English terms in the filter will only be visible after reloading. 

**affected menu in contributions:**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/1dc6a65b-f3fc-43ff-a4ec-2caf90133f22)

**Reproduction:**
1. open an instance and set your language to german
2. open a meeting
3. open participants > contributions
4. change language to german
5. check filter menu
6. If this don't work, do a reload after language switch to german. 

**What should happen:**
Switching the languages from german to english in the contributions menu should instantly change the terms in english.

**Comment by Elblinator** [comment]
From your screenshot it is visible that your openslides-version is old (sort and filter was switched; Now: sort is left, filter is right)

This also happens for other lists but only some of the filter options:
- participant-list
- agenda
