### ISSUE TITLE
Fix "change Password" option in participant-list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3591]
**Current behaviour:**
A meeting admin can navigate to the change password page from Orgaadmins, Accountadmins and Superadmins. 
If they try to change the password the following (or similar) message opens: 
```
Error: You are not allowed to perform action user.set_password. Missing permission: OrganizationManagementLevel superadmin in organization 1
```

**Reproduction:**
1. Create a normal meeting admin (important permission here is participant canUpdate)
2. have a superadmin, orgaadmin or accountadmin (or all) in the same meeting 
3. login as the normal meeting admin
4. try to change the password of one of the higher admins 
5. the error message appears

**Wanted behaviour:**
The Error messages are CORRECT. If a user is not allowed to change the password of another user, then the option to change the password should not be displayed.
A user in the same hierarchy as the other user is allowed to change the password
hierarchy of the admins: superadmin > orgaadmin > accountadmin > meeting admin

**Comment by reiterl** [comment]
I can reproduce the problem.

**Comment by reiterl** [comment]
The field `organization_management_level` is so restricted, that an operator with  canUpdate cannot see it. That leads to the failure here. I think it is a problem of the AU service.

**Comment by reiterl** [comment]
I have added an issue in the autoupdate service. After that issue is resolved we need to check here.

**Comment by Elblinator** [comment]
wait for (https://github.com/OpenSlides/openslides-meta/pull/91)

**Comment by Elblinator** [comment]
added needs investigation bc this bug needs testing after meta and autoupdate is updated

**Comment by Elblinator** [comment]
The wanted behaviour is fulfilled after changing the restriction mode
