### ISSUE TITLE
Last send mail: Info icon can be seen accross meetings without correct permission per meeting

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3596]
**Description:** If a user is part of several meetings and has different group permissions per meeting, he will see the last send mail icon accross all meetings, if he had the permission in at least one meeting. The information is somehow wrongly saved and available accross all meetings if the user has the permission to see the participant menu in a meeting.

**Reproduction:**
- needed: two meetings, same two users in each meeting 

1. open meeting A
2. Add user 1 to group "Staff" and user 2 to "delegates".
3. send user 2 an invitation mail. 
4. Login as user 1: User 1 should see now an icon in the participant menu. (correct)
5. open meeting B
6. Add user 1 and 2 to group "delegates".
7. Login as user 1: In the participant menu, the mail icon should be behind user 2. (incorrect)

**What should happen:**
The permission to see last send mail data should only be visible, if the user has the correct permission to see it.  This should based on group permissions per meeting.

**Comment by jsangmeister** [comment]
The client should hide the field if the operator does not have the required permission in the current meeting, even if the restrictor allows to see the field because of permissions in other meetings.
