### ISSUE TITLE
presence-detail view does not work (not implemented yet)

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#360]

**Comment by GabrielInTheWorld** [comment]
What is the "presence-detail-view"?

**Comment by FinnStutzenstein** [comment]
https://github.com/OpenSlides/openslides-client/tree/master/client/src/app/site/users/components/presence-detail

- must be enabled in the users settings (`meeting/users_enable_presence_view`)
- reachable with the three-dot menu in the user list
- presents an input form to enter a `user/number` and toggle the presence of this user.

IMO this requires a new action for OS4.

**Comment by GabrielInTheWorld** [comment]
I have added the new action `user.set_present_by_number` to the wiki: https://github.com/OpenSlides/OpenSlides/wiki/user.set_present_by_number

@FinnStutzenstein or @tsiegleauq  Please review and feel free to make adjustments yourself. Afterwards, an issue in the backend can be created.

**Comment by FinnStutzenstein** [comment]
Looks good; I changed one sentence.

**Comment by FinnStutzenstein** [comment]
Some more remarks:
- "number" is not clear: First, the `user/number_$` (with the meeting id as replacement). If there no user is found use `user/default_number`
- the `number` in the payload must not be empty
- Whats about duplicates? The number is not unique.

**Comment by GabrielInTheWorld** [comment]
> * Whats about duplicates? The number is not unique.

Therefore, I wrote 

> If a user can not be identified by the given number (because there is no user with this number in the given meeting and their default number is empty, too, or there are at least two users with the same number in the given meeting), return with an error and a suitable error-message.

**Comment by GabrielInTheWorld** [comment]
Related backend-issue: OpenSlides/openslides-backend#916
