### ISSUE TITLE
[Meta] Motion Forward: motion identifier not shown and Error thrown in console

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3605]
**Description:** 
When opening a forwarded motion from the original motion, the motion identifier is displayed incorrectly in the target event. Instead of "Motion 03", for example, "Motion not found" is displayed. 

At the same time, an error message appears in the console. I cannot say whether this is the cause or whether another error is occurring at the same time. 

**target meeting with wrong motion identifier:**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/25f7a530-1072-47ac-834b-6b8e0e49a29b)

**error message after forwarding:**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/3a12eddd-296d-4aeb-a003-36f1263df2b8)

**Reproduction:** 
0. Activate motion forwarding in two committees and create a meeting in each one
1. open console to see Error when it is thrown
2. open meeting A 
3. open motions > workflow > > complex workflow > allow forwarding in state approved
4. open motions > create a motion with workflow complex and as submitter "Test". 
5. change status of the motion to approved and forward the motion to meeting B
6. now open the target meeting by clicking on "Motion forwarded to" link
7. Error is thrown and title is wrong

**What should happen:**

- [ ] 1. The motion identifier should be readable after opening a forwarded motion from the original meeting (or reverse).
- [x] 2. The error message should not appear in the console. #3688

**Comment by Elblinator** [comment]
If I click on the link to move to the origin/forwarded meeting then I can reproduce the Error

I can not reproduce the first bug

I'll make a Meta Issue out of this and edit the description accordingly

**Comment by reiterl** [comment]
After the steps clicking on forward/origin shows the "not found" in Motion header. I don't see an error here.

**Comment by reiterl** [comment]
Stop here for now.

**Comment by Elblinator** [comment]
I cannot reproduce the 'Motion not found' part
Please clarify the reproduction

**Comment by MSoeb** [comment]
I've tried to reproduce it, but it works fine in the current OS version 4.1.9. 

Because of this, I've changed the issue text. The issue can now be closed after the second part of it is fixed and merged.

**Comment by Elblinator** [comment]
The first bug from the meta issue is still relevant I could reproduce it once 
I forwarded the motion and navigated vis the link to the forwarded motion white fast (maybe something was still loading)

**Comment by MSoeb** [comment]
I agree with you. Tried it again. I can reproduce it with one motion in our test environment, but it doesn't occur with every motion. Not sure, what exactly caused it the title loading bug.

**Comment by Elblinator** [comment]
the get errorMessage() in the detail-view.component.ts returns the string ("Motion not found") if the motion.number is not loaded while trying to access it
After this error was thrown once, the title never gets changed again

**Comment by Elblinator** [comment]
I could reproduce the bug rather reliably in a productive instance as follows: 
1. allow committee A to forward to committee B 
2. forward one motion
3. stay in meeting A 
4. hover with the mouse ovwer the link for meeting B 
5. reload the page with F5
6. press the link very fast until you navigated to the other meeting
7. The title is wrong now

I cannot reproduce it reliably in a dev environment ( autoupdateOnSharedWorker: true or false) tested in chromium

**Comment by bastianjoel** [comment]
I think I found the cause of this while working on #4023. 

In `MotionDetailViewComponent` the `hasLoaded` subject does not get reset properly in some cases on meeting change. It might be that this is more reliable reproducible when switching between three meetings via forwarded motion links while staying on the motion detail page. 

The cause could be that on motion switch the active meeting subscription gets unsubscribed too early. 

We should check if #4024 fixes this after it is finished.

**Comment by bastianjoel** [comment]
e4895ef22f57eb121d2a75b43c7c2e57dfa81d7d fixes this.

While this change is a bit off form the motion refactoring it does not work with current main because of other bugs within the motion component I will address in #4024
