### ISSUE TITLE
Editorial final version switch back to diff version after each autoupdate

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#3613]
To reproduce:
* create new motion
* set motion state to accepted
* create editorial final version
=> error 1: text should switch to created "editorial final version" view - diff version is shown instead
* select "editorial final version"
* click edit button -> edit form opens
* make some text changes (without saving)
* Now: open 2nd tab and create an autoupdate (e.g. set a user to present)
=> error 2: motion detail view in tab 1 is switched from "editorial final version" to "diff version"! Edit form is closed without saving! Expected: should keep the selected form open

Workaround for error2: 
go to motion settings and change "default text version" from "Diff version" to "Final version".

This issue is critial because you cannot work in final version editor as long as default is "diff version" (which is default during meeting). Each autoupdate breaks your work...

**Comment by reiterl** [comment]
I can reproduce the bug.

**Comment by reiterl** [comment]
The problem is triggered by the client commit 'd8376e603851ed4e7ae796de10fd8594e4431bc4'.
If I revert it, I don't see the problem anymore.

**Comment by reiterl** [comment]
The `os-motion-highlight-form` seems to be the main component for this issue.
The last commit on it seems to cause the bug. The last commit on it is a "bug" fix of #3139
