### ISSUE TITLE
Moderation note: availabilty for elections and motions

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3615]
**Description:** 
Moderation notes are currently only available for agenda items, not for motions or elections if they are not on the agenda.

**Reproduction**: 
1. open a meeting
2. open motions > create a motion > add it to agenda > project it
3. open Autopilot > moderation note visible
4. open motions > open the list of speakers of the motion > moderation note visible and editable.

**What should happen?**
I think that moderation notes should always be available for motions and elections, regardless of whether they are on the agenda. @emanuelschuetze What do you think?

**Comment by MSoeb** [comment]
No further discussion is needed. The moderation notes should be also available for elections and motions.

**Comment by luisa-beerboom** [comment]
Backend is done
Autoupdate not yet

As for what changes were made in the backend: 
- The `moderator_notes` field has been moved to the list_of_speakers collection. Setting/changing it will now have to be done via `list_of_speakers.update`.
- The related permissions have been moved from the `agenda_item` collection to the `list_of_speakers` and are now called `list_of_speakers.can_see_moderator_notes` and `list_of_speakers.can_manage_moderator_notes`
