### ISSUE TITLE
Meeting: closed meetings

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3622]
A new function for meetings is required that allows the meeting to be closed from the inside and NO admins other than the meeting admin have access to the meeting. Only the event admin can add new accounts to the meeting after it has been closed. 

This enables the creation of closed meetings.

**Comment by Elblinator** [comment]
We need a new setting in the meeting_level:
- -> the setting should be in General -> Meeting information -> on the bottom: a checkbox with the label „Close your Meeting from the inside“
- If a meeting is locked from the inside then only users with the permission to manage settings can edit Information about the meeting (meeting information include: Meeting title, Description, Event location, Meeting date, Administrators, Tags and External ID)
- Only participants from a locked meeting can navigate into the meeting
- Everyone (who can already see these meetings) can still see the meeting in the dashboard, meeting-list and committee-detail view, but the locked meeting has a locked icon left next to the meeting name

**Comment by Elblinator** [comment]
waiting for backend Issue with the new setting: https://github.com/OpenSlides/openslides-backend/issues/2497

**Comment by Elblinator** [comment]
also waiting for https://github.com/OpenSlides/openslides-meta/issues/119

**Comment by luisa-beerboom** [comment]
Attention: After further conceptualization, the backend will have additional changes, among them:
- [ ] `get_user_related_models` presenter has a new meeting info `is_locked` that will be true if the meeting is closed. It will not show data on meeting-internal models for closed meetings, unless the operator is part of that meeting
- [ ] `export_meeting` presenter will not work with closed meetings -> Disable meeting json export button
- [ ] `user.assign_meetings` action will not work at all-> Filter the meeting out of the selector

**Comment by Elblinator** [comment]
Additionally: 
Locked meetings won't be allowed to be templates and template meetings won't be allowed to be locked
The button to turn a meeting into a template/to lock a meeting should be disabled in the respective cases

**Comment by luisa-beerboom** [comment]
Backend is done for now, look at https://github.com/OpenSlides/OpenSlides/wiki/Permission-System and the changed wiki entries from the changes in the PR to see what changes were made

**Comment by Elblinator** [comment]
client-side: 
- meeting access should be prohibited 
- delete dialog when deleting an account > the dialog should say when a meeting is locked from the inside
- guards should not allow entry into meeting routes if the meeting is locked 
- organisation-level actions which would  change the meeting (add user to meetings) should not be usable
- operator.service should be adjusted to match https://github.com/OpenSlides/OpenSlides/wiki/Permission-System and the changed actions and presenter in the backend see (https://github.com/OpenSlides/openslides-backend/pull/2523/files)
