### ISSUE TITLE
Chyron enhancement: add agenda item

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3655]
**Description:** The chyron should be extended so that the projected agenda item can be displayed alongside the current speaker (with structure level). Both areas can be set in two different background colors. Before the projection, a projection dialog is activated which asks in which variant the chyron should be projected.

**Details:** 
- New Chyron: The chyron should be displayed in a single line. Format example: [Title] [First name and surname], [ Structure level]
- Projection dialog: The “Chyron - current contribution” projection button is converted into a dialog. Clicking on the button opens a new dialog. Three projection options should be selectable in the dialog. 1. old chyron, 2. new chyron and 3. the agenda item. The selection should be freely combinable. 
- New background color selection for new chyron and agenda item.

**Example Scenario: Selection of the new chyron plus agenda item.**
If there is a speaker for an agenda item, both are displayed. If there is currently no speaker, only the current agenda item is projected.

Further details can be viewed in the internal mockups.

**Comment by reiterl** [comment]
The current speaker chyron is a slide. The projectors/projections/slides parts seem to be generic built and I haven't
understand it completely.  I don't see land here.

**Comment by reiterl** [comment]
Please add the important mockups here. I don't have access to "internal mockups".

**Comment by reiterl** [comment]
Opened https://github.com/OpenSlides/openslides-backend/issues/2437 for the agenda item bg color.
Waiting on this to continue.
