### ISSUE TITLE
Indicator for projected countdowns

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3656]
**Currently:**
After #2912 is implemented 
If a countdown is projected on projector A and you are on the detail view of projector B then there is no visualisation that the countdown is already projected onto the other projector

**Wanted behaviour:**
If the countdown is projected then there should be an indicator that it is already projected elsewhere. 
The indicator should be the projector icon (directly behind the title) if you hover over the icon the a toolbox tells you where the countdown is projected

**Comment by bastianjoel** [comment]
It is currently already possible via the `Open projection dialog` to view where a countdown is projected. 

As the space is very limited there I think it might be better to integrate the info into the already existing button.
