### ISSUE TITLE
Fix projected timers

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3678]
**Current behaviour:**
- Timers in fullscreen mode overlap with each other
- "In the projector selection?"-dialog the display type and if the timer is projected as fullscreen or not is not remembered when opening the dialog again 
- A timer can overlap with the clock

**Reproduction:**
1. in the  projector-list edit your projector
2. activate "show clock", DEACTIVATE "show header and footer" and change the background colour to a colour where you can see the clock
3. navigate to projector-detail view 
4. create three timers with 1:30 minutes, 2 min and zero minutes
5. project two as fullscreen and display type "in Time and traffic light"
6. the timers are overlapping (see screenshot)
7. open the projection dialog of either of the timers 
8. the dialog saved on which projector the timer is projected but it does not save if it's fullscreen or the display type
9. project the third timer as not fullscreen
10. the timer overlaps with the clock (see screenshot)

**Screenshot:**
![Screenshot_20240516_083700](https://github.com/OpenSlides/openslides-client/assets/69210919/492e7a01-7167-4a42-9f9e-133da7e025d0)

**Wanted behaviour:**
- [ ] <s>Only one timer should be displayed in full screen mode. If one timer is already displayed in full screen then the option for full screen for other timers should be displayed and there should be a hint which explains that per projector only one timer is allowed in full screen</s> (Given that the discussed desired behaviour is that only one timer at a time should be displayed and this above described behaviour will hinder someone from projecting a timer, I will implement a slightly different behaviour): 
Only one timer should be displayed in full screen mode. If one timer is already displayed in full screen then and another timer is then projected in full screen then the new timer will overwrite the previous timer and there should be a hint which explains that per projector only one timer is allowed in full screen
 edited (15.07.2024) 
- [x] if a timer is currently projected and the edit dialog is opened then dialog should save if it's projected in full screen and the display type
- [x] If the clock is displayed (even without header and footer) the timer should not overlap with the clock

**Comment by Elblinator** [comment]
when you see the timer right next to the timer-title you can see the icon 'open_in_new'  pressing this icon will open the dialog where you can select the Display type

**Comment by reiterl** [comment]
Ah, yes, I can reproduce the overlapping times in 'Fullscreen'. It seems like that in the 'Default projector' the dialog is not filled fully.

**Comment by reiterl** [comment]
I have looked at it. The dialog seems to be a 'ProjectionDialogService' dialog. This is generic code, I could include  code to check for fullsceen and default `countdown` in 'openProjectDialogFor()'. But it feels not right, because it would mix levels of concerns.

**Comment by bastianjoel** [comment]
It might make sense to do a refactoring of how the countdowns are displayed on the projector. When doing this #2940 could also be taken into account.

**Comment by bastianjoel** [comment]
Saving options is not possible with the projection dialog as the options (although not possible with current UI) might differ between projectors. 

I would suggest removing the projector selection from the dialog. That way we would also enable users to project different timers with different layouts across projectors.

**Comment by bastianjoel** [comment]
For now I will implement this as described in the previous comment.
