### ISSUE TITLE
Fix active topic-poll in autopilot

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3698]
**Current behaviour:**
If more than one poll is currently running and you navigate to the autopilot then an Error is running through the console several times 
```
TypeError: Cannot read properties of null (reading 'fqid')
    at PollCollectionComponent.getPollVoteTitle (poll-collection.component.ts:109:85)
```

**Reproduction:**
1. create two polls (topic/motion/election)
2. start both polls 
3. navigate to the autopilot 
4. Error thrown

**Wanted behaviour:**
The error should not be thrown

**Comment by reiterl** [comment]
I can reproduce the error.
The error is thrown, because in poll-collection.component the method `getPollVoteTitle` cannot handle the "currentProjection is null" case.

**Comment by reiterl** [comment]
Add a small fix to correct it.
