### ISSUE TITLE
Allow committee admins to change personal information

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3702]
**Description:** 
Currently, account personal information data (e.g. name, e-mail address, gender) can only be changed by the Orgaadmin if the account is involved in several meetings and committees. The committee admin can only manage meetings, but not the members of a committee. This means that an Orgaadmin must always be available for meetings of a committee if, for example, an e-mail is to be changed.

**What should be changed:**
The committee admin should be given more rights: The committee admin should be allowed to edit all accounts that are part of the committee (i.e. all participants in a committee's events). Regardless of whether these accounts are also part of other committees and their meetings.

**Comment by MSoeb** [comment]
The committee admin should only see the accounts, which are part of the committee.

**Comment by reiterl** [comment]
Ah, okay, at the moment a committee admin cannot access the orga-wide account list. We need to change this.

**Comment by luisa-beerboom** [comment]
The `get_user_scope` presenter includes the committee ids necessary for the new scope calculation (i.e. ids of all meetings where the user is member or admin) as of OpenSlides/openslides-backend#2487

**Comment by reiterl** [comment]
A committee manager who is meeting admin cannot edit the email of a user which is in two meetings including a cm's meeting . Is this correct?

**Comment by Elblinator** [comment]
The functionality that committee-admins can change the personal information should work with the linked backend PR already

Feature from the client issue:
- The committee-admin should see the account-list (the shown accounts should be the accounts from the committee(s) and not more)
- Committee-admins inside their own committee(s) should be able to click on the amount of accounts and navigate to the account-list where only the meeting specific accounts are displayed
- There should not be a new filter/sort in the account-list

**Comment by MSoeb** [comment]
Please take care to implent the feature from the issue https://github.com/OpenSlides/openslides-client/issues/3791 for committee admins.

**Comment by rrenkert** [comment]
Please have in mind: https://github.com/OpenSlides/openslides-client/issues/3806
