### ISSUE TITLE
Fix date picker in meeting create/update

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3705]
**Current behaviour:**
If you edit or create a meeting and change the datepicker, the datepicker can open itself again 

**Reproduction:**
Tested in Chromium (Version 125.0.6422.76 (Official Build) built on Debian 12.5, running on Debian 12.5 (64-bit) )
1. Navigate to committee detail
2. create a new meeting 
3. open the datepicker
4. press cancel 
5. click on a different tab (push the current tab out of focus)
6. open the tab where you create a meeting again
7. the datepicker is open again

**Wanted behaviour:**
If the date  picker window was closed (via one of the three buttons or via clicking out of bound for the dialog) then the dialog should stay closed until the meeting date input is actively clicked again

**Comment by reiterl** [comment]
Ah, I can reproduce the problem with Chromium and Firefox (115.11.9). The base datepicker component has code, that
if the form element gets focus the picker is opened. This leads to the problem.
