### ISSUE TITLE
Add eslint rule for template attribute order

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#3709]
In the past we had issues with multiple structural directives in html templates after automatic merging. This could be prevented by requiring a specific order for attributes. 

Angular has an eslint rule for that which also support automatic fix: https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/attributes-order.md

As this will introduce a lot of changes this should be done when there are less PRs open.

**Comment by Elblinator** [comment]
waiting for #3706
