### ISSUE TITLE
Fix alignment of mat-chips in mat-cell

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3710]
**Current behaviour:**
The mat-chips are on top right of a mat-cell
![Screenshot_20240529_161533](https://github.com/OpenSlides/openslides-client/assets/69210919/b7078901-b039-44df-9ef9-1676ccfea39d)

**Reproduction:**
1. Create a category
2. Add a motion to the category
3. Open the category detail view look at the state

**Wanted behaviour:**
The matchips should be vertically aligned in the mat-cell

**Comment by reiterl** [comment]
I cannot reproduce this. I don't see a problem in the category-detail view concerning state.
mat chips are on the "left" side of a mat-cell.

**Comment by Elblinator** [comment]
Looking at top/bottom alignment the chip should be centrally aligned. 
The chip should be left.

I do not know what you mean with 'I cannot reproduce this.' is the chip differently aligned in your version?

**Comment by Elblinator** [comment]
waiting for https://github.com/OpenSlides/openslides-client/pull/3706

**Comment by Elblinator** [comment]
#3706 fixed this issue
