### ISSUE TITLE
User merge 

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3725]
The User merge.together functionality in the backend needs appropriate client implementations as well
See the backend PR here: https://github.com/OpenSlides/openslides-backend/pull/2427

**Mock-ups:**
![Board](https://github.com/OpenSlides/openslides-client/assets/69210919/646f56a1-5537-4698-9734-594097ec877f)

The merge should only be possible from the account-list

1. You select via multi-seelct the accounts you want to merge 
2. then in the three dot menu there should be the option to merge the selected accounts
3. dialog opens
4. you select the reference account, the data from this account will be used, every other data will be **NOT** used
5. the not selected account will be strike through (like the mock-up)
6. The name of the user should be shown like in a user-detail view
7. hovering over the number of meetings should open the toolbox and show up to 10 meetings, if the user is in more than 10 meetings then after 10 there should be a plus
8. hovering over the letter should show when the last invitation-mail was send (same behaviour as the account-list)
9. pressing merge will move all references from the selected accounts onto the same account and delete the now unused accounts
:mage:

**Comment by reiterl** [comment]
The user merge dialog should contain a warning, that in special cases the user merge action can lead to data loss.
