### ISSUE TITLE
Metatable background broken on dark projector

### ISSUE THREAD

**Issue by reesericci** [OpenSlides/openslides-client#3727]
When using a dark background on a projector, the metatable is unreadable due to it being hardcoded with a #ddd background. 

As a workaround, I compiled from source and changed the css to not have a background color in `client/src/app/site/pages/meetings/modules/projector/modules/slides/components/motions/modules/motion-slide/components/motion-slide/motion-slide.component.scss`

Screenshot (blurred motion text on purpose):

![image](https://github.com/OpenSlides/openslides-client/assets/19589006/72f02d1f-79ae-446b-b107-92217f6b285a)

**Comment by reiterl** [comment]
I can reproduce the problem.
