### ISSUE TITLE
Wrong behavior: Sorting/Searching of meeting and committee list is linked

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3750]
**Description:** The sorting and searching of the meetings and committees menus are linked. This can lead to the sorting/searching being carried over from one menu to the other. For sorting: As both menus offer different sorting options, an empty list is then displayed and an error message appears in the console. 

**Error message for sort:** 
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/62dbc508-0af3-47c4-89d0-fa549c700610)

**Reproduction for sort:**
1. open committees. create a committee and two meetings
2. open the committee list and sort it by 'amount of meetings'
3. open the dev-console
4. open meetings and reload the page
5. -> error and empty list appear

Reproduction for searching:
1. open committees. type 'test' in search and navigate to meetings. 

Hint: I'm not sure, if a committee and meetings are needed. Maybe a change of the sorting option is sufficient. 

**What should happen:**
The meetings and committees menus should be sorted/searched separately from each other. I assume that this would fix the error in the console and the empty list.

**Comment by reiterl** [comment]
I can reproduce it, the problem is wrong storage key strings of meeting list, fixed them.
