### ISSUE TITLE
Save poll choices in local storage

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3777]
**Currently:**
You can open a poll in several tabs and fill the poll differently and only send one (you should only be able to send one)

**Wanted:**
To prevent confusion or (accidentally) half-filled polls, One poll should be filled the exact same in the same browser over several tabs. How a poll is filled should be saved in the local storage

abstract example:
You should be able to open a poll in three different tabs; in tab 1 some options and then navigate in between tabs and every poll is filled the same. 
This should only be true for the same poll, you you open poll A and B in two tabs they should be independent from each other

**Comment by bastianjoel** [comment]
This sounds like unexpected behavior which in my opinion opposing to yours could cause confusion. I would also stress that your point "(accidentally) half-filled polls" is not valid because before sending the vote a dialog is displayed which tells you that you did not use all your votes.
