### ISSUE TITLE
Fix wrong behaviour of login button

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3785]
**Current behaviour:**
When opening Openslides if the login data is prefilled then the login button is grey, it should be blue

**Reproduction:**
In Chromium:
1. log into Openslides and save  the user data
2. log out and reload the page
3. the log data should be pre filled
4. the login button is grey and the cursor is wrong 
5. changing the focus makes the button turn blue and lets the cursor change icons

**Wanted behaviour:**
The button should immediately be blue and has the correct cursor

**Comment by bastianjoel** [comment]
Which browser did you use? 
With firefox this works fine. With chromium I need to type my username first before getting a selection. After selecting a user everything works fine.

**Comment by Elblinator** [comment]
I used Chromium

**Comment by Elblinator** [comment]
The action of logging in works fine independent from the colour of the button. But the button should have the correct colour even if the page is just loaded

**Comment by bastianjoel** [comment]
I tested this in chromium too. The button color war correct.

**Comment by Elblinator** [comment]
The bug was fixed by a PR in between
