### ISSUE TITLE
Add custom filter for meeting name > account-list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3791]
**current behaviour:**
If you are in a committee-detail view and see the listed meetings then you get an indicator of how many participants are in the meeting
![Screenshot_20240626_121643](https://github.com/OpenSlides/openslides-client/assets/69210919/c6ac8a66-c00d-4ed3-afa9-74dc2bd752c9)
![Screenshot_20240626_121655](https://github.com/OpenSlides/openslides-client/assets/69210919/34ce55a8-a980-4827-940b-afb1c901f49e)

If you click on the icon then you are navigated to the account-list, where you see every account

**Desired additional behaviour:**
Navigating to the account-list this way should automatically activate a filter which displays the name of the meeting, this filter is deletable like every other filter (via the individual chip or the "delete all filter" button)

**Comment by bastianjoel** [comment]
This is currently disabled intentionally because we had performance issues with that filter. 
We should keep this in mind when working on this.

**Comment by bastianjoel** [comment]
See: https://github.com/OpenSlides/openslides-client/pull/1424

**Comment by Elblinator** [comment]
> This is currently disabled intentionally because we had performance issues with that filter. We should keep this in mind when working on this.
> 
> #1424

This was mentioned while talking about this feature. 
Yes, we should remember checking the performance.
To be clear: The filter for the meetings should not be listed in the filter-list, the filter should only be activatable when navigating via this specific path to the account list
