### ISSUE TITLE
Add feature „lock participants out of a meeting“

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3793]
See https://github.com/OpenSlides/OpenSlides/issues/6756#issuecomment-2159989520 for reference

- [x] If locked out the participant is still in the meeting -> visible in the participant-list, and everywhere where they are on a LoS, are a candidate etc.
- [x] If locked out the participant cannot see or navigate via url to the meeting
- [x] A new filter/sort should be added in the participant-list
- [x] Who can see that a participant is locked out? -> canSeesensitiveData
- [x] A participant with the permission user.canManage can lock out
- [x] Who can NOT be locked out: 
    - [x] You from yourself
    - [x] (Meeting-) Admins
    - [x] participant with user.canManage permission
    - [x] Superadmins
    - [x] Orgaadmins
    - [x] Accountadmins
    - [x] Committeeadmins (but only from their own committees)
- [x] Who can be locked out: 
    - [x] Every User in a meeting who does not  have the permission participant.canManage
    - [x] Committeeadmins (but only from meetings where they are not committeeadmins)
- [x] It should be possible to change is_locked_out via participant detail view and the participant list (multiselect and three dot menu)

- [ ] What should happen if you try to assign a group with canManage permission to a locked out participant?
     - [x] You are told that this is a locked out participant and you cannot give this participant canManage rights until you lift the lock out first 
     - [ ] detail-view: after you assign the group you cannot save and a mat-hint should tell you that a locked out participant is not allowed to have user.canManage rights and you have to lift the lockout first

- [ ] What should happen you try to lockout a participant with canManage permission?
     - [x] You are told that this is a participant with canManage rights and you cannot lock out participants such participants until they lose this right
     - [ ] detail-view: The checkbox for locked out is disabled if the participant is in a group with canManage rights 
     - [x] three dot menu in participant-list: the checkbox is disabled

- [x] Imports: 
    - [x] the is_locked_out flag needs to be visible in
       - [x] the help-box
       - [x] the preview
       - [x] the example export
       - [x] the export

**Mock-up:**
Notes: 
The mock-up for the new feature 
- The red is supposed to be the warn colour
- The function of is_active did not change the placement was just moved unter the present checkbox
- The checkbox for locking_out is supposed to be in the three dot menu, only the indicator is outside
- The indicator in the participant-detail view should be behind the name and the additional information

**Comment by reiterl** [comment]
There are some tasks here to do. I will start looking at the components participant-detail and participant-list.
@bastianjoel  can you look at a way, how to do the lockout from the meeting?

**Comment by reiterl** [comment]
The lockout should be done in the autoupdate service.
The button to the lockout should be in the menu in the participant-list. It should not be a checkbox there, but a button which opens the what to do dialog (like in multiselect).
It should be possible, to use the button in mobile, too.
There should be a permission or isAllowed check, if a operator can set the lockout.

**Comment by luisa-beerboom** [comment]
Transfer from backend issue:
 - [ ] for bulk actions: 
        - [ ] every user who is not locked out should successfully be assigned the group
        - [ ] an error should be thrown which states sth along the lines of: ```X participants could not be assigned this group because they are locked out and locked out participants cannot have the permission to manage users```
        - [ ] every user who does not have the permission canManage should be sucessfully locked out
        - [ ] an error should be thrown which states sth along the lines of: ```X participants could not be locked out because they have the right to manage participants, remove this permission before trying to lock them out again```

This has to be handled by the client via the handle_separately route

**Comment by reiterl** [comment]
Talked with  @Elblinator 

We need a bulk action to set the lockout. The above comment is about this "bulk" action.
This bulk action should use the handle_separately route.

We want all seven checks for the disable in the participant-list. I will include the checks. It should not be a performance problem.

**Comment by reiterl** [comment]
@Elblinator Some points: 
 - "Committeeadmins (but only from their own committees)" 
   A Committee Admin is s.o. who is manager in at least one committee. This is the definition. Do you mean s.th.
  different?
- "(Meeting-) Admins" Do you mean MeetingAdmin? Or s.th. other? A MeetingAdmin is s.o. who is in the admin group of the current meeting.
-  Superadmin is subset of OrgaAdmin is subset of AccountAdmin, why do you have all in your list?

**Comment by Elblinator** [comment]
You can have two committees (A and B)
Someone who is the committee admin from A is a committee admin per definition.
But this someone is not the committee admin from every committee. 
You should be allowed and able to lock this user out from every meeting from committee B.

(Meeting)-Admin = someone who is in the admin group of the current meeting

You are categorically not allowed to lock out Account-Admins, Orga-Admins and superadmins. Please implement it that they are not allowed to be locked out

**Comment by MSoeb** [comment]
Additional change request: With the integration of the locked out feature, the tool tip of the group permission 'Can see sensitive data' needs to be enhanced. By updating the tool tip, please use the wording I've written in the issue #4030. Another information is missing. Both could be included with one change.
