### ISSUE TITLE
Autopilot > List of speakers: Missing names after reload

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3798]
**Description:** There is a strange error in the autopilot that hides the names of the users. When you reload the autopilot, it can happen that user names are hidden in the list of speakers and in the 'Last speakers' list. If you then hover over the X in the list of recent speakers, for example, the names will reappear. Unfortunately, I cannot say whether there is a system for hiding user names. It seems arbitrary. 

**Example of missing username in last speaker list**
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/3a18cf24-bdb5-4672-96c8-26cea8619f91)

**Reproduction:**
1. open the OS4 Demo > Meeting Bundeskonferenz 2024
2. open the Autopilot
3. Reload the page -> Usernames disappear
4. Open 'Last speakers' in Autopilot and hover over the X. Usernames appears again. Hover over the Play-Button -> Names will be visible again. 

Hint: Unfortunately, the problem can only be reproduced cleanly once after calling up the instance. To provoke it again, it sometimes works for me to reload the page with Ctrl+Shift+R. 

**What should happen:**
The list of speakers and the last speakers list should always display the usersnames after reloading the Autopilot.

**Comment by bastianjoel** [comment]
As this only happens in chromium I would suggest waiting with this until we have a recent angular version.

**Comment by bastianjoel** [comment]
Also the shared worker needs to be active.

**Comment by bastianjoel** [comment]
Still happens in some cases

**Comment by MSoeb** [comment]
Found a performance issue in the autopilot. Adding participants to the list of speakers doesn't work almost instantly anymore. It takes 1-2 seconds to add someone in comparison to the last version 4.1.13. - I'm not sure, if the fix of this issue is the reason for it. But it makes most sense.

Repro: 
Just add a participant to the LoS on staging and compare the time for the operation with the one in version 4.1.13.

**Comment by bastianjoel** [comment]
Performance issue was caused by our setup.
