### ISSUE TITLE
Meeting.create: make duplicate from (optionally) mandatory

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3804]
Context: The new setting from the Meta-Issue https://github.com/OpenSlides/openslides-meta/issues/125

**Desired behaviour:**

- [ ] The new setting should be a checkbox: Orga-level > general > last point
- [ ] The title should be „Activate require templates for creating a meeting"
- [ ] There should be a mat-hint „If this setting is active committee-admins can only create meetings from public meeting templates, to enable these admins to create a meeting you need to create a template meeting first“
- [ ] If the setting is activated then **committee admins** while creating a meeting:
      - should only see templates in the dublicate from field
      - the dublicate from field should be mandatory -> users should not be allowed to save without sth being selected in the form-field

**Comment by rrenkert** [comment]
Please have in mind: https://github.com/OpenSlides/openslides-client/issues/3800

**Comment by reiterl** [comment]
Checkboxes doesn't have mat-hint. I used a styled div instead.

**Comment by reiterl** [comment]
What should happen to a account admin (has OML.can_manage_users) and committee manager? They should be allowed to create meetings without restrictions, or?
