### ISSUE TITLE
Several Layout issues

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3811]
Description: Several layout issues occur. 

**Problems:**

Image: left side is Staging / right side is live
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/60b273bb-0ef7-4d57-b501-a6d9ffb0b816)
- [x] The bar in the navigation menu is in the wrong place. Apparently the spacing is no longer correct.  (This also occurs in meetings)
- [x] The distance between the active meetings is incorrect.

Image: Left side is staging / right side is live
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/f05738e3-bc33-4f86-b0ae-8d44c2a5039d)
- [ ] The matcard size of the meeting has changed. 
- [ ] The blue bar is also resized, which leads to a wrong positioning of the text. 

History:
- [ ] Position of the history matcard has changed. 

**What should happen:**
The original layout should be reestablished again.

**Comment by Elblinator** [comment]
Reproduction (there should be a shorter path to get this but I know of this one)
1. Navigate to election-list
2. create an election
3. add some participants
4. open the dialog to create a ballot but don't create teh ballot
5. closes the dialog
6. Navigate to settings > participants
7. Navigate to election-list
8. Navigate to settings > Motions
9. via the arrow from Openslides navigate to settings > Agenda
11. Navigate to dashboard
