### ISSUE TITLE
Fix comment-list appearance

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3838]
**Current behaviour:**
It is possible that the comment fields have the wrong appearance

**Reproduciotn:**
1. motion-list > three-dot-menu > comment fields 
2. create a comment-field (the comment-field should have the full length of the screen minus the menu left)
3. navigate to a motion-detail-view
4. via the Openslides arrow navigate back to the motion-list > comment fields
5. the comment fields are now smaller (770px)
6. reload page 
7. comment fields are again full length

**Wanted behaviour:**
The comment fields should always have the full length

**Comment by reiterl** [comment]
I tried to reproduce this problem, but cannot use a OS back arrow to navigate from motion-detail to comment fields. @Elblinator Please check if it is still there.

**Comment by Elblinator** [comment]
This Issue was fixed by probably https://github.com/OpenSlides/openslides-client/pull/3839
