### ISSUE TITLE
MDC Component: Hint texts not aligned

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3840]
**Description:** With the update of the MDC components, the position of the gray help texts under checkboxes has changed. The text is now aligned with the click frame of the checkbox and no longer with the edge of the checkbox. 

**Old styling image:**
![screenshot-testintern staging openslides com-2024 07 11-16_20_35](https://github.com/OpenSlides/openslides-client/assets/105491030/2537dd18-66cd-46bc-8b0e-7ee5532be5a9)

**New styling Image:**
![screenshot-client3706 staging openslides com-2024 07 11-16_20_55](https://github.com/OpenSlides/openslides-client/assets/105491030/7adfb8d5-323f-454d-b15b-01c6b6185c5e)

**Repro:**
1. open meeting
2. settings > list of speakers > countdown > first checkbox with gray help text

**What should happen:**
The help text should start at the old position again.

**Comment by reiterl** [comment]
I look at the picture and see, that the help texts start in both in the same position.
The layout of checkbox and its text are changed!
And this is not a mat-hint component I suppose.

**Comment by MSoeb** [comment]
Thanks for your reply. To make it more specific.

The gray text should start at the left edge of the checkbox and not at the left side of the circle frame around the checkbox.
Alternatively, if it's more easy, the gray text could start aligned with, in this example, the beginning of the word 'Countdown'. It would also be fine.
