### ISSUE TITLE
Strange behavior in Group menus

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3866]
**Describe the bug**
On the staging instance, there are loading errors in the groups menu. 

In the group menu, I had multiplied the groups automatically after approx. 4-5 hours of running the instance. This led to very slow loading times. There was also the phenomenon that the group list briefly displayed the correct, small number of groups and then switched back to the view with a large number of groups. 

**How to Reproduce**
Group problem: 
The group problem unfortunately only as a picture. Ctrl+Shift+R did not solve the problem. Groups seems to work currently, but I'm not sure, that it will work permanently. 

![image](https://github.com/user-attachments/assets/542b867d-6063-4f29-bee5-1f6bb408fe6a)

**Expected behavior**
Group menu should not evolve and create more groups on it's own. ;)

**Comment by reiterl** [comment]
Mmh, I cannot reproduce this issue, because I cannot wait 5 hrs. I looked into the code of 'os-group-list', but didn't find a problem there. What do you do in the 5-6 hrs? Waiting or saml stuff or importing of a lot of participants with groups?

**Comment by MSoeb** [comment]
I've done testing other pull requests on the instance. After the given time I've recognized, that something went wrong in the group menu.  

But nevermind, the staging server is closed and the update 4.1.13 is done. Hopefully the issue won't appear again on live servers. Maybe it was caused by other problems on the staging server. 

Therefor I will close this issue.
