### ISSUE TITLE
Strange behavior in File-list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3871]
**Describe the bug**
On the staging instance, there are loading errors in the file. 

In the file menu bis a file that hidden at irregular intervals and reappears after a short time. 

**How to Reproduce**
~~Mediafiles:~~
1. ~~Navigate to the mediafiles~~
2. ~~upload a file~~
3. ~~open a new tab~~
4. ~~navigate to motion-list > motion~~
5. ~~create a poll~~
6. ~~the mediafile in the other tab vanish until a new sutoupdate from the mediafiles come in~~

**Expected behavior**
Files should not be appear and disappear.

**Comment by Elblinator** [comment]
This seems to be fixed https://github.com/OpenSlides/openslides-client/pull/3839

**Comment by bastianjoel** [comment]
This is reliable reproducible like this:

1. Open meeting mediafiles
2. Open another tab
3. Upload orga mediafile
