### ISSUE TITLE
Poll detail view: new filters and bar chart

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3899]
**Current behavior**
In addition to a yes, no or abstention nominal vote, there may be various quorums that must be met additionally for some votes. For example, it may be the case that a) a majority from a certain present group or structure level must have voted with yes and b) a weighted majority from this pool must have voted with yes. Neither scenario can currently be visualized or easily read out of the data. Adjustments are required to make this possible.

**Wanted behavior**
The following features are required in the poll detail view to make it easier to recognize the necessary majorities in nominal votes on motions:

1. A filter with two filter options (by structure level and groups) should be added to single votes (See image: lower red mark)

2. Furthermore, a new horizontal bar chart should to be inserted above the table. 
The bar chart should be visible if one (or more) filters are activated
We want to use  form the that visualizes the (weighted) number of votes and percentages for yes/no/abstain vote based on the filtered list. Below the bar chart, the corresponding number of ballots cast (in other words the unweighted number of persons entitled to vote) for yes/no/abstention is shown. (see image: upper red mark)

With these features both desired quorums can be read off.

![image](https://github.com/user-attachments/assets/48bae96c-1b4b-4e8b-a338-ee15990dd08d)

**Comment by Elblinator** [comment]
![5296353923839419387](https://github.com/user-attachments/assets/03961b88-4adf-4358-843d-185ef2f1ec9d)

**Comment by Elblinator** [comment]
The bar chart should not be handmade but be called by the method which creates the pie chart (but it should be called as a bra instead)

**Comment by Elblinator** [comment]
It is possible that only part of the information can be automatically created by the method. 

The third line (2    2    2)  can be called manually, same goes for "Votes in total: "
