### ISSUE TITLE
Motion PDF Export: bullets points in existing motions can't be exported directly

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3915]
**Describe the bug**
If an existing motion on our test instance has bullet points, only the first level will be exported in the pdf file.
If the motion is edited or newly created with bullet points, all sub-level bullet points are correctly exported.

**How to Reproduce**
I'm not sure how to reproduct this, because it has happened after an update and I can't reproduce it with new created content. After editing an old motion or creation of a new motion this doesn't occur. Please contact me, so I can show you the problem. 

**Expected behavior**
Existing motions with bullet points on more than one level should be exported correctly. 

**Additional context**

Motion content:
![image](https://github.com/user-attachments/assets/d938cdb8-30d0-4d56-b264-1ad95541c3da)

PDF Content with missing data:
![image](https://github.com/user-attachments/assets/78ca047c-762e-4b92-b56a-205c09cbdf8f)

**Comment by Elblinator** [comment]
This is an artifact which only occurs if a motion was created in between the current (4.1.13) update. 
If someone created a motion in this in between state pleases open the motion ad a letter to the text, remove said letter again and save the motion. This will fix the in between state
