### ISSUE TITLE
Motion PDF Export: Export Snackbar misses text

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3916]
**Describe the bug**
If a motion is exported, the snackbar misses the text "Creating PDF file ...". See the image below.

correct behavior:
![image](https://github.com/user-attachments/assets/557e6e6b-983a-484f-97dd-407bb173985a)

wrong behavior:
![image](https://github.com/user-attachments/assets/646fb39a-17fc-4dcc-b6e0-f93eb970b833)

**How to Reproduce**
1. open a meeting
2. open motions
3. create a motion
4. open the motion
5. export the motion as single PDF file via three-dot-menu and look at the snackbar on the bottom of your screen

**Expected behavior**
The snackbar should show the text "Creating PDF file ..." again.

**Additional context**
This also effects multiselect export. Please take care, that this also should work for multiselect export.

**Comment by reiterl** [comment]
I can reproduce this. It is just a small thing we could do, if nothing to do. So "low".
