### ISSUE TITLE
Motions > Workflow > simple workflow: Deletion not possible

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3930]
**Describe the bug**
If a meeting admin wants to delete the simple workflow in a meeting, it can't be deleted, because it still has a reference to the statute amendments and the process will stop with an error message.

Error Message: 
"Fehler: You cannot delete the workflow as long as it is selected as default workflow for new statute amendments in the settings. Please set another workflow as default in the settings and try to delete the workflow again."

As the statute amendments are no longer available in the program, the required setting cannot be made and therefore the Simple Workflow cannot be deleted.

**How to Reproduce**
1. open a meeting
2. open settings > motions > workflow: Change both options to complex workflow > save
3. open motion > three-dot-menu > workflows > try to delete the simple workflow. -> error message

**Expected behavior**
It should be possible to delete the simple workflow without getting restricted by a feature which isn't part of OpenSlides anymore.

**Comment by MSoeb** [comment]
May be this issue gets solved by https://github.com/OpenSlides/openslides-backend/issues/2053

**Comment by reiterl** [comment]
Tested with the pr of https://github.com/OpenSlides/openslides-backend/issues/2053
In a new meeting, after changing the default motion workflow and the default motion amendment workflow I could delete the "Simple Workflow". So this needs a retest after the remove statute pr is merged.

**Comment by Elblinator** [comment]
This issue was fixed by the removal of the statutes: 
https://github.com/OpenSlides/openslides-backend/pull/2506
