### ISSUE TITLE
Improve client group matrix

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#394]
Gray out and check permissions that are "inherited" based on https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/permission.yml. Maybe add a tooltip saying e.g. "Included in `agenda_item.can_manage`" when hovering over `agenda_item.can_see`.

Related to https://github.com/OpenSlides/openslides-backend/issues/851 to make the UI nicer for a user, so he sees which perms a group additionally have.

**Comment by jsangmeister** [comment]
Precondition: generate a json/typescript file from https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/permission.yml which can then be used to calculate implicit permissions and gray out fields.

**Comment by jsangmeister** [comment]
Ah right, forgot that this issue existed.

> Maybe add a tooltip saying e.g. "Included in `agenda_item.can_manage`" when hovering over `agenda_item.can_see`.

Do we want to add this? It seems sensible to me.

**Comment by tsiegleauq** [comment]
> Do we want to add this? It seems sensible to me.

Would imply that we also generate (literally, even) the condition for the tooltip and the tooltip message. Might be a struggle to translate. Otherwise we might simply add a hint that this permission was implied by another permission. I'd probably await feedback from customers before adding this.

**Comment by GabrielInTheWorld** [comment]
What is the status here?

**Comment by jsangmeister** [comment]
Just noticed as well that I'm still assigned here. The "greyed out" part is done, the only thing missing/to be discussed are the aforementioned tooltips. Maybe we can discuss this later, but I don't think it has high priority.
