### ISSUE TITLE
Anonymous user

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3955]
see for context: https://github.com/OpenSlides/OpenSlides/issues/6798

**Wanted behavior**
Login mask: 
- [x] below the internal login should be a button with "Login as guest" as text
- [x] If this button is pressed the anonymous user should be:
   - If only one meeting is public -> should be navigated to the public meeting
   - If more than one meeting is public -> should be navigated to the dashboard, where every public meeting is display 
  
General: 
- [x] If you are using OpenSlides as a anonymous... In the top right corner 
  - The icon next to your name should be "no_accounts"
  - The displayed name should be "Anonymous"
  - the "My profile"-Option should be hidden
  - The "Logout" button should have the icon "Login", and if pressed you should be navigated to the login page "..../login"

Orga-level as an anonymous user: 
- [x] Only "Dashboard" should be visible
- [x] In the dashboard every meeting which is public should be displayed

Meeting:
- [ ] Settings:
   - There will be a new setting after Locked from inside (https://github.com/OpenSlides/openslides-client/pull/3869) is merged
   - This (this issue) new setting to allow anonymous users should be below locked_from_inside
      - it should be a checkbox 
      - the label (for now) should be "Allow anonymous users"
      - There should be a hint below this setting, the hint should be as follows:
         - If the anonymous group has no permissions at all: "The anonymous group will become visible at the url:  '##/participants/groups', please configure what your anonymous users are allowed to see"
         - If the anonymous group has one or more permissions: "The anonymous group is at url:  '##/participants/groups'. Your anonymous group is already allowed to see some of your contents, please configure the permissions according to your liking"
   - Locked_from_inside and make a meeting public should **NOT** be allowed to be true at the same time 
     - a locked meeting from the inside is not allowed to be public 
     - a public meeting is not allowed to be locked from the inside
     - If one checkbox is activated and the other is empty the empty one should be disabled, if both are (somehow) activated at the same time neither should be disabled
- [ ] Group-Matrix with the new anonymous group:
  - The group should only be visible if the setting "Allow anonymous users" is activated
  - Guest-group is only allowed to have reading-permissions, every writing permission should be off and disabled

**Additional context**
- we also have the new setting to lock a single participant out (https://github.com/OpenSlides/openslides-client/pull/3815). That setting can be active while a meeting is public --> these two settings are independent from each other

**Comment by Elblinator** [comment]
For now the client will not display archived meetings if they are public and you are a guest

We have to discuss whether or not archived meetings should be allowed to be public. 
The backend is currently not preventing archived meetings to be public and vise versa. If this becomes a requirement, then the backend's requirement will be updated, same goes with this issue

**Comment by bastianjoel** [comment]
> The backend is currently not preventing archived meetings to be public and vise versa. If this becomes a requirement, then the backend's requirement will be updated, same goes with this issue

This is not correct. Archived and also active meetings are currently in restriction Mode B and therefore NOT public. See https://github.com/OpenSlides/openslides-meta/issues/140 for more details on how this needs to be changed.
