### ISSUE TITLE
Fix jitsi information update for a closed_meeting

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3980]
**Describe the bug**
If a meeting is closed from the inside and a superadmin tries to change the Jitsi domain, Jitsi room name or Jitsi room password, then the following Error is thrown: 
```
Error: The user needs Permission user.can_update for meeting ##
```

**Repo:**
1. Close a meeting from inside
2. Login as a superadmin who is not in the meeting
3. Navigate to the edit view from this meeting
4. add information to the jitsi options
5. save
6. error is thrown

**Wanted behaviour:**
The superadmin should be allowed to change these three fields even if a meeting is locked from the inside

**Additional context**
I assume that the action:user.update should not be in the payload
**Payload:**
```
[
  {
    "action": "meeting.update",
    "data": [
      {
        "jitsi_domain": "domain name",
        "jitsi_room_name": "name for room",
        "jitsi_room_password": "very secure password",
        "id": 354
      }
    ]
  },
  {
    "action": "user.update",
    "data": [
      {
        "id": 1,
        "meeting_id": 354,
        "group_ids": [
          1897,
          1895
        ]
      },
      {
        "id": 9,
        "meeting_id": 354,
        "group_ids": [
          1895
        ]
      },
      {
        "id": 7243,
        "meeting_id": 354,
        "group_ids": [
          1894,
          1895
        ]
      }
    ]
  }
]
```

**Comment by peb-adr** [comment]
The quick fix for now should be to send only not send a `user.update` action for unchanged user information.

This should avoid the error and make it possible to change jitsi information even for closed meetings.

@rrenkert suggests that this implies a bigger discussion that we will not dive into at this point.
