### ISSUE TITLE
Accounts: User deletion from filtered meeting list doesn't work properly

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3982]
**Describe the bug**
When deleting a user from a filtered meeting list, a loading error occurs. Although the user has been removed from the meeting, he is still displayed. After reloading the page, the user is no longer displayed. I suspect an autoupdate problem.

This problem occurs currently only on the staging instance.

**How to Reproduce**
0. Required: A committee with two meetings (A and B). The meetings should have the superadmin as admin and two user as delegates.
1. open committees and open the filtered participants list of meeting A
2. in the filtered list: open three-dot-menu > multiselect > mark one user > three-dot-menu > set/remove meeting > remove user from meeting A
3. The user should now still be visible in the list. > Reload > User is gone.

**Expected behavior**
By removing a user from a filtered meeting list via multiselection, the action should be instantly without a reload visible.

**Comment by reiterl** [comment]
In step 1. How do I open a filtered list of meetings in the committee-detail view?

**Comment by MSoeb** [comment]
You can access it by clicking on the small participant icon. -> see the image. I've marked it red.

FYI: This opens the meeting participant list in the Account menu. The filter can only be opened in that way. A filtered list of meetings can't be opened via Account menu directly. 

![image](https://github.com/user-attachments/assets/8600a540-0c9d-473e-9e67-d19e1f1be4a7)

**Comment by bastianjoel** [comment]
`meeting.user_ids` field is not subscribed from autoupdate.
