### ISSUE TITLE
Closed meetings: Account detail view needs info about closed meetings

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3988]
**Current behavior**
All meetings in which a user is participating are listed in the account detail view. There is currently no indication if the meeting is closed or not.

Example - Last meeting is closed without any indicator.
![image](https://github.com/user-attachments/assets/cdc04639-9717-44e3-a158-725d2cfc35f0)

**Wanted behavior**
A lock icon should be added in front of the name of a meeting to make closed meetings recognizable. The size of the symbol should be based on the font size of the meeting name. The lock icon should be similar to the one used in the calendar.

**Additional behavior**
Please take care of public and archived meetings. Both types of meetings have individual icons, which should be used in the user details.

**Comment by Elblinator** [comment]
The link should additionally have the same colour as the groups if the admin cannot enter the meeting

**Comment by Elblinator** [comment]
The icon should be in front of the meeting name the icon should be black

**Comment by MSoeb** [comment]
Added an additional behavior
