### ISSUE TITLE
Account/Participant import: wrong behavior of 'is_active' checkbox

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4011]
**Describe the bug**
When importing accounts or participants, there is a problem with the value 'is active'. If no value is entered in the csv file, then after the import the user is listed as active and inactive at the same time in the Account/Participant detail view. On the one hand the symbol for inactive is displayed, on the other hand the checkbox for 'is active' is marked. The user visually has both statuses at the same time. 

Practical effect: The negative impact is moderate as the user cannot log in. The account is correctly set to inactive.

Example of inactive Symbol:
![image](https://github.com/user-attachments/assets/6a97514b-e068-46ff-9955-030068abd968)

example of same account with marked checkbox.
![image](https://github.com/user-attachments/assets/9ae0c699-5a24-4947-b714-117ec10dc790)

**How to Reproduce**
1. open an instance
2. open accounts > three dot menu > import > download the example file > edit the file with a new user. remove value for 'is active'. leave cell empty > import the data  
3. open the account list and open the user details. you will see the is inactive symbol > open the edit mode. the checkbox for 'is active' is marked.

**Expected behavior**
If no value is entered in the csv file for 'is_active', than the account/user should be imported as active. The checkbox and icon should follow this logic.

**Comment by Elblinator** [comment]
The backend implements the new default as described in this issue 

I would however recommend not to retroactively change this behaviour (change the users with is_active: `null` to is_active: `true` )

If a user has is_active: `null` in their profile then they cannot login and if they try to then they get the Error message that their account is deactivated.
Given that this is the behaviour from the already created users I propose representing `null` in the same manner as `false` in the client and migrating the preexisting users to is_active: `false`

**Comment by Elblinator** [comment]
to be able to test this behaviour the client needs to be fixed before the backend:
https://github.com/OpenSlides/openslides-backend/issues/2579
