### ISSUE TITLE
Group permissions: 'Can see sensitive data' tool tip misses information

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4030]
**Current behavior**
The tool tip of the group permission 'Can see sensitive data' misses information about data a user could see with it. Membership number and locked out state is missing.

**Wanted behavior**
Please change tool tip to "Can see email, username, membership number, SSO identification and locked out state of all participants".

**Additional context**
Feature #3793  must first be integrated so that the text can be customized.

**Comment by reiterl** [comment]
I changed the text in the #3815 pull request. Please check.
