### ISSUE TITLE
Chromium Browser: Files didn't open in new tab

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4032]
**Describe the bug**
Files are no longer opened in a tab in Chromium browsers, but are offered for download instead. In comparison, files (here a pdf file) are opened in a new tab in Firefox.

No settings have been changed proactively in Chromium. However, it is unclear whether this is a settings problem or a bug. It is also unclear whether other browsers are affected by this misbehavior. 

**How to Reproduce**
1. open an instance in a chromium browser 
2. open Files
3. upload a pdf file
4. try to open the pdf file

**Expected behavior**
If possible, files should always be opened in a new browser tab first and not downloaded directly. This should be the general behavior regardless of the browser.

I know, not all file types are supported to be opened in a browser. Please take care, that at least images and pdf files could be opened. 

**Additional context**
Tested in Brave Version 1.68.141 Chromium: 127.0.6533.120 (Offizieller Build) (64-Bit)](https://brave.com/latest/

**Comment by bastianjoel** [comment]
This is intended behavior and cannot be changed for security reasons. 

We consider uploaded content as not trustworthy. With our current setup files are served on the same origin as the application which could grant some file types privileges we really don't want them to have.
