### ISSUE TITLE
Add 'Default poll method' for motions

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#4043]
**Current behaviour**
Since https://github.com/OpenSlides/openslides-client/pull/3979 a motion poll can be method YN and YNA

Waiting for: https://github.com/OpenSlides/openslides-backend/issues/2578

**Wanted behaviour:**
Like the elections the motion polls should have a selectable default poll method

The new setting should be above the motion setting "Default 100 % base"

**Comment by luisa-beerboom** [comment]
Backend PR exists: OpenSlides/openslides-backend#2590
