### ISSUE TITLE
Login-Screen: unclear error message in console

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4045]
**Describe the bug**
If you reload the login screen, an error message is displayed in the console.

![image](https://github.com/user-attachments/assets/555b4567-aa34-4405-8869-e906bd6a12c2)

**How to Reproduce**
1. open an instance > stay at the login page without login in
2. open the console
3. reload the page

**Expected behavior**
Console error should not appear.

**Comment by reiterl** [comment]
I cannot reproduce this. If I go to the login screen and press on reload, *no* error message is thrown.

**Comment by MSoeb** [comment]
#4108 - same problem?
