### ISSUE TITLE
Voting: Flickering when voting

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4070]
**Describe the bug**
Flickering occurs durign voting. The best way to recognize it, is via vote delegation. After confirming the vote, there is a brief flickering between the buttons and the confirmation. However, this does not occur every time. Therefore, several transmitted votes are required to reproduce it in a meaningful way. 

**How to Reproduce**
1. open a meeting
2. active vote delegation
3. create 10 users as delegates
4. delegate their vote to yourself
5. open motions > create a motion > create a poll with admin and delegates as entitled vote groups and start it. If you're not present, set yourself as present. Try voting and check the flickering.

**Expected behavior**
No flickering should occur after voting has been completed. The confirmation of the vote should appear immediately.

**Additional context**
If you need further information, please contact @emanuelschuetze

**Comment by bastianjoel** [comment]
Talked to @emanuelschuetze who said that the buttons sometimes do not disappear after they were hidden for a brief moment and appeared again.

**Comment by bastianjoel** [comment]
Only happens for users who can see the "Received votes" bar.
