### ISSUE TITLE
Vote delegations get cut off on participant detail page

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-client#4088]
**Describe the bug**
Vote delegations get cut off on participant detail page.

**How to Reproduce**
Add vote delegations to participant

![Screenshot_20240905_131730](https://github.com/user-attachments/assets/dbdb8f50-27f0-4809-8501-80e4af217922)

**Comment by Elblinator** [comment]
**Wanted behaviour:**
the whole text should be shown and not information should be cut of by an ellipsis
