### ISSUE TITLE
Fix display of most current Nomination list (election polls)

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#4094]
**Describe the bug**
The most current election poll displays a too big list (double the items)
![Screenshot_20240909_120321](https://github.com/user-attachments/assets/1db7e6fe-f386-414d-8727-3997016391fa)

**How to Reproduce**
1. create a new election
2. put a candidate onto the candidate list 
3. create a poll with voting method: Yes/No/Abstain per list 
4. Nomination list has empty items
5. create a new poll with voting method: Yes/No/Abstain per list
6. The newest polls nomination list has the same problems the old one(s) are correct again

**Expected behaviour:**
The nomination list should only display the candidates

**Comment by reiterl** [comment]
It seems to be a wrong use of the 'for ... track...' in the template.
