### ISSUE TITLE
Orga Media files: edit of file title or folder name leads to error

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4135]
**Describe the bug**
If a user wants to edit the title of media file or the name of a folder on orga level an error occurs. The edit is not saved. The action is aborted.

![image](https://github.com/user-attachments/assets/75a45a8f-50b4-485f-9acf-89041166028e)

![image](https://github.com/user-attachments/assets/11ccd8fd-4797-422a-b699-629f48e776b3)

Payload:
[
  {
    "action": "mediafile.update",
    "data": [
      {
        "id": 353,
        "title": "asdf2",
        "meeting_id": null
      }
    ]
  }
]

**How to Reproduce**
1. open Files on orga level
2. upload a file
3. edit the title of the file -> error occurs 
4. create a folder 
5. edit the title of the folder -> error

**Expected behavior**
Changing a folder name or a file name should be possible.

**Comment by luisa-beerboom** [comment]
The problem is twofold: 
1. The client sends "meeting_id": null
2. The backend doesn't throw a verbose error

I'll fix the latter in the backend, someone will have to fix the client
