### ISSUE TITLE
Vote delegation / vote weight - several optimizations

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4154]
The vote delegation and vote weight feature needs some optimizations to be more user friendly. I will list the individual requirements below.

**A) User Detail view lacks in a good overview layout, if a user has several vote delegations.** Example image: The user has more than three vote delegations, but after three it is not possible to read them. 
![image](https://github.com/user-attachments/assets/5bc36a4d-eb25-40a6-ab4d-8b28a1c3bf78)
--> Solution: Voting delegations are shown in a numbered list below each other. 

**B) Participant list: The total amount of vote delegations is not readable.** 
--> Solution: The suitcase (red mark) should get a number with the total amount of vote delegations per user. 
Image example which suitcase is meant: 
![image](https://github.com/user-attachments/assets/efa0f870-f0cc-437a-9c19-5346b8758771)

**C) Participant list: If a user has vote delegations, the total amount of vote weight is missing.**
--> Solution: The gray vote weight information should be enhanced with information about the total amount of vote weights given per delegation. Example line "Vote weight: 1 plus (amount) voting weight from transferred votes."
Example which line is meant:
![image](https://github.com/user-attachments/assets/6853c63a-9953-40d4-b2b9-67277610587a)

**D) Participant list > Add new Filter 'Entitled to vote'.** 
The options for this filter should be 1.) 'is entitled to vote' and  2.)' is currently entitled to vote'. 

**E) Enhance information text in Participant list >  gray information text if filter in D is active.** 
If the new filter of D is active, there should be an information about how many rights to vote are given and the accumulated value for vote weights. This values should also change, if multiselection is used. The gray help text on the left side to filter and sort options should display' X of Y (Rights to vote 'value', accumulated vote weight 'value')'. Please take care, that this interacts with vote delegations. If a user has a vote delegation with a vote weight, this should also be accumulated. 
Note: This information should only be displayed for the new filter. For all other scenarios the information should not be visible.
 
**F) Visualization of vote weight in participant list needs to be improved and new help text for vote weight setting is needed**
Current status: All person are displayed with vote weight 1, if the vote weight option in activated. This is irritating and not helpful, because not all users are entitled to vote.
Solution: The vote weight in the participant list should only be displayed for users which are in an entitled to vote group given by the settings of agenda, motions and elections. For all other users, which are not in a corresponding group, the vote weight should not be displayed. Additionally the vote weight setting should get a new help text: "The vote weight will only be shown in the participant list for participants which are in a default vote group".

**Comment by Elblinator** [comment]
After a discussion we decided the following, these are just additions to the descriptions: 
A)
 The menu should be a numbered list
The ten first delegations should always be displayed
If there are more than ten, then the eleventh (and upwards should be hidden/collapsed. The function should be list similar to a mat-expansion-panel or the comments/personal notes in a motion detail view) 

B) 
The number should be behind the delegation names
The number should only be displayed if there is an ellipse 
The number describes the total amount of delegations

C) 
The used string should be "Vote weigh: # + ##sum-of-delegations
The sum should be the total sum of delegations regardless of filters and settings 

D)
The string "X of Y (vote weight: #)" should be changed to "X of Y (accumulated votes: #, accumulated vote weight: #)"
partly still in discussion:
either) 
in the three dot menu is a checkbox which if activated changes the string
or) 
There is a new filter 
title:  'Entitled to vote'.
two option:  'is entitled to vote' and 'is currently entitled to vote'
'is entitled to vote' only activates the string display
'is currently entitled to vote' activates the string and filters like "is present" does

E)
Information text: "X of Y (accumulated votes: #, accumulated vote weight: #)"
"X of Y" stays as it is
"accumulated votes: #" ==> is the sum of unique votes which could be submitted by everyone in the list
"accumulated vote weight: #" ==> is the sum of all the unique votes from the accumulated votes
(meaning that if a principal and their proxy are in the list then the vote of the principal is only counted once and not twice)

F)  
vote weight should be hidden (participant-list and participant-detail) if a participant is is none of the default poll groups
