### ISSUE TITLE
User Profil > setting "Disable connection closing on inactivity" doesn't work anymore

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4158]
**Describe the bug**
The setting "Disable connection closing on inactivity" doesn't work anymore. The purpose of this function is that tabs will be always active and didn't fall into a disconnection sleep mode by inactivity. This doesn't work anymore. The tabs will fall in a permanent disconnection mode. Only reload will bring them back to life. 

**How to Reproduce**
1. open an instance
2. open the user profile > settings > mark 'Disable connection closing on inactivity'
3. now open the module 'meetings' in a new tab and wait until the tab disconnects for inactivity. 

**Expected behavior**
Discussed the topic a bit with @emanuelschuetze and @rrenkert and it's not clear what should be the optimal solution to solve this.
Option 1: Delete the setting, because tabs came back to life in quite a short amount of time.
Option 2: We fix it and it works again as intended.

**Comment by bastianjoel** [comment]
I cannot verify this. "Disable connection closing on inactivity" works as expected. The feature does not prevent pausing connections after a worker restart as this would lead to performance problems.

The described problem sounds more like other connection problems maybe cause by other browser functionality. Logs from console would be helpful for such cases. 

But as there is no issue with the disable connection closing feature I am closing here.
