### ISSUE TITLE
Motion with amendments projection - paragraphs are displayed double

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4159]
**Current behavior**
The current state of the motion with amendments projection has improvement potential. If a motion has several amendments, with changed in different paragraphs, the projection will show at first the first amendment with all it's changes and than the second and so on. This leads to the strange situation, that the projection of the content start by line 1 till the end of the first amendment and start again by line 1 with the second amendment. Addtitionally the projection doesn't show the number of the amendment nor if amendments are in conflict. This needs to be improved, because in complexe amendment scenarios it is hard to distinguish in the projection which amendment is now shown and it's irritating to see the prjection start again with line 1.

**Wanted behavior**
The projection should follow the same layout logic like the motion detail view. There it is easy to spot amendment conflicts and information about the current shown number of the amendment. 

**Additional information:**
This occurance that the whole motion is shown and not paragraph by paragraph sometimes happens and sometimes is doesn't. I always needed a motion with 3+ paragraphs and creating an amendment which changes several paragraphs was a good way to recreate the problem

**Comment by Elblinator** [comment]
After talking about the concept:
- General motion/amendments projection: the projection should be paragraph driven and not amendment driven, meaning that e.g. the first _paragraph_ should be projected as motion/amendment 1/ amendment 2/ etc. and then the second, third .... 
- the same warn icon should be projected as it is in the motion-detail
- The amendment nr should be projected in the same line as the icon (if there is no nr then only the icon is projected
- The amendment status should not be projected
- The icon and Nr should be indented in the same way as they are displayed in the motion-detail
- If an amendment has no icon and no Nr then the word "Amendment" should be projected 
- If reasonably possible in this issue the submitter from the amendment should be behind the Nr

**Comment by Elblinator** [comment]
For the bug part I'll link the Meta-Issue https://github.com/OpenSlides/openslides-client/issues/2956 with this Issue 
And update the title

**Comment by MSoeb** [comment]
Please don't work on it, until @Elblinator has added a clear reproduction.

**Comment by Elblinator** [comment]
This specific bug is not reproducable anymore 
I'll close this Issue, if the same or a very similar bug reappears please create a new Issue
