### ISSUE TITLE
WLAN data projection with strange interaction

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4179]
**Describe the bug**
If the WLAN data is projected in the standard projector, the Autopilot shows an additional motion poll result, if one is available.

Example of wrong behvaior:
![image](https://github.com/user-attachments/assets/f3369ca8-d915-4c36-9198-31c8e706675b)

**How to Reproduce**
1. open a meeting
2. open settings > general > wifi > add values for WLAN name and password > save
3. open motions > create a motion > create a poll > vote and publish it
4. open projector > detail view of standard projector > messages > project wifi data
5. open Autopilot: WLAN data and last poll should be visible

**Expected behavior**
If the WLAN data is projected, it should only show the WLAN data in the Autopilot nothing more.

**Comment by reiterl** [comment]
I can reproduce it. The showPollCollection function allows to show polls. I'm working on a patch.
