### ISSUE TITLE
Motions > Editor: empty paragraph line leads to wrong behavior in amendments

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4181]
**Describe the bug**
If a text in the editor contains an empty paragraph - set with Enter - this has an effect on amendments. Amendments that are placed on an 'empty' line are assigned line 0. In addition, the paragraph set in the editor is not visible in the motion. It is only visible in the editor or in the amendment creation screen.

Image of line 0 amendment:
![image](https://github.com/user-attachments/assets/0ab4e25e-e7ab-4bdf-b9bb-516065eea6c6)

**How to Reproduce**
1. open a meeting
2. open motions
3. create a motion which includes a paragraph set by enter
4. create an amendment to it and choose the empty line
5. --> Amendment should have now line 0 as base.

**Expected behavior**
If a paragraph is set in the editor using Enter, then this paragraph should also be visible in the motion and have the correct line numbering. It should also be possible to create a change request in this line.

**Additional context**
In OpenSlides 3 this was solved in the editor with a no-break space ( &nbsp ). 

Important: In the editor, however, it should still be possible to create a line break with SHIFT+ENTER that does not create a new line numbering. It is only about a line break with Enter.

**Comment by bastianjoel** [comment]
Could you please further specify what the "correct line numbering" should be?

**Comment by MSoeb** [comment]
> Could you please further specify what the "correct line numbering" should be?

Note: All images from OS3. 

Example image how a Text with an intented line done with ENTER should look like. 
![image](https://github.com/user-attachments/assets/10e8b707-0c53-4b94-8d06-fbfc2901cc55)

Editor view:
![image](https://github.com/user-attachments/assets/44a7198d-7e01-4223-adb9-c7605b6cce70)

Editor code view:
![image](https://github.com/user-attachments/assets/b1616b7f-1400-4622-b07f-ad8e8c0218ad)

In comparision a line done with SHIFT+ENTER. The gap is visible, but a new line numbering is not provided. Short: Enter = line numbering vs. SHIFT+Enter = no line numbering 
![image](https://github.com/user-attachments/assets/7207c403-b5dc-4c71-8b1f-c5f80aee1c96)
