### ISSUE TITLE
PDF Projection: only page 1 is projected

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4184]
**Describe the bug**
The projection of a PDF File doesn't work correctly. If a PDF file contains more than one page, only the first page can be projected. The other pages are not visible. 

**How to Reproduce**
1. open a meeting
2. open Files > upload a PDF file with more than one page
3. project the PDF file

**Expected behavior**
The whole PDF File should be projectable and scrollable.

**Comment by reiterl** [comment]
I can reproduce it. It seems that the page property of the slides is always 1, I didn't find the way, how this page should be set. I assume the projector button dialog needs to set it. I didn't find a BuildDescriptor for mediafiles. So no idea.
I stop here.
