### ISSUE TITLE
Fix global search markers

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#4197]
**Describe the bug:**
Sometimes there is a < mark >... < /mark > displayed when you use the global search

**How to Reproduce**
1. Create a meeting (I chose committee and meeting name "gggg")
2. Open global search 
3. Search for the meeting name 
4. Search for meeting titles
5. Marker  is displayed
![Screenshot_20240930_155906](https://github.com/user-attachments/assets/26431444-a364-44c1-a160-ea474a2b2e42)

**Expected behavior**
the tag should not be displayed

**Comment by Elblinator** [comment]
found in https://github.com/OpenSlides/openslides-client/pull/3965

**Comment by reiterl** [comment]
Yes, sometimes this happens. I can reproduce it.

**Comment by reiterl** [comment]
I added a possible fix for meeting and committees in breadcrumb.
