### ISSUE TITLE
Public Access: Add a new setting for global activation

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4204]
**Current behavior**
The new public access feature misses an additional setting for the superadmin to activate/deactivate the public access globally. 

**Wanted behavior**
A new setting should be placed on organization level in settings > Superadmin settings > under 'enable chat globally'. Name of the setting should be 'Enable public access globally'. By activating it, the option to set a meeting as public access should be avaible in any meeting. If deactivated, the setting in the meetings should not be visible.

**Comment by luisa-beerboom** [comment]
The new setting in the organization is also called `enable anonymous`.
The field should be used to hide the guest button in the login mask if it is not true.

@bastianjoel @m-schieder I cannot evaluate what changes would be needed in the auth service, if any, but I can imagine that we may want all anonymous users to be thrown out if the setting is turned off.

By the way, wouldn't it be better to leave the meeting setting visible and allow the user to manually turn it off if it was turned on before the the organization setting was turned off?
