### ISSUE TITLE
Structure level: unwanted automatic translation

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4209]
**Describe the bug**
A structure level with the name 'Support' has an unwanted translations in the participants filter menu. 'Support' will be translated to 'Unterstützen' in the german client.

Structure level name:
![image](https://github.com/user-attachments/assets/dac88891-4e04-4457-9ce7-44addf419b63)

Filter:
![image](https://github.com/user-attachments/assets/6088e8e3-381a-461b-901f-9c60c04ea4f7)

**How to Reproduce**
Steps to reproduce the behavior: Use a german OS client
1. open a meeting
2. open participants > structure level > create a structure level with name 'Support'. 
3. open participants > filter > structure level > Filter is translated to  'Unterstützen'

**Expected behavior**
Automatic translations should not translate structure level names.

**Comment by Elblinator** [comment]
Additionally group names should not be translated either

**Comment by reiterl** [comment]
I can reproduce the problem. I think in os-view-list all filter options are translated. I have no quick fix for this.
