### ISSUE TITLE
Login-Screen: error messages in console

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4214]
**Describe the bug**
Several error messages appears in the console on the login page. Also I get this error messages on the password reset page.

![image](https://github.com/user-attachments/assets/34b0b0d9-643a-4da2-bebb-84860da3a400)

**How to Reproduce**
1. open an instance URL and the console -> reload the page. 

**Expected behavior**
Error messages should not appear.

**Comment by reiterl** [comment]
I can reproduce this problem.

**Comment by reiterl** [comment]
The problem is, that isCommitteeManager is called for a anon user, and the operator hasn't got a user Object.
So I added a check, that an anon user cannot be committee manager.
