### ISSUE TITLE
Fix display/error messages for public access if vote delegations are activated

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#4225]
**Describe the bug**
Following Error is in the console if logged in with a public access:
```
ERROR TypeError: this.getMeetingUser is not a function
    at zx.vote_delegations_from_ids
```

**How to Reproduce**
1. Activate vote delegations and activate "Restrict delegation principals from adding themselves to the list of speakers"
2. Delegate a vote from one user to another
3. Activate public access for the meeting, activate all permissions (which are possible) for the public access
4. Project a motion/topic/motion block or election
5. login as with a public access
6. navigate to the autopilot
7. Error is in the console, sometimes the content is not projected

**Expected behavior**
The Error should be prevented and the content should be projected

**Comment by reiterl** [comment]
I can reproduce a problem here, @bastianjoel wants to look at it. So I have assigned him here.
