### ISSUE TITLE
Fix redirect if a user is locked out

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#4235]
**Describe the bug**
Sometimes a user is not correctly redirected if they are locked out of a meeting

**How to Reproduce**
1. Have a user (B) in several meetings (uncertain if that is a requirement but it is far more likely to happen with several meetings)
2. With one browser login as user B
3. Navigate to any page (except the autopilot)
4. Make a reload/Make a hard reload
6. With another browser login as an admin and lock out B 
7. The page "You are not supposed to be here." is shown instead of the wanted redirect
8. IF you do a normal reload in the home then the content in the mat-card and the menu left vanishes and you need to reload to be able to navigate somewhere else

**Expected behavior**
B should immediately be redirected

**Comment by reiterl** [comment]
Your issue description mixes user A and user B.

**Comment by Elblinator** [comment]
This Issue will be closed in favour of https://github.com/OpenSlides/openslides-client/issues/4404
