### ISSUE TITLE
public-access: add an indicative header for requests that are made by guest users

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-client#4241]
**Current behavior**
Not the following. (lol)

**Wanted behavior**
The following:

When a user accesses a meeting publicly (i.e. clicks the "public access" button) all following requests should add an http header indicating they are indeed accessing publicly.
Consequently as soon as the users logs in the header should no longer be set.

**Additional context**
This will make it easier to separate and prioritize requests and take action on that, e.g. route them differently.

**Comment by peb-adr** [comment]
Name proposal: `X-Public-Access: true`

**Comment by bastianjoel** [comment]
Status is currently set by a cookie which is sufficient for now. Using a header would have the benefit that we could set this just for api requests and not for requests to client assets.

**Comment by peb-adr** [comment]
Not needed atm. Closing ...
