### ISSUE TITLE
User Profile: Presence status can't be set by participants

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4251]
**Describe the bug**
Currently it is not possible to change the presence status via user profile. Users can't set themselves as present in a meeting

**How to Reproduce**
1. open a meeting
2. open setting > participants > activate 'Allow users to set themselves as present'
3. open participants > add yourself to the meeting
4. open user profile and try to set yourself as present

**Expected behavior**
If the setting 'Allow users to set themselves as present' is activated, users should be able to set themselves as present in a meeting. 

**Additional context**

**Comment by reiterl** [comment]
I can reproduce this. The component is 'os-account-button'. Somehow the view user in this component is not
updated after the autoupdate service response.
