### ISSUE TITLE
Request to speak list is empty

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4271]
**Describe the bug**
The requests to speak list in the imprint is empty. 

![image](https://github.com/user-attachments/assets/c79784b0-2560-4b68-b464-5829718263e2)

**How to Reproduce**
1. open a meeting
2. open agenda > create an item
3. open participants > create a user with a structure level
4. project the agenda item
5. open Autopilot > add user to list of speakers > start and stop the speech
6. open the imprint > Requests to speak > check the list

**Expected behavior**
The Requests to speak list should list all structure levels with it's accumulated times.

**Additional context**

**Comment by reiterl** [comment]
It seems that the subscription `meeting_info_<nr>` doesn't work like expected. I tried to change the subscription without success. I think @bastianjoel needs to help me here.

**Comment by reiterl** [comment]
A user in a meeting can have n structure levels.
The request count does count speakers and time.
In general speakers don't have a connection to a structure level.
So this issue is **not** solvable in general.

**Comment by reiterl** [comment]
As @Elblinator found out: In **parlament** mode (special meeting setting) there could be a connection between speakers and structure levels.

**Comment by reiterl** [comment]
@rrenkert Please evaluate, how to continue here.

**Comment by rrenkert** [comment]
Talked to @MSoeb: We see the problem here and maybe we want to implement a bigger solution with some more statistics. Please stop here and wait for futher information.

**Comment by MSoeb** [comment]
Further information about wanted behavior:

- [ ] The listing is always meeting related
- [ ] If a user is in more than one structure level, the spoken time is counted for ALL structure levels
- [ ] If a user has more than one structure level and he has spoken for one of it, which can be chosen via parliament mode) it should count only for the spoken structure level.

**Comment by reiterl** [comment]
With " If a user is in more than one structure level, the spoken time is counted for ALL structure levels" you mean that all structure level of a user of a speaker "gets" the full time, or a divided time or what?
Why should that in parliament mode differ?

**Comment by MSoeb** [comment]
Scenario A - without parliamentary mode activated: User A has the structure levels ABC, DEF and GHI and parliamentary mode is not active. 
Example 1: User A is on the list of speakers and speaks for 1 minute. Now all structure levels are active, because without the active parliamentary mode it is not possible to select for which structure level to speak. So the time counts separately for all structure levels. ABC is credited one minute, DEF is credited one minute and GHI is credited one minute.
Example 2: For user A, the structure levels DEF and GHI are temporarily removed. He speaks ONLY for ABC. In this case, only ABC is credited with one minute.


Scenario 2 - active parliamentary mode: User A has the structure levels ABC, DEF and GHI.
Example 1: The user is placed on the list of speakers. In the list, you can now select the structure for which the person is speaking. If for ABC, then the time counts for ABC.
Example 2: NO outline level is selected for the user when parliamentary mode is activated. In this case, the time must NOT be allocated to all outline levels, as this would distort the statistics. With parliamentary mode activated, speaking times must be recorded correctly per structure level. In this case - without selecting the outline structure level - the speech would have to be assigned to a for example 'dummy structure level'.

**Comment by reiterl** [comment]
Szenario A1, 2.1, and 2.2 should work with my pr.
The problem with A2 is, that in non-parliament mode, we don't save a connection between speaker and structure-levels and need to use the current values of a user. That means A2 cannot work at the moment. Perhaps we can think about this in another issue, which gets into concept?

**Comment by reiterl** [comment]
This issue does not include requirements about special styling or sorting.
