### ISSUE TITLE
Projection flickers during content updates

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4274]
**Describe the bug**
The projection of for example a list of speakers flickers, if an update is done in on the list. 

**How to Reproduce**
1. open a meeting
2. open agenda > create an item > project it
3. open projector > create a new projector and project the list of speakers on it
4. open autopilot and add two participants to the list of speakers
5. now you need a split screen: 1. screen = Autopilot and 2. screen = Projector of list of speakers
6. Add/create several new participants to the list of speakers, start/stop speeches. Do this until you see the projection flickers.

**Expected behavior**
All projections should not flicker, if the content is updated or an action, like start of speeches, is performed.

**Additional context**
We've debugged, that the PR https://github.com/OpenSlides/openslides-client/commit/499591b4109cb8be99002ba1440c2cc4ce65157d#diff-a4d0ddc1485ef4d7f10c88c159b740682c0fe2b9d0aa76019a92a4e29fcca9a8 is the reason for this.

**Comment by reiterl** [comment]
I can reproduce sometimes a light flicker in the projection with the steps.
