### ISSUE TITLE
Motion creation has an error

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4290]
**Describe the bug**
There is an error when creating a motion.  After entering the title and text, the save button is not activated immediately. You must first enter something in the reason so that it can be saved. It is not important that something has to be in the reason, the field only has to be used once for the save button to become active.

**How to Reproduce**
1. open a meeting
2. open motions > create a motion > enter title and enter motion text > save button is inactive > enter something in the reason > save button is active

**Expected behavior**
It must only be possible to save motions by entering the title and text. 

The only restriction: If 'Reason required for creating new motion' is activated in the settings, it is necessary to enter a reason for saving.

**Comment by Elblinator** [comment]
The reason could be that the submitter is not loaded fast enough.Clicking on the reason could potentionally force this load. But I am not sure myself

**Comment by bastianjoel** [comment]
This only happens when typing mess than two letters or pasting and then not interacting any further with the motion text input.
