### ISSUE TITLE
Motion menu: Error message appears with a specific set of group permissions

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4291]
**Describe the bug**
If a participant has the group permissions 'can see motions' and 'Can manage motion metadata' an error appears by opening the motion list or a motion.

error message: Fehler: You are not allowed to perform presenter get_forwarding_meetings Missing permission: motion.can_manage

error message in console: Error: The presenter service has returned a wrong format

I'm not sure, if this has negative impace except of the message. I've tried to change meta data and it worked. 

**How to Reproduce**
1. open a meeting
2. open participants > groups > grant delegates the permissions 'can see motions' and 'Can manage motion metadata'
3. open motions > create a motion
4. open participants > create a new user as delegate
5. login as the delegate and open the motions menu

**Expected behavior**
The error messages should not appear and the set permissions should work properly.

**Comment by reiterl** [comment]
I can reproduce it. It seems to be a small problem.
