### ISSUE TITLE
Voting: Change of presence problem - buttons didn't appear 

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4305]
**Describe the bug**
If a user first sets himself to present during an ongoing vote, the voting options are not immediately visible. The user must either open a different menu or reload the website. 

**How to Reproduce**
Steps to reproduce the behavior: An admin and another user (A) as delegate is needed
1. open a meeting
2. open motions > create a motion > create a poll with admin and delegate as groups who could vote
3. open in another browser the instance and log in as user a > open the autopilot. IMPORTANT: User should not be present and the user should have the option to change the presence state.
4. [as admin] start the poll
5. [as user A] you should see now the running poll, but oyu can't vote, because you are not present. -> change your presence state in the user profile menu > you are now able to vote, but the buttons didn't appear. you have to open the motion or relaod the autopilot to see them

**Expected behavior**
If a user changes his presence state during a running poll (or all other voting types) the voting options (buttons) should immediately appear. This should work in all menus, where a user could have the possibility to vote.

**Comment by reiterl** [comment]
I can reproduce a broken behaviour with the step-by-steps.
There is a banner with "click here to vote" -> click on it doesn't work.
The voting buttons are not shown in the autopilot.
