### ISSUE TITLE
Vote weight visibility bug

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4360]
**Describe the bug**
If participants have the 'Can see participants' permission, they can see the vote weight of other participants as well as existing vote delegations. Unfortunately, they cannot see the voting weight value associated with the vote delegations in the list of participants. The 'Can see sensitive data' permission is required for this. This makes no sense. 

Information in red sqare is missing 
![image](https://github.com/user-attachments/assets/0f105883-83b9-4c11-8f88-a0e151081518)

**How to Reproduce**
1. open a meeting
2. open settings > participants > mark settings 'Activate vote weight' and 'Activate vote delegations'
3. open participants > create two participants (A and B) as delegates. Delegate voteing roght from B to A.
4. open group permission matrix and grant delegates the permission to see participants
5. Login as user A > open participants

**Expected behavior**
Participants who have the “Can see participants” permission should also receive information about the transferred vote weight in the list of participants.

**Comment by reiterl** [comment]
This seems to be also a good first issue.
