### ISSUE TITLE
Elections > export: Fix display of numbering of candidates

### ISSUE THREAD

**Issue by bspekker** [OpenSlides/openslides-client#4398]
**Describe the bug**
In the export of an election with >9 candidates, the column with the numbering of the candidates in ballot results is limited to one digit, resulting in linebreaks within numbers >9.

**How to Reproduce**
1. create an election
2. add 10 candidates to list of candidates
3. create new ballot (all voting methods except Y/N/A per list) 
4. start and end voting
5. export election
6. position 10 in list of ballot is broken into two line "1" and "0"

**Expected behavior**
Column width allows for numbers >9

**Comment by reiterl** [comment]
I can see a translation bug here, the code tries to translate `undefined`. (`assignment-pdf.service.ts:265`)
I can also see the broken display of 10th or 11th candidate.
