### ISSUE TITLE
Motion creation: Add free text submitter field and committee selection field

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4405]
**Current behavior**
During motion creation it is not possible to add a free text submitter. After creation it is possible to add a free text submitter.

**Wanted behavior**
As admin or as a participant with can manage metadata and can create motion permissions it should be possible to enter a free text submitter during motion create . To implement this, the existing components in motion metadata should be used. This should include the 'Extension' and 'Committee' fields. After integration persons with corrcet permissions mentioned above can enter free text submitters or choose a free text submitter from the committee field. The behavior should be the same like in the motion metadata.

The free text field and the committee field should be placed between submitter and title.
![image](https://github.com/user-attachments/assets/49716001-2cf4-474e-af04-3b8364f21783)

important: 
- A setting should be integrated in Settings > Motions, that allows to activate/deactivate the free text submitter field as well as the committee field in the motion create mask. The default value is deactivated. 
- The existing submitter creator field and the free text field should interact with each other. One of the two fields must be filled in. Example: If no text is entered in the free text field, the account creating the motion is set as the submitter. This is the existing behavior. If ONLY the free text field has a submitter and NO submitter is selected in the other field, then the account is not automatically set as the submitter. 
- The new fields 'Extension' and 'committee' should be in on line under 'submitter' field. The extension field should be wider than the committee field. 
- Committe field: Please take care, the box can have long terms. If this happens, a side scrollbar appears, which is is the current state only half visible. This should not happen. Bar should be fully visible.

**Additional context**
The added content (submitters) should behave like the existing component. The added submitters are free text, which will not create accounts.

**Comment by luisa-beerboom** [comment]
Related question: The backend already allows for this, but currently fills in the calling user as the submitter if no ids are given. From what I can see, this does ignore whether text submitter is given, so even if there was a text submitter, currently the one who physically created the motion will still be submitter.

Is this the desired behaviour? If not, can you create a backend issue?

**Comment by MSoeb** [comment]
Thank you for your message. When clarifying the details, we noticed that the issue needs to be rewritten. I will include details of your request in the issue.
