### ISSUE TITLE
Meeting > User create: issue with present status during user creation

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4419]
**Describe the bug**
If you add a user to a meeting or create a new one, the presence status is always set to absent. It does not matter whether the presence checkbox was checked in step 3 or not. 

When debugging with Loki, we noticed that the attendance is not sent when referencing. See picture.
![image](https://github.com/user-attachments/assets/de1b5983-b125-4137-9ea7-56adc3fb4d43)

Something is sent during the new creation, but this has no influence on the presence status. See image.
![image](https://github.com/user-attachments/assets/91da65d2-3c9f-48af-8462-94fb23b69c32)

**How to Reproduce**
1. open a meeting
2. open participants
3. create a new user. uncheck and check presence state during creation. > check presence state after creation.
4. Add a new user by referencing an existing user. presence checkbox should stay marked -> after creation the user is not present 

**Expected behavior**
1. when creating or referencing users in a meeting, the presence checkbox should not be checked by default. 
2. if the presence checkbox is checked, the user should be created as present.

**Comment by reiterl** [comment]
I can reproduce it. I have looked into the code. It seems that presence set mechanism is not in participant-controller in the create method. Hmm...
