### ISSUE TITLE
Public access deactivated > login button still available on login page

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4424]
**Describe the bug**
If public access is deactivated globally but is still active in a meeting, a login button for public access is displayed on the login page. Clicking on the login button opens an empty dashboard.

**How to Reproduce**
1. open a meeting -> set the meeting to public
2. head to orga level > settings > deactivate the public access
3. logout > check the login page. 

**Expected behavior**
When deactivating public access at organization level, the feature must be completely deactivated and no login button must be available on the login page.

**Comment by reiterl** [comment]
I cannot reproduce this with main commit 3f5227277

**Comment by MSoeb** [comment]
@reiterl You are right. I've tested it again with the current version 4.1.22 and the bug doesn't occur anymore. Therefor I will close this issue.
