### ISSUE TITLE
Motion > Amendments: deletion of bullet point/paragraphs is not recognized as change

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4451]
**Describe the bug**
If a bullet point or paragraph is completely deleted with a new amendment, this deletion is not recognized as an amendment. After saving, it is displayed that no change has been made. The crucial point is, that amendment which are created in this way show have no changed content and therefor the information of the change is not available anymore. 

Here an example for bullet points.

original motion content:
![image](https://github.com/user-attachments/assets/a502ecd9-6cf6-4043-b677-9362ba1d1285)

view of bullet point before editing:
![image](https://github.com/user-attachments/assets/36e11e75-27db-4d3f-bca3-af0631705298)

view of bullet point after edit:
![image](https://github.com/user-attachments/assets/7087ff29-5355-438e-b8a3-d1af931f6965)

amendment view after save:
![image](https://github.com/user-attachments/assets/475dc402-f700-48c0-80c8-0dfca763a0f3)

**How to Reproduce**
1. open a meeting
2. open motions > create a motion with one paragraph and three bullet points
3. create amendment to the second bullet point and delete the whole content > save
4. Amendment is now empty.

**Expected behavior**
If an amendment deletes a bullet point or a paragraph completely, the amendment should be displayed correctly. Specifically, this means that the bullet point or the paragraph is crossed out in red. 

This is part of the Meta diff Issue #2956

**Comment by MSoeb** [comment]
Changes:
- extended to paragraphs
- added high label

**Comment by emanuelschuetze** [comment]
I found the problematic pr which caused the error:
https://github.com/OpenSlides/openslides-client/pull/3667
