### ISSUE TITLE
Export of elections and topic polls does not work

### ISSUE THREAD

**Issue by bspekker** [OpenSlides/openslides-client#4463]
**Describe the bug**
If an election has a completed ballot, the election cannot be exported. Same for topics with polls.

**How to Reproduce**
1. create an election with at least one candidate
2. create a ballot
3. start and stop voting
4. export the election --> Error in console:

![image](https://github.com/user-attachments/assets/a9de82e6-d02b-466b-829e-597285c678ab)

For topic polls:
1. create a topic
2. create a topic poll
3. start and stop voting
4. export topic --> Error:

![image](https://github.com/user-attachments/assets/1d16b967-fe7b-47e3-8086-359c3725c7eb)

**Expected behavior**
Export of election with completed ballot and topic with poll works.

**Comment by reiterl** [comment]
Election: in AssignmentPdfService (assignment-pdf.service.ts:265) the translation is called with `undefined`. This leads to this error message. There was an update of the translation lib and service. Perhaps the new translation service is more strict.

**Comment by reiterl** [comment]
In agenda (topic-pdf.service.ts:175) this seems to be the same problem.

**Comment by reiterl** [comment]
A possible solution without fixing the translate service would be to filter the singleResult without vote in getPollResult.
