### ISSUE TITLE
Sending votes with too few candidates

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#452]
From #446

If there is an election with a minimum number of votes greater than the number of persons, who can be voted for, I cannot send my votes. I don't know if this is a bug...

**Comment by FinnStutzenstein** [comment]
I think, if you have to vote for more options than there exists, the manager who created to poll did something wrong.

Maybe this should be catched by the backend when creating/updating the poll (e.g. the min number of votes must be <= number of candidates).

**Comment by ostcar** [comment]
The client should block the creation of a poll, the the min votes is higher then the candidates.
