### ISSUE TITLE
Archiving meetings: Client side's to do

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-client#465]
see [impact on client side](https://github.com/OpenSlides/OpenSlides/wiki/MeetingArchived#impact-on-client-service):
- Archived meetings could be seen as usual, but could not be changed anyway, except the field `meeting/is_active_in_organization_id` by a user with OML SUPERADMIN right
- An active meeting can be set to archived by setting field `is_active_in_organization_id` to null with CML can_manage or users with a OML of can_manage_organization 
- it is not possible to start a conference within an archived meeting
- views with choices of meetings should have a limitation to active meetings, where archived meetings are not eligible and vice versa

Please, verify the text by using the link, before implementing. Last synchronized:; 12.8.2021

**Comment by GabrielInTheWorld** [comment]
Related backend-issue to resolve: OpenSlides/openslides-backend#899

**Comment by GabrielInTheWorld** [comment]
Actions:
- [meeting.archive](https://github.com/OpenSlides/OpenSlides/wiki/meeting.archive)
- [meeting.unarchive](https://github.com/OpenSlides/OpenSlides/wiki/meeting.unarchive)
