### ISSUE TITLE
Warning when deleting a user if they are assigned to something

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#495]
If a user is assigned to something (e.g. as candidate in an election, as speaker for a topic or as a submitter for a motion) and they should be deleted, then a warning should raise.
The warning should inform performing users, that the user to delete is linked to other models.

**Comment by tsiegleauq** [comment]
Requires a presenter, thus in the backend now

**Comment by GabrielInTheWorld** [comment]
Waits for OpenSlides/openslides-backend#947
