### ISSUE TITLE
A submitter can withdraw a motion

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#503]
A new permission is, that a submitter can withdraw a motion by themselves. Currently, if a motion is not in the first state of a workflow, but in one of the next states, a submitter cannot withdraw a motion (and put it back to the first state) and therefore they cannot edit the motion again. 
This can be done by a new permission in a motion-state.

**Comment by luisa-beerboom** [comment]
Analogously to what has been done in the backend, I'm closing in favor of the new feature of withdrawing in a specific state for the submitter.
