### ISSUE TITLE
<Missing content object> in a topic when user has `OML.can_manage_organization`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#508]
Steps: 
1. Create a new topic
2. Fill out the necessary fields (`name` - for example "huhu")
3. Go back to the agenda

See picture:
![topic_missing-content-object](https://user-images.githubusercontent.com/10206688/132831039-c8b529cc-f951-4cd9-a358-2d5a2d60bb22.png)

**Comment by GabrielInTheWorld** [comment]
Related autoupdate issue: OpenSlides/openslides-autoupdate-service#317

**Comment by emanuelschuetze** [comment]
Fixed in autoupdate service.
