### ISSUE TITLE
Show a warning on http

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#536]
OpenSlides4 does not support http. But it seems to work.

Could you add a warning or a banner, that http is not supported? This can not be done on the server, since the https could have been terminated on a proxy.

See https://github.com/OpenSlides/openslides-manage-service/issues/76

**Comment by tsiegleauq** [comment]
I'd propose this, yet would not disable forms here, automatic client tests without backend connection would require http.
![image](https://user-images.githubusercontent.com/10233032/139705955-a3e9a30f-d09d-4cbf-9151-25c0f364931e.png)
