### ISSUE TITLE
When a hidden motion is projected, a delegate sees only a white (empty) projector 

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#577]
Create a motion
Set it to a motion_state, in which only - for example - users can see the motion, if they are either its submitter or have the permission motion.can_manage
Project the motion
Sign in as a delegate (without the permission motion.can_manage), so they won't see the motion in the motion-list
Look at the projector/AP

**Comment by tsiegleauq** [comment]
OK, confirmed
