### ISSUE TITLE
New service to manage "batch" requests

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#578]
It is noticed (especially in #525), that there are requests, which take a long time to succeed. For those requests, the timeout for (angular-) requests will exceed. Therefore, a service to manage those requests is very useful.
Otherwise, we have to build an [interceptor](https://stackoverflow.com/questions/45938931/default-and-specific-request-timeout) to increase the timeout and "freeze" the current window to not interrupt the executing of requests.

**Comment by luisa-beerboom** [comment]
I think the action-worker-service does this for backend requests.
@jsangmeister do you thing this is still necessary? Are there any other requests the client might do that could potentially require this? Maybe to the media service?

Otherwise I think we can close this...

**Comment by jsangmeister** [comment]
Don't think so
