### ISSUE TITLE
See the `accepted` or `rejected` state of a forwarded motion in its origin

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#620]
After forwarding a motion, a submitter of its origin should see the (current?) state of the forwarded motion in the origin motion.

**Comment by luisa-beerboom** [comment]
This would require changes in backend and possibly autoupdate:
The restriction mode of `motion.state_id` would have to be changed to `A` in the backend, and the restrictions for `motion_state` would probably have to be changed in the autoupdate to also allow people who can see the origin motion of any motions which have that state.

I am creating the related issues in these services.

=> requires OpenSlides/openslides-backend#1564 and OpenSlides/openslides-autoupdate-service#599

**Comment by jsangmeister** [comment]
@luisa-beerboom this can be tackled now

**Comment by luisa-beerboom** [comment]
Also waiting on OpenSlides/openslides-backend#1596 now

**Comment by jsangmeister** [comment]
Waiting for https://github.com/OpenSlides/openslides-autoupdate-service/issues/599

**Comment by MSoeb** [comment]
This issue will be closed, because there is no need for this fearure. Additionally, this feature would need a clear concept of permissions. Therefore I will close it.
