### ISSUE TITLE
Cannot set logo for pdf header

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#621]
Try to set a logo as pdf header image does not work:
``
ERROR Error: Uncaught (in promise): Error: Datastore service sends HTTP 400. 
{'msg': "The key 'used_as_logo_$pdf_header_L_in_meeting_id' is no fqid, fqfield or collectionkey", 'type': 1, 'type_verbose': 'INVALID_FORMAT'}
``

**Comment by tsiegleauq** [comment]
> Error: Connect to mediaservice failed.

**Comment by tsiegleauq** [comment]
I suppose thats for the backend. The send request seems fine. Tracked on:

https://github.com/OpenSlides/openslides-backend/issues/1014

Will make a cypress for that one.
Tracked on: https://github.com/OpenSlides/openslides-backend/issues/1014
