### ISSUE TITLE
A user who is not allowed to see a page is not redirected to another page or an "error" page

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#626]
This contains two situations:
- [x] Going manually to `/motions/999` will result in an ugly motion-detail site as well as going to a "forbidden" motion (when the motion's state allows only the motion's submitters and users with the permission `motion.can_manage` to see the motion). These cases should show an "error" page (like "You are not allowed to see this page" or "This page could not be found")
- [ ] As delegate, going manually to `/settings/` within a meeting shows the settings-page although a delegate must not see that page. In such cases a user should be redirected to the startpage (or the first page, they are allowed to see).

**Comment by tsiegleauq** [comment]
> Going manually to /motions/999 will result in an ugly motion-detail site as well as going to a "forbidden" motion (when the motion's state allows only the motion's submitters and users with the permission motion.can_manage to see the motion).

it always has been like that. In OS4 we would not have the chance to check the autoupdate for information about that model. This possibility has not been there in OS3. Yet I suppose that would require a more generic solution which could take some effor.
