### ISSUE TITLE
getting "has voted" state from delegations

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#649]
leftover from #640
currently, we cannot ask the new vote service to get the "has voted" information from ones vote delegations.

**Comment by emanuelschuetze** [comment]
see https://github.com/OpenSlides/openslides-vote-service/issues/83

**Comment by luisa-beerboom** [comment]
@emanuelschuetze In OpenSlides/openslides-vote-service#83 I described the following bug in the client, which this "feature" fixes:

> This means that the client currently has no real way of knowing whether a delegation has already been voted on EXCEPT if the operator himself did it in that very session.
> 
> I.e. if you vote for a delegation, the component will show that you've already voted for that delegation. If you then simply reload the page, you will again be able to see the voting interface as if the vote didn't happen. You can then click on a vote option and send another vote request (and receive an error stating that you can't vote twice).

Considering that, I don't see why this isn't a 4.0 issue.

**Comment by luisa-beerboom** [comment]
Whoever ends up working on this, should probably also take a look at the `user_has_voted_for_delegations` attribute in the `poll.ts` and its references. I believe that field doesn't even exist in the backend any more.
