### ISSUE TITLE
Calculate number of voters

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#653]
When a poll-manager starts a poll, the number of vote_count appears, for example `0 / 100`

The second nummer (I call it max_vote_count) does not consider not present users.

For example:

1. Create a new meeting
2. Create two users in this meeting in the group "delegates"
3. Make sure only one of the users is present
4. Create a new motion in the meeting
5. Create a nominal or non-nomal poll with the group "delegates".
6. Click on "start voting"

You see the value `0 / 2`

I would expect `0 / 1`

**Comment by emanuelschuetze** [comment]
confirmed with current master
