### ISSUE TITLE
Improve the poll-box if noone has voted

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#654]
If you start and stop a poll before anyone has voted, the vote-box is a bit empty. Maybe it can be improved. Maybe there could be a message that noone has voted.

The current box looks like this:

![screen](https://user-images.githubusercontent.com/977937/142728613-e63f713c-fddb-47bd-9e14-c104a72900dc.png)

**Comment by luisa-beerboom** [comment]
Already fixed since 4.0
