### ISSUE TITLE
Set poll/backend field

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#655]
If I did not miss something, it is currently not possible to set the field [poll/backend](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2531-L2538)

When creating a poll, there should be a form field to decide, if it is a long running poll or a fast poll.

This feature is urged. It is currently not possible to test the postgres-backend of the vote service. See https://github.com/OpenSlides/openslides-vote-service/pull/66

See also the discussion in https://github.com/OpenSlides/openslides-backend/issues/1037 If we create the field `meeting/poll_default_backend`, then it will be also necessary to adapt the config page.

**Comment by ostcar** [comment]
I talked with @emanuelschuetze about this. He don't want the field in the poll-create form. He only wants a setting in the meeting to define the "meeting-default-poll-backend".

So only the setting has to be adapted. See: https://github.com/OpenSlides/openslides-backend/issues/1037

**Comment by GabrielInTheWorld** [comment]
What is your intention for this field? What should this feature do?
By hearing `meeting-default-poll-backend` I cannot imagine anything and I suggest to take another name.

**Comment by ostcar** [comment]
Currently the poll collection has the fields [poll/type](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2523), [poll/pollmethod](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2542), [poll/onehundred_percent_base](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2580) and [poll/entitled_group_ids](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2634).

Per meeting, the default value of this fields can be set in the config with the fields [meeting/motion_poll_default_type](motion_poll_default_type), [meeting/motion_poll_default_100_percent_base](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1073), [meeting/motion_poll_default_group_ids](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1077), [meeting/assignment_poll_default_type](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1190), [meeting/assignment_poll_default_method](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1194), [meeting/assignment_poll_default_100_percent_base](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1198), [meeting/assignment_poll_default_group_ids](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1202), [meeting/poll_default_type](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1221), [meeting/poll_default_method](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1225), [meeting/poll_default_100_percent_base](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1228) and [meeting/poll_default_group_ids](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L1232).

They all share the same name schema.

There is another important config for each poll, its the field [poll/backend](https://github.com/OpenSlides/openslides-backend/blob/e1f83b6807027ffac64134ee30740b8b4558443e/global/meta/models.yml#L2531). This field decides, if the poll should be saved in redis (fast, but no backups), or in postgres (slower, but with backups). The fast-backend (redis) backend should be used if users are together in the same room. The long-backend (postgres) should be used, if the poll goes for a longer time, for example a week.

It is currently not possible to set this poll-config in the UI. @emanuelschuetze suggests, that there is a meeting-specific config to set the "default" value. This value is used when a poll is started but it is not possible in the UI to set the value for an individual poll.

I suggested to call the new fields `meeting/motion_poll_default_backend, `meeting/assignment_poll_default_backend` and `meeting/poll_default_backend`. This would be the names, if you follow the name schema of the other poll-config fields.

But of cause, another name can be selected. Do you have any suggestions?

This feature is important. It is blocking us from testing the postgres backend, since there is no way to set it in the UI. See https://github.com/OpenSlides/openslides-vote-service/pull/66

**Comment by tsiegleauq** [comment]
you should not depend on the client to test backend / vote features. Removed high, will most likely set to 4.1 later

**Comment by ostcar** [comment]
All normal tests don't depend on the client. I am talking about performance tests. We have to test how fast the vote-service is with a single postgres-instance, with bgbouncer and specific settings. This can only be tested in a productive environment.

@peb-adr Do you think you can test the postgres backend of the vote service, if the UI does not have any setting to use the backend? You can still use it by manually changing the field `poll/backend` in the datastore.

**Comment by GabrielInTheWorld** [comment]
Well, this is not an issue for the client. Your feature request is, if any, a backend issue. You want to have a default value for this. This will be accomplished by setting this in the `initial-data.json` respectively the `example-data.json`. We would only implement a field to change this field per meeting.

**Comment by ostcar** [comment]
There are two issues. The [issue in the backend](https://github.com/OpenSlides/openslides-backend/issues/1037) to create the models.yml-fields and the issue here to set it in the ui.

It is not enough to set a value in the `initial-data.json` or `example-data.json`. To test the performance, it is necessary to create new polls with the postgres-backend.

**Comment by tsiegleauq** [comment]
> All normal tests don't depend on the client. I am talking about performance tests. We have to test how fast the vote-service is with a single postgres-instance, with bgbouncer and specific settings. This can only be tested in a productive environment.
> 
> @peb-adr Do you think you can test the postgres backend of the vote service, if the UI does not have any setting to use the backend? You can still use it by manually changing the field `poll/backend` in the datastore.

I can comprehend the desire to test the new voting features, but don't really see this as a relevant feature for a 4.0 feature.
Being feature complete and somewhat compatible with 3.4 is enough as it is right now, especially for the client. Doing some more docker magic by configuring the vote-backend during setup phase seems to be the adequate solution for the tome being. If the feature is small enough we can set it as `low` and `4.0`.

**Comment by GabrielInTheWorld** [comment]
I assume, that this is a feature, which will used only for e-voting. Is this correct?

**Comment by ostcar** [comment]
> I assume, that this is a feature, which will used only for e-voting. Is this correct?

Yes
