### ISSUE TITLE
AU-service does not send removed `logo_$_id`-keys anymore

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#675]
I sent this request to the AU-service:
```js
{
    "collection": "meeting",
    "ids": [
        2
    ],
    "fields": {
        // [...],
        "id": null,
        "logo_$_id": {
            "type": "template"
        },
        "font_$_id": {
            "type": "template"
        },
        "reference_projector_id": null,
        "is_active_in_organization_id": null,
        // [...]
    }
}
```

I got this response:
```js
{
    // [...]
    "meeting/2/id": 2,
    "meeting/2/is_active_in_organization_id": 1,
    "meeting/2/logo_$_id": [
        "web_header"
    ],
    "meeting/2/logo_$web_header_id": 5,
    // [...]
}
```

So far, so good...

But then, I remove the logo used as `web_header` (this request is regardless, but for the completeness):
```js
[
    {
        "action": "meeting.unset_logo",
        "data": [
            {
                "id": 2,
                "place": "web_header"
            }
        ]
    }
]
```

And I got the following response:
```js
{
    "meeting/2/logo_$_id": []
}
```

You see, the key `web_header` is missing. Therefore, the client does not notice, that the logo changed. 
Is this a bug or is this a result of previously committed changes (like OpenSlides/openslides-autoupdate-service#337)?

**Comment by GabrielInTheWorld** [comment]
Duplicate of #618

**Comment by tsiegleauq** [comment]
> Maybe we could think about changing the type of the field meeting/logo_$_id from a template field to a JSON-field. So you could save all logo-values for one meeting into one database key.

this would be the solution I'd propose. Currently, the client cannot get the required information in any meaningful way.
