### ISSUE TITLE
Meeting create form cannot be edited

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#701]
For some reason, most of the controls are not active.

![image](https://user-images.githubusercontent.com/10233032/145410231-69afb98c-5d0d-4fc8-a894-a221aa0aee8c.png)

**Comment by GabrielInTheWorld** [comment]
Which is your latest commit? I cannot reproduce this behavior on the current master or in our demo...

**Comment by tsiegleauq** [comment]
ah, I suppose only the version checked in OS4 was affected

**Comment by tsiegleauq** [comment]
@emanuelschuetze
