### ISSUE TITLE
Use color picker for tag color

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#726]
Currently, the tag color selector is slightly broken. On default there are two `#`-Symbols which prevents saving. Furthermore, we currently have two different color pickers. Use the normal color picker for selecting colors.

![image](https://user-images.githubusercontent.com/10233032/148577090-0d22deca-a80d-4a73-bb51-ba2520382908.png)

**Comment by jsangmeister** [comment]
tracked in https://github.com/OpenSlides/openslides-client/issues/1420
