### ISSUE TITLE
Password reset page

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#757]
There are some low priority issues on the password reset page

1. It would be nice, if the focus would be on the e-mail field. Currently it is necessary to click on it.
2. After clicking on the "reset" button, nothing happens (if the server is slow). There should be some feedback, that the button was clicked. For example disable it.

**Comment by luisa-beerboom** [comment]
@emanuelschuetze  While I was working on this I noticed something: 
I believe that after one sends a forget password request, the router attempts to navigate out of the page, but this throws an error. As a result one stays in the reset-password page.

Where is this navigation supposed to go? I would like to fix it while I'm at it.
