### ISSUE TITLE
Update metadata of a meeting

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#758]
I try to change the name of a meeting as a superadmin. Therefor I go to the page `/committees/1/edit-meeting/1`. I would expect, that it is possible, to change the fields on that form, but most of them are disabled. 

Looking at the wiki, it should be possible to change the name: https://github.com/OpenSlides/OpenSlides/wiki/meeting.update

**Comment by emanuelschuetze** [comment]
Currently, you have to add the superadmin to commitee management to edit a meeting. We can discuss this.

**Comment by luisa-beerboom** [comment]
Given that a superadmin can currently edit basically anything within a meeting with impunity even if he isn't even a participant, I do find it pretty illogical that he shouldn't be allowed to edit the metadata. Given that this is a pretty simple thing to change, I'll make a PR for this right now
