### ISSUE TITLE
No suitable error message if a client is offline and tries to send an HTTP request

### ISSUE THREAD

**Issue by Hhhhmmmmasch** [OpenSlides/openslides-client#759]
Hey there,

i finally managed to get all things up and running (v3.7 aka 4).
After having run './openslides initial-data', which resulted in

openslides-datastoreWriter-1  | [2022-01-16 02:06:06 +0000] [31] [INFO] Created position 2
openslides-datastoreWriter-1  | [2022-01-16 02:06:06 +0000] [31] [INFO] Events executed (1 UPDATE)
openslides-datastoreWriter-1  | [2022-01-16 02:06:06 +0000] [31] [INFO] UPDATE: ['user/1']

i opened https://localhost:8000 and tried to login with superadmin/superadmin.
This runs into "Error: IsTrusted: true" being displayed.

What am i still doing wrong?

Best wishes and thanks!

**Comment by normanjaeckel** [comment]
This looks like a client error.

**Comment by Hhhhmmmmasch** [comment]
> This looks like a client error.

Meanwhile was able to log in after changing the proxyconf to 0.0.0.0:8000:8000 and running it without upstream proxy (it's not reachable from outside)..
In a very few cases the message "Error: IsTrusted: true" shows up only very few times.

The login-problem was a proxy-issue and presumably result of a request-timeout.

Going on ...

**Comment by GabrielInTheWorld** [comment]
I don't think, this is a client issue...

**Comment by GabrielInTheWorld** [comment]
Maybe, this happens, if a client is offline and tries to send an HTTP-request.
