### ISSUE TITLE
After signing out, the banner "Archived" is displayed

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#796]

**Comment by bug0002** [comment]
I can make a few additions to the problem description : 

This problem only seems to affect users (not administrator).

A yellow-orange banner is displayed. This may correspond to the following function

openslides-client/client/src/app/core/core-services/active-meeting.service.ts

    private createArchivedBanner(): BannerDefinition {
        return {
            icon: `archive`,
            class: `background-warn`,
            text: `Archived`
        };
    }

**Comment by emanuelschuetze** [comment]
Done in current main branch.
