### ISSUE TITLE
Spaces after usernames

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#799]
- [ ] In the user list, groups of users are separated by " , ". Remove the space before the comma.
- [ ] In the user detail view, groups of users are separated by " , ". Remove the space before the comma.
- [ ] ~~In the list of submitters, there is a space after the username of a submitter~~

**Comment by bug0001** [comment]
a good place to start may be

OpenSlides/openslides-client/client/src/app/site/users/components/user-list

and perhaps the "groupsCell" class.

Within it, "<span *ngIf="!last">,</span>" defines the symbol (so long as not the last item)

**Comment by bug0001** [comment]
Update : This was the right location.

The issue being some linting tool transforming

"<span *ngFor="let group of getUserGroups(user); let last = last"> {{ group.getTitle() | translate }}<span *ngIf="!last">,</span></span>"

which does not cause problems, into a prettier version which causes formatting to be interpreted as empty space.

**Comment by bug0001** [comment]
Please specify in which area of the application "In the list of submitters, there is a space after the username of a submitter" takes place.
