### ISSUE TITLE
I cannot add users to a meeting if there is already a superadmin assigned to

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#841]
The message "You have not the permissions to modify a superadmin" came up.

Steps to reproduce:
1. Create an account, which is an administrator of their organization
2. Create a meeting and assign a superadmin as administrator of the meeting
3. Try to assign the previously created account as administrator of the meeting (in addition to the superadmin)

**Comment by luisa-beerboom** [comment]
I couldn't replicate this no matter how I try to do it.
Also I couldn't even find the given error message in the current code.

I found two different things:
1. Trying to select another user through the user search selector for meeting admins, while being logged in as a committee manager without OML.user_can_manage throws massive amounts of missing permission errors.
2. If (in dev mode) you
   1. As an orga admin use the user search selector for meeting managers and
   2. Search for the superadmin (i.e. 'admin')
   3. You'll see that his name is displayed as `null Administrator`

I'll write new issues for this two things, meanwhile could someone please take another look at whether this is even still an issue? (maybe @emanuelschuetze or @MSoeb ?)

**Comment by MSoeb** [comment]
Tried to reproduce the original problem. Can't find any problems. @emanuelschuetze close it?
