### ISSUE TITLE
Rework the setting under Participants (vote weight & delegation of vote)

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#848]
### 1. Existing setting: Activate vote weight .../settings/participants

If active, then under Participants .../users/...

- [x] Filter "Vote weight" is visible
- [x] Sort option "Vote weight" is visible

If deactivated, then the previously mentioned items are not visible.

> ### 2. New setting: Activate Delegation of vote .../settings/participants
> 
> **Add new setting** "Activate Delegation of vote" under "Participants", below "Activate vote weight"
> 
> If active, then under Participants .../users/...
> 
> - [ ] Filter "Delegation of vote" is visible
> - [ ] In the **big edit view** of a user the dropdown menu
>     - [ ] "Voting right received from (principals)" is visible
>     - [ ] "Voting right delegated to (proxy)" is visible
> - [ ] in the **quick edit dialog** of a user the dropdown menu
>     - [ ] "Voting right received from (principals)" is visible
>     - [ ] "Voting right delegated to (proxy)" is visible
> 
> If disabled, then the previously mentioned items are not visible.

**Comment by luisa-beerboom** [comment]
The first part I will do now, the second part is going to require quite a bit of work (probably also in the backend)
It also will need to be discussed how that is going to be done.

I've delegated that to another issue ( #1512 )
