### ISSUE TITLE
Motions: Voting possible, although the status does not allow it

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#849]
### Describe the bug
.../motions/...
It is possible to create a poll/vote in every status, although the workflow does not allow it.

### Expected behavior
Polls and the possibility to create a poll should only be possible if in the workflow .../motions/workflow/... the setting "Allow create poll" is active for the selected status. Otherwise not.

**Comment by emanuelschuetze** [comment]
@alveolus Should be done. Please retest and close.

**Comment by rrenkert** [comment]
@emanuelschuetze Is there a PR that fixes this one? We should not have open issues for month that are already done.
However I can not reproduce the issue in a short test.

**Comment by jsangmeister** [comment]
At least in the backend this is not done yet. I will open an issue there

**Comment by luisa-beerboom** [comment]
@rrenkert , @jsangmeister  since this seems to be resolved in both client and backend, I'll close this issue now
