### ISSUE TITLE
Adapt changes in the models.yml

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#85]
From https://github.com/OpenSlides/OpenSlides/pull/5802:

- delete role model and repo
- Add `organisation_management_level` to user
- Change `about_me`, `comment`, `number`, `structure_level`, `vote_weight` to template fields. This requires to add methods to `user.ts` and `view-user.ts`.
- Add fields `default_number` and `default_structure_level`. In the getters of `number` and `structure_level` fall back to the defaults, if there are no specific numbers/structure levels
- watch out for `default_vote_weight`, it may be added in the PR
- adapt all templates and autoupdate queries in the user repo.

**Comment by GabrielInTheWorld** [comment]
> * delete role model and repo

Waht about `ViewRole` and its dependencies?
What about the relations between organisation and role? Simply change the `ViewRole` to `ViewUser`?

**Comment by FinnStutzenstein** [comment]
Just delete them. Look into the models.yml: There are no relations between organisation and user; The role system is replaced with the new collectionfield `user/organisation_management_level`
