### ISSUE TITLE
Vote/Poll: List and quantity of entitled users are wrong

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#851]
### Describe the bug
The list of entitled users in the detailed view of a vote/poll is not correct. Not the entitled (and present) users during a vote/poll are listed, but all persons who were present during the vote/poll. Even users who are not authorized are listed there. This affects the content of the list as well as the data (quantity) above the list.

### How to Reproduce
.../motions/polls/...
There must be more persons present than those entitled to vote, then the bug is easy to reproduce.

### Expected behavior
In the list of entitled users, only the authorized voters who were present during the vote/poll are displayed. The last number above the list ("23 out of 23") should be the number of voters, who were present (=17, one person did not vote in my case).

### Screenshot
![2022-02-16 17 52 10 verdi openslides com 27e8c24824fd](https://user-images.githubusercontent.com/23032204/154481525-cea6665f-57a0-4ef4-84f6-dab1d7aa3340.png)

**Comment by emanuelschuetze** [comment]
this is a backend issue, see https://github.com/OpenSlides/openslides-backend/issues/1220
