### ISSUE TITLE
Beautify detail view of a vote

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#852]
The list "Single votes" looks very nice. The first line contains the name of the person, the second line contains the structure level (text is grayed out, which looks nice).

The list "Entitled users" on the other hand is the ugly brother/sister. The design of the list here should be just as pretty as the "Single votes" list is. So:

- The first line contains just the name of the person
- The second line contains the structure level (text grayed out).
- The list uses its width wisely (less wrapping)

The icon for "Vote submitted" (I assume) is currently a check mark. This is a bit confusing, because users might assume that the icon indicates presence. But this is not the case.

That's why I suggest: The icon should be changed to `<mat-icon>how_to_vote</mat-icon>` <img width="29" alt="20220217-133955" src="https://user-images.githubusercontent.com/23032204/154484741-efa97077-d768-4f44-a52b-87fedbf8ee8e.png"> and behind it should be the text "vote submitted" or "vote has been cast" or something like that.

**Comment by emanuelschuetze** [comment]
nice suggestion

**Comment by alveolus** [comment]
Further suggestion: Next to the graphic, below "Valid votes", the number of the entitled users during the vote is shown. Example:

<img width="30" alt="20220217-140730" src="https://user-images.githubusercontent.com/23032204/154488176-44f68632-6239-473d-b6ba-441f34916c08.png"> Entitled users     17

Icon: `<mat-icon>group</mat-icon>`
