### ISSUE TITLE
Error message when trying to change the title of a vote

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#853]
### Describe the bug
The error message "Anonymous is not enabled for meeting [number]" is displayed when trying to change the title of a (published) vote. The error message itself is also very meaningless.

### Where?
Detail-View of a Motion .../motions/...
Detail-View of a Poll ...motions/polls/...

### Expected behavior
Like on OpenSlides 3: Title can be changed and the change is applied correctly without error message.

<img width="774" alt="20220217-141342" src="https://user-images.githubusercontent.com/23032204/154491883-2972d42f-c79a-4318-961a-ce1eee14ce4e.png">

**Comment by luisa-beerboom** [comment]
Cannot reproduce in current version:
OpenSlides Version: 4.0.0-beta-20220502-464a0e5
