### ISSUE TITLE
Make changes to the handling of `projector_countdown`s used as something 

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#859]
Every meeting has a projector_countdown used as poll-countdown and a projector_countdown used as list_of_speakers-countdown by default. Those projector_countdowns cannot be deleted. Therefore, hide the function to delete them. Also, we should implement a toggle activate/de-activate these projector_countdowns. If they are deactivated, they should be hidden.

**Comment by bastianjoel** [comment]
Disabling the delete function of these countdowns was already implemented by #771
