### ISSUE TITLE
Strange "guest view" although guest mode is disabled

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#873]
### Setup
Latest Dev Setup
Completely fresh instance, only default committee
No settings were changed

### Describe the bug & How to reproduce
It is possible to get into a kind of "guest view" if you click on the OpenSlides title logo under **Legal notice** `.../login/legalnotice` or under **Privacy policy** `.../login/privacypolicy`. The OpenSlides title logo has the (funny) link `.../?checkBrowser=false`

You must not be logged in. If you click on the title logo, you will land on the page `.../?checkBrowser=false`. There it is possible to see **Calender** and **Committees**.

View under Calendar: _No meetings available_
View under Committees: _No data_

On the top right you are shown as the user "Gast" (yes, the german Gast, not the english Guest). If you click on **Gast** > **Login**, then nothing happens.

### Expected behavior
This page should not be visible. You should land on the main URL/Login-Page if you click on the OpenSlides title logo under Legal notice `.../login/legalnotice` or under Privacy policy `.../login/privacypolicy`.

**Comment by GabrielInTheWorld** [comment]
Related to #800.

**Comment by GabrielInTheWorld** [comment]
Closed by #1057
