### ISSUE TITLE
Global search is disabled

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#875]
In OS 3 a search function was also available on the mobile view. This was some kind of "global search", however.

Since there is no global search anymore in OS 4, at least the search (bar) of each list should also be usable in the mobile view. This is especially useful at events, where you can quickly solve problems, because (for example) you are searching through the Participants list for a certain name on your smartphone.

### Feature request & a first Idea

On the mobile view, a magnifying glass <img width="29" alt="20220224-205120" src="https://user-images.githubusercontent.com/23032204/155597463-adad3a9e-e44a-4ab5-a863-71c441b62940.png"> is displayed to the left of "Filter". If the magnifying glass is tapped, a search bar or something like that appears for the current list view I am in. Icon: `<mat-icon>search</mat-icon>`

It should definitely be considered how to embed the search function in the most user-friendly (and pretty) way.

**Pure interest question**:
Why is the global search function no longer available?

**Comment by GabrielInTheWorld** [comment]
This is due to the fact, that a client will never request every date in a database. To activate the global search function again, we have to implement a "search-service". This is not a task for the client, but a task for the entire OpenSlides-team.

**Comment by rrenkert** [comment]
See [OpenSlides/openslides-serarch-service](https://github.com/OpenSlides/openslides-search-service) for server side progress.

**Comment by bastianjoel** [comment]
This is done.
