### ISSUE TITLE
Profile: Use the sun icon for light mode

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#876]
If you are in dark mode and go to the profile, the button to switch to light mode looks like something like "Settings". This seems a bit misleading to me. Instead of the weird/abstract "brightness_low"-icon, the well-known sun icon should be used.

Old Icon: <img width="28" alt="20220224-211642" src="https://user-images.githubusercontent.com/23032204/155600740-09ed3928-0025-4f79-91c3-19b00b1ce97e.png"> `<mat-icon>brightness_low</mat-icon>`
New Icon: <img width="29" alt="20220224-211322" src="https://user-images.githubusercontent.com/23032204/155600225-1e2dd59e-3e3e-47a9-9181-130ddc067b5d.png"> `<mat-icon>wb_sunny</mat-icon>`

**Comment by GabrielInTheWorld** [comment]
If this icon is available for the client, we will change it. (also the moon-icon will be changed)
