### ISSUE TITLE
Organization tags aren't loaded on the committee-list

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#898]

**Comment by GabrielInTheWorld** [comment]
Fixed by #902.
@alveolus Feel free to re-open this issue, if this is still not fixed.

**Comment by alveolus** [comment]
Organisations-Tags in der Gremien-Liste werden weiterhin nicht geladen.

### Kennzahlen
- Anzahl der Gremien unter .../committees: 7029
- Anzahl angelegter Tags unter …/organization-tags: 25

### Fehler in der Konsole
- [Log] Handle stream error: (main.1e51ae351040b6413d67.js, line 1)
  - c
    - error: {type: "InternalError", msg: "Ups, something went wrong!"}
    - reason: "Error while reading progress event"
    - type: "Unknown"
  - c Prototyp
    - constructor: function()
      - arguments: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.
      - caller: TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.
      - length: 3
      - name: "c"
- [Log] 975465:n default: Retry counter 0 of 3 (main.1e51ae351040b6413d67.js, line 1)

**Comment by alveolus** [comment]
I'm closing this issue, the bug is fixed. See https://github.com/OpenSlides/openslides-client/issues/1159
