### ISSUE TITLE
Counting current active users leads to an error

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#913]
1. Go to a meeting
2. Open the private policy
3. Click on "count users"

**Comment by MSoeb** [comment]
The problem occurs again. Please reopen ticket.

**Comment by jsangmeister** [comment]
seems like https://github.com/OpenSlides/openslides-client/pull/976/ was skipped during a rebase for gabriels client rework. Re-integrating the changes should help
