### ISSUE TITLE
The autopilot does not work properly under Safari

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#916]
OpenSlides won't automatically be refreshed.

**Comment by emanuelschuetze** [comment]
@alveolus please test

**Comment by alveolus** [comment]
@GabrielInTheWorld Exactly which component(s) of the autopilot are affected by this problem? Projection, agenda, speakers list, election, polling — or all? At first glance, it looks fine on the latest macOS and iOS. But I'd like to look more closely if it affects specific component(s).

**Comment by GabrielInTheWorld** [comment]
@alveolus Feel free to close this issue. I only opened it, because it was reported in "the" list.

**Comment by emanuelschuetze** [comment]
@alveolus Please reopen this issue if there are still any problems with safari.
