### ISSUE TITLE
CSV-Import creates committees multiple times

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#927]
The import via CSV file under .../committees/import creates committees multiple times. I'm using the latest dev-setup from this morning.

My CSV file contains **118** committees with unique titles. According to the preview in the importer, the file was in the correct format. Also there were no error messages after the import.

<img width="832" alt="20220224-092031" src="https://user-images.githubusercontent.com/23032204/155489360-e268c136-b181-4cb8-a244-b5ff895922bb.png">

If you go to Committees .../committees after the import, you can see **219** committees there:

- 1 × default committee
- 118 × committees from the CSV file
- 100 × additionally created committees with already existing committee titles

Data stored in the multiple created, incorrect "ghost" committees:

- Title
- Assigned accounts
- Committee management

Example of a incorrectly created "ghost" committee
Please note ID/URL, possibly relevant for the fix: .../committees/**22**

![2022-02-24 09 43 30 localhost c9dcac547906](https://user-images.githubusercontent.com/23032204/155489857-ca2717bc-3427-4c0b-803f-1660dfb4c07c.png)

Data stored in the correctly created committees:

- Title
- Forward motions to
- Receive motions from
- Assigned accounts
- Committee management

Example of a correctly created committee
Please note ID/URL, possibly relevant for the fix: .../committees/**122**

![2022-02-24 09 43 36 localhost 1a15066a8761](https://user-images.githubusercontent.com/23032204/155489890-32a3c823-867d-476b-87dd-807a711dd767.png)

**Comment by emanuelschuetze** [comment]
@alveolus Can you retest this issue please?
