### ISSUE TITLE
Investigate on TCP-/HTTP/2-connections

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#938]
The connections to the autoupdate server are still closed.

**Comment by emanuelschuetze** [comment]
cannot reproduce any disconnections (also tested: laptop opens projector, goes into 'standby'/sleep mode, project new topic from other device, laptop wakes up -> new topic is shown on projector) -> looks good. So wait until new problem is reported.

**Comment by GabrielInTheWorld** [comment]
> cannot reproduce any disconnections (also tested: laptop opens projector, goes into 'standby'/sleep mode, project new topic from other device, laptop wakes up -> new topic is shown on projector) -> looks good. So wait until new problem is reported.

Due to this behavior, I close this issue. @emanuelschuetze, @alveolus or @rrenkert feel free to re-open this issue if any problems came up.
