### ISSUE TITLE
Check, if category prefix can be optional

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-client#95]
Followup from https://github.com/OpenSlides/openslides-backend-coordination/issues/54

Check, if the PR https://github.com/OpenSlides/openslides-backend/pull/401 solve the issue.

**Comment by GabrielInTheWorld** [comment]
Successfully handled the following request:
```
[
  {
    "action":"motion_category.create",
    "data":[
      {
        "meeting_id":1,
        "name":"Herr Der Ringe",
        "prefix":"None",
        "parent_id":"None"
      }
    ]
  }
]
```
State: b236793abf72846d5bf4e027f987d254a4711c41

**Comment by FinnStutzenstein** [comment]
Are you sure, that `"None"` is empty? It is a string...

**Comment by GabrielInTheWorld** [comment]
> Are you sure, that `"None"` is empty? It is a string...

This is an excerpt of logs from backend (in json). The client sent `null`.

**Comment by FinnStutzenstein** [comment]
Oh, can you provide this request and the resulting change to the datastore in a new issue in the backend? Thanks!

**Comment by GabrielInTheWorld** [comment]
> Oh, can you provide this request and the resulting change to the datastore in a new issue in the backend? Thanks!

Done.
