### ISSUE TITLE
It is not shown if a user is a natural person, a committee or what else

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#958]
The detail and list view of participants/accounts should reflect, if a user is a committee, is active... which is already the "state of the art" in OS3: https://demo.openslides.org/users.

**Comment by emanuelschuetze** [comment]
Right. Only user manager (with 'can_manage') can see special fields. We should check which fields in which view (account list/detail or meeting user list/detail) for which user are possible to see.
