### ISSUE TITLE
Restructuring of the Access-data PDF for a participant (swap Access and WiFi block)

### ISSUE THREAD

**Issue by f-fritz** [OpenSlides/openslides-client#962]
Hey

For my use case we do have User Accounts in order to conduct elections but we do not have a special WiFi network set up for the participants. I wonder whether there is any use case where you would have a WiFi but no personalised access data.

If there is none, maybe the "OpenSlides access data" block could be swapped with the "WLAN access data" one because the document looks a little out of balance if the WiFi section is completely unpopulated while the access section is (populated). Alternatively, the access section may also be completely hidden if no network name is provided at all.

Even though that is only a minor (cosmetic) concern and not at all relevant for general usage I would be interested in hearing your thoughts

(OpenSlides 3.3)

**Comment by GabrielInTheWorld** [comment]
If I understand your hint correctly, then this issue is related to OpenSlides/OpenSlides in version 3.3/3.4.
Therefore, I will transfer it to the correct repo, unless you want it for OS4 as well..?

**Comment by f-fritz** [comment]
Sorry, looks like I mixed up the repos... This was indeed meant as a feedback for 3.3/3.4 and has yet nothing to do with OS4
