### ISSUE TITLE
Error when user with OML `can_manage_users` creates user

### ISSUE THREAD

**Issue by m-andreas** [OpenSlides/openslides-client#984]
**Describe the bug**
When User for Commitee creates a User he should be able to

**How to Reproduce**
Create User for a Comittee with Account Managment Role

1. Go to /accounts/create
2. Fill In Data
3. Click Save
4. See error (data.committee_$_management_level must be object)

**Expected behavior**
Should Create User

**System information**

- OpenSlides-Version: 4 beta

**Comment by jsangmeister** [comment]
Confirmed. Thanks for your bug report!

**Comment by jsangmeister** [comment]
@GabrielInTheWorld feel free to change the labels, I tagged it as I viewed it appropriate. Probably easiest to just remove the field from the payload in this case.
